opensource-observer/oso

indexer/src/utils/parsing.ts, indexer/test/utils/parsing.test.ts
* Previously the owner and repo name must exist to return
* Now can parse GitHub urls with just the owner/organization without a repo
=> fix: parsing GitHub urls

indexer/src/actions/oss-directory.ts, indexer/src/cli.ts, indexer/src/db/entities.ts, indexer/src/events/github/unpaginate.ts
* Skip any project files where there is already a Project entity without checking that the contents are consistent.
* Add an ora spinner for the GitHub API rate limit
=> feat: skipExisting importOssDirectory

.github/workflows/indexer-autocrawl.yml, .github/workflows/indexer-manual.yml, package.json
* Previously we were running the build for frontend on the indexer jobs. This requires environment variables we don't have
* Reduce the scope of the build to just the indexer
=> fix: index jobs should only build indexer

indexer/src/actions/oss-directory.ts
@ryscheng. I noticed this the other day when I ran the import script locally. I am not sure this is the solution but it allowed me to move forward so I could replicate what's on the prod db on my local db.
Ideally we'd have a whole setup to track failures and maybe even backoff on certain event collection if they're continuously failing (so we don't, say, blow API quotas)
=> Do not fail on errors. 

frontend/app/artifact/[namespace]/[...name]/page.tsx, frontend/app/project/[...slug]/page.tsx, frontend/components/dataprovider/supabase-query.tsx, frontend/lib/errors.ts, frontend/lib/paths.ts, frontend/lib/supabase-client.ts, frontend/middleware.ts, frontend/plasmic-init-client.tsx
`/artifact/:namespace/:name`
* Added global middleware to handle these routes. Just proxies to `/artifactById/` and `/projectById` respectively
* Abstract out the ArtifactNamespace enum matching to a generic function
* Abstract out SupabaseQuery to a generic function
=> feat: middleware to proxy `/project/:slug` and

indexer/package.json, indexer/prisma/migrations/20230828184711_add_contributor_namespace_git_email/migration.sql, indexer/prisma/migrations/20230828191601_add_contributor_namespace_git_name/migration.sql, indexer/prisma/schema.prisma, indexer/src/actions/github/fetch/commits.ts, indexer/src/cli.ts, indexer/src/db/artifacts.ts, indexer/src/recorder/actors.ts, indexer/src/recorder/index.ts, indexer/src/recorder/recorder.ts, indexer/src/recorder/types.ts, indexer/src/utils/array.ts, pnpm-lock.yaml
This is a bit of a large PR but mostly cause I took some of the things I learned from pull the contract data and made a (hopefully) easier to use interface (that is a work in progress) for recording events to the database. Now, you just need to have a "recorder" type that takes `IncompleteEvent`. These objects look like: 
```
interface IncompleteEvent {
eventTime: Datetime;
eventType: EventType;
artifact: IncompleteArtifact;
contributor: IncompleteContributor;
amount: number;
details: object;
};
```
The `IncompleteContributor` and `IncompleteArtifact` allow us to just specify the name/namespace of either and the recorder will handle all of it. Additionally, I had performance issues running imports on events while also handling idempotent writes.  This abstracts all that away. So you just …
=> Load commits (with a generic event recorder)

.eslintrc.json
* Disallow use of `preview: true` in objects. This is a common mistake in plasmic-init.ts
* Steer people towards using logger instead of console
* Forbid use of 'prompt'
=> fix: eslint should prevent you from using restricted stuff

indexer/src/actions/github/fetch/pull-requests.ts
Reopen/Close events weren't tracking the original author of the PR/Issue. This adds that to the details.
=> Track original author for Issues and PRs

frontend/components/dataprovider/event-data-provider.tsx
* Looks like SWR was inappropriately caching invalid queries.
* Updated the SWR key to be unique per query params
=> fix: latency issues in EventDataProvider

frontend/app/artifact/[namespace]/[...name]/page.tsx, frontend/app/project/[...slug]/page.tsx, frontend/middleware.ts
* Abstract out ArtifactPage and ProjectPage into re-usable components
* In Plasmic, the pages now wire the params/queries into the component props
* In the dynamic routes, plumb the id/metadata and render the Plasmic component directly
=> feat: update dynamic routes for Artifact/Project pages

frontend/components/dataprovider/event-data-provider.tsx
* We were caching the formatted data
* Instead, just cache the SupabaseQuery, and format afterwards.
* Let's see if this will allow us to only query once across charts
=> fix: SWR caching between charts

indexer/package.json
=> fix: GitHub actions deploy for DB migrations should use `prisma deploy`,

indexer/src/cacher/time-series.test.ts, indexer/src/utils/ranges.test.ts, indexer/src/utils/ranges.ts
Forces usage of UTC if not specified for range instantiation
=> Range: Force UTC

indexer/src/actions/dune/funding-event-collector.ts, indexer/src/actions/dune/index.ts, indexer/src/actions/github/fetch/commits.ts, indexer/src/actions/github/fetch/common.ts, indexer/src/actions/github/fetch/pull-requests.ts, indexer/src/actions/github/fetch/repo-followers.ts, indexer/src/cli.ts, indexer/src/db/events.test.ts, indexer/src/events/npm.ts, indexer/src/recorder/group.ts, indexer/src/recorder/recorder.ts, indexer/src/recorder/types.ts, indexer/src/scheduler/common.ts, indexer/src/scheduler/pointers.test.ts, indexer/src/scheduler/pointers.ts, indexer/src/scheduler/types.ts, indexer/src/utils/async-results.test.ts, indexer/src/utils/async-results.ts
This is a fairly big one: 
* Adds higher granularity responses for each job
* Attempts to structure so we can report failures at finer grained points.
* Adds grouping of recordings
* This is useful when the events are streamed in a way that is unordered and ungrouped. So we can commit a single artifact at the end of the `collect` step, but only if all of it's dependent events are properly recorded.
* Fixes `github-followers` collector. Now runs to completion
* Fixes `github-issues` collector. Now runs to completion
=> Adds Execution Summaries for each job

indexer/src/db/migration/1696805280733-fix-event-source-id-index.ts, indexer/src/db/orm-entities.ts, indexer/src/recorder/recorder.ts
As designed, a single `sourceId` of an event can potentially create multiple event types. This could prove useful in the future, to use as some kind of relationship but for now this is just how it works for issues.
=> Event index should be unique by type X sourceId

frontend/app/artifact/[namespace]/[...name]/page.tsx, frontend/app/project/[...slug]/page.tsx, frontend/components/dataprovider/event-data-provider.tsx, frontend/components/widgets/algolia.tsx, frontend/lib/common.ts, frontend/lib/errors.ts, frontend/lib/graphql/queries.ts
* Add a new `entityType` to choose between artifact or projects
* Add separate components for doing different graph queries
* Clean up the event data parsing and normalization
=> feat: EventDataProvider can accept either artifact or project IDs

indexer/src/db/migration/1697236370397-event-add-size-and-details.ts, indexer/src/db/orm-entities.ts
Arrived at this to pragmatically add the contract call count _and_ the gas totals. The `size` field is a bigint so it can fit gwei measurements. We can rename the field later but this is very much pragmatic. Dune data is imminently being loaded.
=> Add additional fields to events

frontend/components/dataprovider/event-data-provider.tsx, frontend/components/dataprovider/table-data-provider.tsx, frontend/lib/config.ts, frontend/lib/graphql/queries.ts, frontend/plasmic-init-client.tsx
* Adds GraphQL queries for fetching aggregates by artifactId or projectId
* Removes `path` dependency in `config.ts`
* Removes `kpiCard` option in EventDataProvider. We'll migrate to using an AggregateDataProvider in the future
=> feat: Add aggregate GraphQL queries

frontend/components/dataprovider/event-data-provider.tsx, frontend/lib/graphql/queries.ts, indexer/README.md, indexer/src/db/migration/1698257133416-drop-events-by-artifact-project.ts, indexer/src/db/migration/1698258468674-recreate-events-to-artifact-project.ts, indexer/src/db/orm-entities.ts
* There were a few manual steps that happened in between. (1) I manually refreshed all of our continuous aggregates and materialized views
(2) I manually tracked the materialized views in Hasura and added anonymous SELECT and aggregation permissions
* added instructions in README on how to do this refresh
* fixed the GraphQL queries in the frontend to use the new materialzed views
* Migration to drop the old EventsDailyByArtifact/Project views
* Migration to drop and recreate the new materialized views. For some reason they didn't get registered as continuous aggregates by TimescaleDB
=> feat: fix the build post new materialized views

frontend/components/dataprovider/event-data-provider.tsx, frontend/lib/graphql/queries.ts
* Add queries for monthly/weekly event data queries
* Dynamically determine the ideal bucket width and switch queries
* Fixed a bug that accidentally introduces leading zeroes to time series data
* Only do gapFill if using bucketWidth=day
=> feat: dynamically switch between monthly/weekly/daily aggregations

frontend/app/project/[...slug]/page.tsx, frontend/components/dataprovider/event-data-provider.tsx, frontend/components/dataprovider/provider-view.tsx, frontend/components/dataprovider/supabase-query.tsx, frontend/components/dataprovider/table-data-provider.tsx, frontend/lib/cached-queries.ts, frontend/lib/graphql/queries.ts, frontend/lib/types.ts, frontend/plasmic-init-client.tsx
feat: TableDataProvider shell
* Abstracting out the Plasmic code component registration props into
reusable snippets
* GraphQL to get projects by collection slugs
* GraphQL to get event sum aggregates
=> feat: TableDataProvider starter

.eslintrc.js, frontend/components/widgets/tremor.tsx, frontend/plasmic-init-client.tsx, frontend/tailwind.config.js, frontend/tsconfig.json
* Currently the barlist will use your system settings for light vs dark mode by default. But when you specify a color, it will go to lightmode for the background. If the system settings are dark mode, the text also shows up light, which is ugly.
* This just hardcodes everything to light mode unless we explicitly set dark mode
* I also add a hard-coded value formatter to use toLocaleString() on values
=> feat: barlist colors set to light mode

frontend/components/dataprovider/event-data-provider.tsx
* Previously we'd remove all preceding and trailing empty data points so that the area charts would zoom into the place with action
* Removing this for now since it can be confusing with the date picker
=> fix: removing trimming function in areacharts

indexer/src/db/migration/1698960376757-users-monthly-to-project.ts, indexer/src/db/orm-entities.ts
* Note that this cannot be a continuous aggregate (doesn't allow set operations)
* This means this materialized view needs to be refreshed periodically manually
=> feat: materialized view for users_monthly_to_project

frontend/app/api/project-event-aggregates/route.ts, frontend/components/dataprovider/table-data-provider.tsx, frontend/lib/common.ts, frontend/lib/graphql/cached-queries.ts, frontend/lib/graphql/queries.ts, frontend/lib/types/errors.ts, frontend/plasmic-init-client.tsx
* TableDataProvider updated to leverage our route handler
* Update route handler to access eventType names in addition to ids
* Add `assert` to common
* Cache the route handler
* Cache getting all event types
* Register TableDataProvider as a code component
=> feat: TableDataProvider

frontend/app/api/project-event-aggregates/route.ts, frontend/components/dataprovider/table-data-provider.tsx, frontend/lib/graphql/cached-queries.ts
* Update project-event-aggregates to accept collectionSlugs
* Reduce surface of TableDataProvider, get the projects server-side now
* Added a cached query for getting projects by collection slugs
=> feat: TableDataProvider pt 2

indexer/src/recorder/recorder.test.ts, indexer/src/recorder/recorder.ts, indexer/src/scheduler/types.ts
This was causing some issues. It's not bad to just swallow the errors for now, but we can create some utilities to check for errors after things have completed.
=> Recorder: Don't treat dupes as errors for now

indexer/src/collectors/dune-daily-contract-usage.ts, indexer/src/collectors/dune-funding-events.ts, indexer/src/collectors/github-commits.ts, indexer/src/collectors/github-followers.ts, indexer/src/collectors/github-issues.ts, indexer/src/collectors/github/common.ts, indexer/src/collectors/npm-downloads.ts, indexer/src/recorder/group.ts, indexer/src/recorder/recorder.test.ts, indexer/src/recorder/recorder.ts, indexer/src/recorder/types.ts, indexer/src/scheduler/common.ts, indexer/src/scheduler/types.ts, indexer/src/utils/debug.ts
We still have issues with some of the collectors for contract backfills. There are just so many events. This will need some clean up but it has a massive speed increase. Follow on issues will be created to clean all this up. This should significantly improve performance, but it comes at the cost of potentially more data written to the database that needs to be cleaned up periodically. 
In terms of speed comparisons. This can write millions of rows in ~20seconds. Compared with previous versions of the recorder that may have taken upwards of 15 minutes. It also needs a fraction of the ram on the executing machine as the original recorder.
=> Massive recorder speed improvements

frontend/components/widgets/algolia.tsx, frontend/plasmic-init-client.tsx
* Accept a children slot for the Algolia search trigger
* Still default to a SearchIcon if children is missing
=> feat: search box accepts children

indexer/src/recorder/recorder.ts
This should alleviate some issues related to dune errors to get moving through the queue.
=> Update the timeout for the recorder

.github/workflows/indexer-create-job.yml, .github/workflows/indexer-refresh-mvs.yml, indexer/src/scripts/db-utilities.ts
On the CLI it defaulted to 2015 which caused us to miss many events when refreshing.
=> Fix the `startDate` for `refresh-mvs`

docker/Dockerfile, docker/compose.yaml, docker/install.sh, indexer/package.json
Something must of have changed about the node or ts-node version deployed on github actions. It was no longer accepting ts-node --esm. This addresses that. Sadly, this wasted a few hours
=> Fixes indexer execution errors

indexer/src/collectors/dune/daily-contract-usage/client.ts
This should be most the opportunities for NaNs. I imagine it's because of dune sometimes doing scientific notation substitutions for numbers. 
Fixes #637
=> Fix number handling for dune

docs/docusaurus.config.ts
* since we don't have versioning or locales yet, it seems to get confused
=> fix: turn off contextualSearch on algolia

dbt/oso_dbt/__init__.py, dbt/pyproject.toml
I put context into the dummy `__init__.py` file. 
This should address issues @ccerv1 and I encountered when using poetry 1.7.x.
=> Fix errors when installing with poetry 1.7+

frontend/.env.local.example, frontend/app/api/artifacts/route.ts, frontend/app/api/projects/route.ts, frontend/components/dataprovider/event-data-provider.tsx, frontend/lib/config.ts, frontend/next.config.js, frontend/package.json, frontend/tsconfig.json, package.json, pnpm-lock.yaml
* Add an environment variable STATIC_EXPORT to control whether to do a static site build from frontend/
* Fix the build to support both modes
* Remove @opensource-observer/indexer from the frontend build (not used)
* Upgrade dependencies in root package.json
=> feat: static builds

frontend/components/dataprovider/auth-router.tsx, frontend/supabase/migrations/20240209235914_hasura_claim.sql
* The auth hook will take the user's id and put it in a custom claim under app_metadata using the fields that Hasura expects.
* Add print debugging on the Supabase session
* This needs to be enabled under the Supabase Auth Hook settings
=> feat: add Supabase migration for a Hasura auth hook

dbt/models/marts/events/events_daily_to_artifact.sql, dbt/models/marts/events/events_monthly_from_artifact.sql, dbt/models/marts/events/events_monthly_to_artifact.sql, dbt/models/marts/events/events_weekly_from_artifact.sql, dbt/models/marts/events/events_weekly_to_artifact.sql, oso/bq2cloudsql/script.py
* Removed `{to/from}_name` from all `events_{duration}ly_{to/from}_artifacts` because the `*_name` field is not guaranteed unique for a namespace. 
* Small bug fixes
=> Uncaught model issues

.github/workflows/warehouse-run-data-pipeline.yml, oso/bq2cloudsql/script.py
Remove the need to do manual configuration. 
Bonus: 
Added a way to skip the cloudquery plugins so we can just run dbt.
=> Automatically sets up all marts to copy with bq2cloudsql

dbt/models/intermediate/contributors/int_devs.sql, dbt/models/intermediate/contributors/int_users.sql, dbt/models/marts/onchain_metrics/onchain_metrics_by_collection.sql, dbt/models/marts/onchain_metrics/onchain_metrics_by_project.sql, dbt/models/marts/repository_metrics/repository_metrics_by_collection.sql, dbt/models/marts/repository_metrics/repository_metrics_by_project.sql, dbt/models/staging/oss-directory/stg_ossd__repositories_by_project.sql
* `github_metrics_*` metrics now renamed to `repository_metrics_*`
* Renamed `network` field in `onchain_*` to `onchain_network` to follow the same format as `repository_source`
* Fixed some linting in various files
Closes #974
=> Rename GitHub metrics

apps/docs/.gitignore, apps/docs/docs/index.mdx, apps/docs/plasmic.lock, apps/docs/src/components/plasmic/Overview.tsx
* Trying to fix a weird behavior on dark mode, everything seems to work locally, but on production, the Plasmic components don't re-render when the dark mode is toggled. Not sure what causes that
* Fixed the import on docs/index.mdx
* Adding plasmic.lock into the version control
=> docs: dark mode fiddling

.github/workflows/ci-default.yml, apps/frontend/.env.local.example, apps/frontend/codegen.ts, apps/frontend/lib/clients/apollo.ts, apps/frontend/lib/config.ts
* We currently use the OSO API in 2 places: (1) to generate types for the GraphQL API via codegen and (2) to make server-side queries to the database.
* Added OSO API keys in various GraphQL initializers so we don't get a broken build if we exhaust the anon rate limit
=> feat: use OSO API keys in our own app

apps/frontend/app/api/auth/route.ts, apps/frontend/app/project/[...slug]/page.tsx, apps/frontend/components/dataprovider/event-data-provider.tsx, apps/frontend/lib/graphql/cached-queries.ts, apps/frontend/lib/graphql/queries.ts
* Reflected in Plasmic v48.0.0, this does the main data queries server-side (cached), and then passes it in as props to the page.
* Adds a bunch of new GraphQL queries that we use for the project page
* Adds a `queryWrapper` to cache new queries easily
* Added some minor logging to the auth route for later
=> feat: wire up the new project page

apps/frontend/components/dataprovider/apollo-wrapper.tsx, apps/frontend/components/dataprovider/event-data-provider.tsx, apps/frontend/lib/clients/supabase.ts, apps/frontend/lib/config.ts
* Create a hook that will replace the HTTP link of the Apollog client to use an authorization token from the Supabase client when we see one
* Update the event-data-provider to call the new hook
* Try to get the Supabase JWT token globally once the Supabase client loads
=> feat: Pass in JWT token to the Apollo client

apps/frontend/components/dataprovider/auth-router.tsx
* This flag will force always showing the children in the auth-router, even if you're not logged in. Useful for always showing the same thing, but you still need access to the Supabase state
=> feat: ignoreNoAuth flag on auth-router

apps/frontend/.env.local.example, apps/frontend/components/dataprovider/auth-router.tsx, apps/frontend/lib/config.ts
* Analytics might fail (e.g. ad-blockers etc). We should just ignore that gracefully via spawn
* The Segment write key needs to be accessible client-side now, previously we were embedding it into the server-side build bundle, but now it's loaded in a client-side component
=> fix: 2 bugs with how Segment was loading on the frontend

apps/docs/package.json, apps/frontend/app/artifact/[namespace]/[type]/[...name]/page.tsx, apps/frontend/app/project/[...slug]/page.tsx, apps/frontend/lib/graphql/queries.ts, apps/frontend/lib/paths.ts, apps/frontend/package.json, pnpm-lock.yaml
* Upgrade Next and Apollo on the frontend
* Added SSG for OSO, which seems to be a requirement now. For static
exports you must have a non-empty list of paths to generate.
* Removing user_namespace from graphql queries. This was inadvertantly
removed, which causes the queries to fail on build. This will need to
be re-added later
* Removed searchParams from project and artifact pages. This was causing
an error with requiring Suspense. We don't use it anymore, can re-add
it later if necessary
=> fix: frontend build

apps/frontend/lib/graphql/queries.ts, apps/hasura/metadata/api_limits.yaml
* There was a broken query: `source` no longer existed on code_metrics, which caused a confusing generic "Apollo database error"
* Updated the Hasura API limits, just because
=> fix: frontend

README.md
Correct the URL to get started docs.
=> Fix missing link in dbt Start

.lintstagedrc, warehouse/cloudquery-oss-directory/src/tables.ts
* Minor, we get the SQL dialect from .sqlfluff now, so we don't need to explicitly flag it
=> fix: cloudquery-oss-directory should import `description`

package.json
* Not sure why this was added. I think it was a yarn thing?
=> fix: remove strict packageManager version in package.json

warehouse/dbt/models/intermediate/blockchain/int_optimism_transactions.sql
This typo was only encountered when running for production with `is_incremental() == True`
=> Fix int_optimism_transactions typo

warehouse/oso_dagster/goldsky.py
Had some issues with this due to checkpoint size loading too many files at once into bigquery. Generally this _won't_ happen but we haven't pulled in data on a regular schedule. This should address that moving forward
=> Fix goldsky checkpoint size

.github/workflows/test-deploy-owners.yml, ops/external-prs/.env.example, ops/external-prs/src/base.ts, ops/external-prs/src/cli.ts, ops/external-prs/src/ossd/index.ts
* Adds an .env.example so folks know how to configure this for local testing
* Reports in an error message what the valid commands are if you specified an invalid one
* Adds a bunch of comments in places
=> fix: external-prs better error messages

warehouse/dbt/models/intermediate/directory/int_artifacts_by_project.sql
* Checks whether the oss-directory network is any_evm, includes if so
* Fix the join to join on both source and namespace
=> feat: add ANY_EVM semantics to deployer crawling

warehouse/dbt/macros/models/contract_invocation_events_with_l1.sql, warehouse/dbt/macros/models/filtered_blockchain_events.sql, warehouse/dbt/models/intermediate/blockchain/int_optimism_contract_invocation_events.sql, warehouse/dbt/models/intermediate/blockchain/int_optimism_transactions.sql, warehouse/dbt/models/intermediate/directory/int_all_artifacts.sql, warehouse/dbt/models/intermediate/directory/int_artifact_types.sql, warehouse/dbt/models/intermediate/directory/int_artifacts.sql, warehouse/dbt/models/intermediate/directory/int_artifacts_by_user.sql, warehouse/dbt/models/intermediate/metrics/int_repo_metrics_by_project.sql, warehouse/dbt/models/marts/directory/artifacts_by_project_v1.sql, warehouse/dbt/models/marts/directory/artifacts_v1.sql, warehouse/dbt/models/marts/superchain/rf4_events_daily_to_project.sql
* Previously, we were DISTINCT on source, namespace, name, AND type.
* This means that the same address was shown multiple times per artifact_type
* This refactor creates an intermediate model called int_all_artifacts that we can use
* artifact_type is removed from artifacts_v1 and artifacts_by_project_v1
* there's a new int_artifact_types table that we can use to get types
=> fix: removes artifact_type from artifacts, moves to a separate table

.env.example, warehouse/bq2cloudsql/README.md, warehouse/bq2cloudsql/cloudsql.py, warehouse/bq2cloudsql/script.py, warehouse/bq2cloudsql/synchronizer.py, warehouse/dbt/models/marts/directory/artifacts_by_project_v1.sql, warehouse/dbt/models/marts/directory/artifacts_v1.sql, warehouse/dbt/models/marts/directory/collections_v1.sql, warehouse/dbt/models/marts/directory/contracts_v1.sql, warehouse/dbt/models/marts/directory/projects_by_collection_v1.sql, warehouse/dbt/models/marts/directory/projects_v1.sql, warehouse/dbt/models/marts/directory/users_v1.sql
* Allows the mart model author to specify which indices to build
* Adds a few indices in `marts/directory`
* Adds a README to bq2cloudsql
* Adds an .env.example in monorepo root
* Adds a utility to read the index config from the mart model and create the indices on copy Note: This will not work on incremental mode in bq2cloudsql
=> feat: build indices for mart models

ops/external-prs/package.json, ops/external-prs/src/ossd/index.ts, pnpm-lock.yaml
* oss-directory now exposes BlockchainTag and BlockchainNetwork
* Use these types to make sure that we are using the correct strings in validation logic
=> feat: refactor external-prs to use oss-directory types

warehouse/bq2cloudsql/cloudsql.py, warehouse/bq2cloudsql/script.py
* For some reason previously index creation would succeed, but still be missing for a non-deterministic set of indices
* This changes the retry logic to preempt retries with checking for success criteria.
* Then we select for indices and retry until we see it in the database
=> feat: retry building indices until we see it in the DB

ops/external-prs/README.md, ops/external-prs/package.json, ops/external-prs/src/base.ts, ops/external-prs/src/ossd/index.ts, ops/external-prs/src/ossd/templating.ts, ops/external-prs/src/ossd/validation-results.ts, pnpm-lock.yaml, warehouse/cloudquery-oss-directory/package.json
* This comes with some pretty major refactoring of how we store ValidationResults
* Move mustache templating code to separate module
* Create a generic class for storing ValidationResults that will be rendered to a GitHub issue comment
* Updates to oss-directory 0.0.15
* Fixes up some minor logging too
=> feat: any_evm addresses warns if you're tagging `contract`

warehouse/oso_dagster/utils/bq.py
I caught this while refreshing some datasets. This ensures the dataset is public
=> bug: Fix dataset permissions

warehouse/dbt/macros/models/combine_op_airdrops.sql, warehouse/dbt/models/staging/optimism/stg_optimism_airdrop_addresses.sql, warehouse/dbt/models/static_data_sources.yml
As per discussed, adding the macro and closing https://github.com/opensource-observer/oso/pull/1637
Got a question related to datatype as the addresses are currently set as float, no matter how i change the source data type or cast to string in query, they continue showing up as numbers
=> Add macro and airdrop addresses to staging

warehouse/oso_dagster/utils/common.py, warehouse/oso_dagster/utils/errors.py
* Add file for custom errors in Dagster
* Add python common utils, ported from TypeScript * Includes, assertNever, ensure, cast
=> feat: python common utils

warehouse/oso_dagster/assets/clickhouse_dbt_marts.py, warehouse/oso_dagster/factories/__init__.py, warehouse/oso_dagster/factories/bq2clickhouse.py, warehouse/oso_dagster/utils/clickhouse.py
* Factory for bq2clickhouse, which exports datasets to GCS in a staging bucket, then import to Clickhouse
* This follows the pattern mostly from bq2cloudsql
* Auto-create assets for every dbt mart
=> feat: Dagster assets for copying marts from BigQuery to Clickhouse

warehouse/oso_dagster/factories/bq2clickhouse.py
* Fix the way we handle gcs bucket names and paths
=> fix: bq2clickhouse

warehouse/oso_dagster/assets/optimism.py
Originally, had some custom code for using optimism transactions with google blocks but realized we are also getting the blocks from goldsky so we're just loading all into the `superchain` data source. 
Closes #1873
=> Ingest all optimism data sources

warehouse/oso_dagster/factories/bq2clickhouse.py
Notices clickhouse was attempting to materialize when things weren't run in dbt. I'm thinking perhaps we have things with the `opensource.observer/type` be:
* `source` - Essentially a raw data source
* `staging` - Staging models
* `intermediate` - Intermediate models
* `mart` - Marts
We can be flexible but this will prevent errors from happening because it's expecting things in dbt.
=> Changing the type tag of the clickhouse assets

.gitignore, ops/helm-charts/oso-dagster/Chart.yaml, ops/helm-charts/oso-dagster/templates/config-map.yaml, poetry.lock, pyproject.toml, warehouse/oso_dagster/cli.py, warehouse/oso_dagster/constants.py, warehouse/oso_dagster/definitions.py, warehouse/oso_dagster/resources/__init__.py, warehouse/oso_dagster/resources/dlt.py, warehouse/oso_dagster/resources/io_manager.py
Need to check a couple things but this _should_ allow for running dagster's dlt assets with a very minimal configuration just:
```
GOOGLE_PROJECT_ID=<get this from oso_lets_go>
DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1
```
=> Allow local only env for dlt development

warehouse/oso_dagster/factories/dlt.py
This is a preliminary bug fix for some DLT factory things. I realize actually we _can't_ do multiple dlt resources from one of these factories so some additional logic needs to be removed but I'd prefer to get #1952 merged in before because that will require some rewriting. This still _works_ it's just not actually semantically correct.
This fixes a bug where the dlt factory errors when running locally because of `jsonl` and duckdb usage.
=> Fix dlt factory

.gitignore, poetry.lock, pyproject.toml, warehouse/clickhouse-mesh/config.yaml, warehouse/clickhouse-mesh/models/incremental_model.sql
This isn't fully working on any remote db but it will work if you have downloaded `int_events` locally.
This also ensure most up-to-date python deps.
=> Add SQLMesh

apps/frontend/app/artifacts/[source]/[...name]/page.tsx, apps/frontend/app/collections/[...name]/page.tsx, apps/frontend/app/projects/[...name]/page.tsx
* If the server-side logic for collections/projects/artifacts pages fail for any reason, redirect to /retry, which will ask the user to retry their request.
* This assumes that all failures are caused by Clickhouse idling and a simple retry will fix it.
=> fix: Add a retry page

warehouse/oso_dagster/assets/filecoin.py
Hey there! 
This should replicate Filecoin Lily tables to the proper region (https://github.com/opensource-observer/oso/issues/1989).
=> feat: replicate Filecoin data

ops/k8s-apps/base/cloudsql-proxy/proxy.yaml, ops/k8s-apps/base/dagster/dagster.yaml
Also uses spot instances again due to some memory constraints.
=> Redeploy with small scale up to unblock dagster

apps/frontend/app/artifacts/[source]/[...name]/error.tsx, apps/frontend/app/artifacts/[source]/[...name]/page.tsx, apps/frontend/app/collections/[...name]/error.tsx, apps/frontend/app/collections/[...name]/page.tsx, apps/frontend/app/projects/[...name]/error.tsx, apps/frontend/app/projects/[...name]/page.tsx
* Following the guide here https://nextjs.org/docs/app/building-your-application/routing/error-handling
* Recommended not to use try/catch
* By default, just redirect to /retry for now.
* In the future we should switch on different types of errors
=> feat: Error page for Collection/Project/Artifact pages

warehouse/oso_dagster/assets/dbt.py
This is because sometimes dbt assets get changed and then it becomes difficult to run the dbt assets from the UI.
=> Makes dbt asset jobs

warehouse/metrics_mesh/config.py, warehouse/metrics_mesh/lib/factories/factory.py, warehouse/metrics_mesh/macros/oso_id.py, warehouse/metrics_mesh/macros/source.py, warehouse/metrics_mesh/models/events_daily_to_artifact.sql, warehouse/metrics_mesh/models/metrics_factories.py, warehouse/metrics_mesh/models/metrics_v0.sql, warehouse/metrics_mesh/models/timeseries_metrics_by_artifact_v0.sql, warehouse/metrics_mesh/sources/clickhouse.sources.yml, warehouse/metrics_mesh/sources/local.sources.yml
Also had to change some things for sqlmesh because our old `source.py` file doesn't work in a sqlmesh world. We basically shouldn't be loading external files into any macros. I likely could solve it some other way but I think we should transition to using something more idiomatic in sqlmesh which is around `external_models`. For now this works and should continue to work but it's a bit of a punt for that issue.
Closes #2091
=> Migrated metrics_v0 and timeseries_metrics_by_artifact_v0 to sqlmesh

.env.example, warehouse/metrics_mesh/README.md, warehouse/metrics_mesh/lib/local/utils.py, warehouse/oso_lets_go/cli.py
* We should load the GCP project ID from .env
* Adds a README for how to get started with sqlmesh
=> fix: get sqlmesh started without a default project ID

warehouse/dbt/models/marts/events/daily/events_daily_to_artifact.sql, warehouse/dbt/models/marts/events/daily/events_daily_to_collection.sql, warehouse/dbt/models/marts/events/daily/events_daily_to_project.sql, warehouse/dbt/models/marts/events/monthly/events_monthly_to_artifact.sql, warehouse/dbt/models/marts/events/monthly/events_monthly_to_collection.sql, warehouse/dbt/models/marts/events/monthly/events_monthly_to_project.sql, warehouse/dbt/models/marts/events/weekly/events_weekly_to_artifact.sql, warehouse/dbt/models/marts/events/weekly/events_weekly_to_collection.sql, warehouse/dbt/models/marts/events/weekly/events_weekly_to_project.sql
* We are migrating to the sqlmesh metrics pipeline. yay!
=> fix: stop copying event aggregation tables to Clickhouse

warehouse/dbt/models/filecoin_sources.yml
Added some of the most useful tables to the dbt sources files from `https://lilium.sh/`.
Note that not all tables that Starboard is publishing are updated se we can use this to expose the ones that are maintained and used.
Closes https://github.com/opensource-observer/oso/issues/1989
=> Add filecoin dbt sources

apps/frontend/app/artifacts/[source]/[...name]/page.tsx, apps/frontend/components/dataprovider/metrics-data-provider.tsx
* For the ArtifactPage, I'm trying to keep this as generic as possible, so now you can pass in which key metrics to show directly, as well as which metric IDs to show in the time series chart.
* This gives ultimate flexibility to pass in different values depending on whether this is a repo, or package, or contract etc.
=> feat: ArtifactPage props updated

warehouse/oso_dagster/definitions.py, warehouse/oso_dagster/factories/common.py, warehouse/oso_dagster/factories/dlt.py, warehouse/oso_dagster/schedules.py
This PR closes #2119 and unblocks the merging of #2110 by enhancing the [`dlt_factory`](https://github.com/opensource-observer/oso/blob/4202708b428fc6ce7867d68b5d8a6f3cfaf7b1ee/warehouse/oso_dagster/factories/dlt.py#L121) decorator by automatically creating daily schedules for assets with `partition_def`. The key features include:
1. **Daily Schedule & Weekly Job**: It sets up a daily schedule for the asset and a job that materializes weekly on Sunday. Partitions that are already materialized are skipped.
2. **Custom Tagging**: The `dlt_factory` decorator now adds a custom tag (`opensource.observer/extra -> partitioned-assets`) to Dagster assets to indicate they are partitioned.
3. **Job Creation**: An internal job is created using the provided partition and is included in the …
=> feat: automatically create `schedules` to materialise `partitioned` assets dynamically

poetry.lock, pyproject.toml, warehouse/oso_dagster/definitions.py, warehouse/oso_dagster/factories/alerts.py, warehouse/oso_dagster/utils/alerts.py
This PR introduces a new `AlertManager`: `CanvasDiscordWebhookAlertManager`. This new alert manager functions similarly to `DiscordWebhookAlertManager`, with the key difference being that it generates a summary of the failed step using Pillow on the fly.
=> feat: display failed step details in `canvas` on discord

warehouse/oso_dagster/factories/goldsky/assets.py, warehouse/oso_dagster/factories/goldsky/network.py, warehouse/oso_dagster/utils/bq.py
=> Allow coercible schema changes

warehouse/oso_dagster/factories/dlt.py
This PR adds the `dagster/concurrency_key` to all partitioned assets created via the `dlt_factory` decorator. This tag will be used to limit concurrency to `1` for those assets to avoid race-conditions for the time being.
=> add: `dagster/concurrency_key` to partitioned assets

.sqlfluff, poetry.lock, pyproject.toml, warehouse/metrics_mesh/config.py, warehouse/metrics_mesh/macros/time_aggregation_bucket.py, warehouse/metrics_mesh/macros/to_unix_timestamp.py, warehouse/metrics_mesh/models/events_daily_to_artifact.sql, warehouse/metrics_tools/lib/factories/factory.py
This was part of #2109 but was part of my discovery that sqlmesh would take a _very_ long time not just hours but actually days. This improves that a bit by using some new sqlmesh code combined with some changes i'd like to make upstream to them and an update to our configuration. I want to merge this as it _works_ but it's not exactly perfect. I don't, however, want things to drift too far. 
I'll be experimenting with using clickhouse materialized views from here on
=> Various sqlmesh and clickhouse updates for concurrency

warehouse/metrics_mesh/config.py, warehouse/metrics_tools/lib/factories/definition.py
Fixes issues with the metrics ids not getting into `metrics_v0`
=> Metrics fixes for metrics_v0

warehouse/oso_dagster/assets/eas_optimism.py, warehouse/oso_dagster/assets/open_collective.py, warehouse/oso_dagster/utils/common.py
This PR updates failed queries to use Dagster's retry mechanism instead of failing silently, adjusts the data fetching to reduce nodes to 500 per query—since the Open Collective API returns 503 errors for larger queries—which seems sensible based on local testing and will require further triage, and changes the write disposition to "merge" to prevent duplicates in the dataset.
=> fix: use dagster `retry` mechanism

apps/hasura3/oso_subgraph/metadata/oso_clickhouse-types.hml, apps/hasura3/package.json
* When running ddn codegen to upgrade to latest schemas, I think it introduced a bug where _in arguments look for a string, instead of a string array. This manually forces it back in an attempted fix
=> fix: Hasura CLI created incorrect argument schemas

apps/frontend/components/dataprovider/metrics-data-provider.tsx, apps/frontend/lib/graphql/queries.ts
* Copying logic from the metrics provider for artifacts
=> feat: MetricsDataProvider supports projects and collections

apps/frontend/app/artifacts/[source]/[...name]/page.tsx, apps/frontend/components/dataprovider/metrics-data-provider.tsx
* Bug in CollectionMetricsDataProvider that was getting by projectId instead of collectionId
* Instead of filling missing dates with 0, use null, and then leverage Tremor's ability to connect nulls for smooth graphs
=> fix: various chart fixes

warehouse/oso_dagster/assets/eas_optimism.py, warehouse/oso_dagster/assets/open_collective.py
Fixes #2300 by removing `end_date` parameter to partitions. TLDR; `end_date` was computed once when Dagster was deployed, making it miss future partitions.
=> fix: remove `end_date` parameter

warehouse/oso_dagster/assets/eas_optimism.py, warehouse/oso_dagster/assets/open_collective.py
This PR closes #2295 by enabling partitioned jobs to materialize an additional range. Specifically, for a weekly partition, it includes the current partial week, allowing the asset to materialize the available data for the current week without waiting for the full week to complete.
=> fix: allow `assets` to materialize the current week on demand

warehouse/oso_dagster/assets/clickhouse_dbt_marts.py
This PR fixes #2335 by updating the `clickhouse_dbt_mart` k8s config, which used the old one. I have also checked all the other `dagster-k8s/config` uses, which are following the new format, so we should be fine!
=> fix: use updated `k8s` config

warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
The pipeline fails with a `401 Unauthorized` error when attempting to fetch repository data using `githubkit`. After investigating, it appears the issue stems from the Pydantic validation for the full repository model. Specifically, `githubkit`'s full repository model expects a `datetime` field, whereas we were using `Optional[datetime]` due to the signature in the `MinimalRepository` for API version `2022-11-28`. This caused the validation to fail. There is a comment in the library explaining this design choice:
https://github.com/yanyongyu/githubkit/blob/1857d5e711fa400df74782775b53fa3ffe5acef8/githubkit/typing.py#L81-L83
This is a potential fix and requires further testing to confirm that the validation issue is indeed the root cause.
=> fix: `ossd` failing pipeline

warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
This PR reverts the changes made to the `created_at` and `updated_at` fields. If this does not resolve the issue, the failing pipeline error may be related to authentication. However, if the issue is resolved, it indicates a mismatch with the API version model.
=> revert: github `repository` model properties

warehouse/dbt/models/intermediate/blockchain_events/int_base_traces.sql, warehouse/dbt/models/marts/superchain/4337_traces.sql, warehouse/oso_dagster/assets/base.py
Closes #2269 by storing the `amount` field as `bytes` on the oso raw sources, and casting it back in direct downstream dependencies. This results in precession loss for really big numbers. As discussed, we'll follow this approach for the moment.
=> fix: float `overflow` for base traces

warehouse/metrics_mesh/models/metrics_factories.py, warehouse/metrics_tools/lib/factories/definition.py, warehouse/metrics_tools/lib/factories/factory.py, warehouse/metrics_tools/lib/factories/macros.py
Closes #2377 
This addresses issues with metric duplicates which ended up being that some metrics shouldn't be rolled up as a mart and are only intermediate. Additionally we need to have metric_ids take the event source into account.
=> Fixes appearance of metric duplicates

warehouse/metrics_tools/dialect/translate.py, warehouse/metrics_tools/lib/factories/definition.py, warehouse/metrics_tools/lib/factories/factory.py, warehouse/metrics_tools/lib/local/utils.py
Found this randomly testing fixes to the metrics. Need to fix this before we start going crazy with the rolling metrics.
=> Addresses issues with generated models being overly eager to refresh

warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
We should change this once #2415 gets done. Changed it to log instead of throw in order to not lose hours of progress.
=> fix: `log` failed sbom request instead of throw

warehouse/oso_dagster/assets/ossd.py
This PR closes #2404 by adding the `dagster/concurrency_key` tag to all `ossd` assets.
=> fix: add `dagster/concurrency_key` to `ossd` assets

warehouse/dbt/models/oss_directory_source.yml, warehouse/dbt/models/staging/oss-directory/stg_ossd__missing_sbom.sql, warehouse/oso_dagster/assets/ossd.py, warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
=> fix: `sbom` performance improvements

ops/tf-modules/warehouse-cluster/main.tf
n2 with greater than 20 CPUs can't be used here sadly. It forces 4,8, or 16 ssds which costs way too much.
=> sqlmesh manual load ops fix

warehouse/dbt/models/intermediate/events/int_events_aux_issues.sql, warehouse/dbt/models/marts/events/timeseries_events_aux_issues_by_artifact_v0.sql
Still needs to be deployed but this is the auxiliary events table that we will use to join issues together. 
Ideally, we'd have an `event_id`, but we don't currently have that so we will need to join on quite a few columns when doing the join in sqlmesh. I think changing the event table to add the event_id for right now would be too large a change as many things depend on the current schema (I considered it though).
=> Auxiliary events table for issues

pyproject.toml, scripts/dbt_doc_gen/dataset_context/arbitrum_one.json, scripts/dbt_doc_gen/dataset_context/farcaster.json, scripts/dbt_doc_gen/dataset_context/filecoin.json, scripts/dbt_doc_gen/dataset_context/gitcoin.json, scripts/dbt_doc_gen/dataset_context/githubarchive.json, scripts/dbt_doc_gen/dataset_context/lens.json, scripts/dbt_doc_gen/dataset_context/open_collective.json, scripts/dbt_doc_gen/dataset_context/openrank.json, scripts/dbt_doc_gen/dataset_context/oso_playground.json, scripts/dbt_doc_gen/dataset_context/oso_production.json, scripts/dbt_doc_gen/dataset_context/oso_projects.json, scripts/dbt_doc_gen/dataset_context/superchain.json, scripts/dbt_doc_gen/generate_dbt_docs.py
llm led data dictionary generation for dbt models
=> feat: llm led data dictionary generation for dbt models

warehouse/dbt/models/intermediate/directory/int_artifact_ownership.sql, warehouse/dbt/models/staging/npm/stg_npm__manifests.sql, warehouse/oso_dagster/assets/npm.py
The npm `manifest` fields previously had multiple formats, causing `dlt` to create multiple tables and cluttering the schema with inconsistent columns. This PR addresses the issue by flattening the `manifest` to establish a consistent structure. Additionally, it updates the downstream dbt models to align with the new schema.
=> fix: flatten `npm` manifest structure

warehouse/dbt/macros/models/parse_npm_git_url.sql
This PR addresses edge cases found when extracting information from `npm` Git URLs to ensure consistency.
- Git URLs that include a `#revision` at the end.  
- Git URLs containing `/blob/...` or `/tree/...` instead of the absolute URL.  
- Git URLs that omit the `.git` suffix.  
These cases have been handled to standardize URL processing across the board.
=> fix: update `parse_npm_git_url` macro for improved URL parsing

warehouse/dbt/models/intermediate/events/int_events__dependencies.sql
This PR closes #2521 by only tracking events for dependencies present in `artifacts_v1`.
=> fix: filter intermediate dependency events by `artifacts_v1`

warehouse/dbt/macros/models/parse_npm_git_url.sql
This PR modifies the `parse_npm_git_url` macro to follow a more structured approach when cleaning up and extracting heterogeneous `npm` git URLs.
=> fix: npm `git` url parsing cleanup logic

warehouse/dbt/macros/models/parse_npm_git_url.sql
This PR fixes yet another edge case on the URL parsing. URLs should be correct now!
=> fix: build `remote_url` from source items

warehouse/dbt/models/marts/events/timeseries_events_aux_issues_by_artifact_v0.sql
Adds the comments column (apologies I missed this)
=> Fix timeseries_events_aux_issues_by_artifact_v0.sql to include `comments` column

warehouse/metrics_mesh/models/metrics_factories.py, warehouse/metrics_mesh/oso_metrics/funding_received.sql
This PR closes #2286 by creating a time series model for the funding received over the last `180` days.
> [!NOTE]
> Data is incomplete since it's playground data, so the plot may not be 100% accurate.
We can create visualizations such as the following:
=> add: timeseries `funding_received` sqlmesh model

warehouse/metrics_mesh/models/metrics_factories.py, warehouse/metrics_mesh/oso_metrics/dependencies.sql
This PR closes #2287 by creating a time series model for the funding received over the last 180 days.
> [!NOTE]
> Data is incomplete since it's playground data, so the plot may not be 100% accurate.
We can create visualizations such as the following:
=> add: timeseries `dependencies` sqlmesh model

warehouse/oso_dagster/assets/crates.py, warehouse/oso_dagster/factories/archive2bq.py
This PR adds a new asset factory, `archive2bq`. This factory fetches an archive, uncompresses it, filters out the files we need, uploads them to GCS, creates the BigQuery tables with the data from GCS and deletes the GCS data when it is no longer needed.
With this asset, it is trivial to replicate _any other_ data source such as `crates`, that provides a tarball with their data. Just add a ~10 line config and done!
```py
crates_data = create_archive2bq_asset(
Archive2BqAssetConfig(
key_prefix="rust",
asset_name="crates",
source_url="https://static.crates.io/db-dump.tar.gz",
source_format=SourceFormat.CSV,
filter_fn=lambda file: file.endswith(".csv"),
staging_bucket=staging_bucket,
dataset_id="crates",
deps=[],
)
)
```
=> feat: replicate `crates` data on bigquery

warehouse/dbt/models/intermediate/funding/int_gitcoin_funding_events.sql, warehouse/dbt/models/marts/gitcoin/gitcoin_funding_events_by_project_v0.sql, warehouse/oso_dagster/assets/gitcoin.py
- **fix: remove rounds dagster asset**
- **fix: round naming**
=> fix(dbt): gitcoin round namings

warehouse/dbt/models/deps_dev_sources.yml, warehouse/dbt/models/intermediate/directory/int_artifacts_in_deps_dev_by_project.sql, warehouse/dbt/models/intermediate/directory/int_packages.sql, warehouse/dbt/models/intermediate/directory/int_sbom_artifacts.sql, warehouse/dbt/models/marts/directory/package_owners_v0.sql, warehouse/dbt/models/marts/directory/sboms_v0.sql, warehouse/dbt/models/staging/deps-dev/stg_deps_dev__packages.sql
- **fix(dbt): point to better source for latest package owner in deps.dev**
- **feat(dbt): staging model for latest package owner**
- **feat(dbt): int model to see if we have a package's owner repo already**
- **fix(dbt): add model to resolve deps.dev and sbom source names**
- **feat(dbt): parse package lineage and determine if historic owner is current owner**
- **fix(dbt): refactor to use int_packages**
- **fix(dbt): use int_packages to join on sbom package sources**
=> feat(dbt): mart registry for dependency graph

.github/scripts/publish-docker-containers.sh, docker/images/oso-debug/Dockerfile, docker/images/oso-debug/build.sh, ops/clusters/warehouse/flux-system/gotk-sync.yaml, ops/helm-charts/metrics-calculation-service/values.yaml, ops/k8s-apps/base/trino/trino.yaml, ops/k8s-apps/production/trino/custom-helm-values.yaml, ops/tf-modules/warehouse-cluster/main.tf, warehouse/metrics_mesh/config.py, warehouse/metrics_mesh/macros/oso_id.py, warehouse/metrics_mesh/macros/oso_source.py, warehouse/metrics_mesh/models/artifacts_by_project_v1.sql, warehouse/metrics_mesh/models/code/issue_event_time_deltas.sql, warehouse/metrics_mesh/models/events_daily_to_artifact.sql, warehouse/metrics_mesh/models/first_of_event_from_artifact.sql, warehouse/metrics_mesh/models/last_of_event_from_artifact.sql, warehouse/metrics_mesh/models/metrics_v0.sql, warehouse/metrics_mesh/models/projects_by_collection_v1.sql, warehouse/metrics_mesh/models/timeseries_metrics_by_artifact_v0.sql, warehouse/metrics_mesh/models/timeseries_metrics_by_collection_v0.sql, warehouse/metrics_mesh/models/timeseries_metrics_by_project_v0.sql, warehouse/metrics_tools/compute/cluster.py, warehouse/metrics_tools/compute/constants.py, warehouse/metrics_tools/definition.py, warehouse/metrics_tools/factory/factory.py, warehouse/metrics_tools/factory/test_factory.py, warehouse/metrics_tools/joiner/__init__.py, warehouse/metrics_tools/joiner/fixtures/basic/expected_project.sql, warehouse/metrics_tools/utils/fixtures/gen_data.py
This connects bigquery to trino and also makes a few fixes that were required when running sqlmesh against trino
=> Connect Trino to Bigquery

warehouse/metrics_mesh/models/metrics_factories.py, warehouse/metrics_tools/compute/manual_testing_utils.py, warehouse/metrics_tools/compute/test_app.py, warehouse/metrics_tools/compute/test_service.py, warehouse/metrics_tools/definition.py, warehouse/metrics_tools/runner.py
We may need to change how this is configured in the future but this seemed to make the most sense. 
Part of #2652
=> Use the cron to determine materialization interval

warehouse/metrics_tools/compute/service.py
* Fixed an issue where cancelling early will still result in creation of the trino table. It's not a _bad_ thing just inefficient. The table isn't merged into the final sqlmesh result. This fixes that.
=> More MCS Bugs

warehouse/metrics_tools/factory/factory.py
Took a while to debug some of the issues on the sqlmesh deployment on dagster. I will need to come up with something here to get around this but this will work for now. I think what we may want to do is keep a directory of "versions" for each of the proxies.
=> Add legacy models (noop) to support deployment

warehouse/oso_dagster/assets/sqlmesh.py, warehouse/oso_dagster/definitions.py, warehouse/oso_dagster/resources/__init__.py, warehouse/oso_dagster/resources/clickhouse.py, warehouse/oso_dagster/resources/kube.py, warehouse/oso_dagster/resources/mcs.py, warehouse/oso_dagster/resources/trino.py, warehouse/oso_dagster/utils/asynctools.py, warehouse/oso_dagster/utils/http.py, warehouse/oso_dagster/utils/test_asynctools.py
Part of #2479 
Did some refactoring because we actually need to share some resources like trino among a couple different assets. Technically if two things shared the trino resource at once this would actually cause a problem but we should solve that at a later time with something like resource reservations using some kind of kubernetes operator that tracks resource reservations for given deployments (this way we can keep costs low by only turning on these services when necessary).
=> Refactor trino and mcs into dagster resources 

warehouse/oso_dagster/definitions.py, warehouse/oso_dagster/resources/trino.py
We were previously using the root of the server but that was never actually a known good endpoint. I got this from here: https://github.com/trinodb/trino/issues/14663
=> Use the correct trino health check endpoint

warehouse/oso_dagster/resources/trino.py
Frustratingly, the dagster objects for resources have no type checking for their attributes so I missed this purely out of missing it from a previous refactor. This is hopefully it but the only way to test is on production at the moment.
=> Fix trino resource

ops/k8s-apps/base/dagster/dagster.yaml
@Jabolol I think this should resolve the issue for logging. If the docs are correct for the dagster helm chart this will mean our internal modules are now being logged.
=> Adds metrics_tools and oso_dagster loggers to dagster logs on the UI

warehouse/metrics_mesh/macros/to_unix_timestamp.py
One of the main reasons we need a local trino. Turns out some things we're assuming would work are not working. This should _in theory_ fix the issue with this macro. It doesn't yet fix one of the other issues on the python model for openrank. Looking at that next.
=> Fix the unix timestamp macro for trino

warehouse/metrics_mesh/macros/to_unix_timestamp.py, warehouse/metrics_mesh/models/metrics_factories.py, warehouse/metrics_mesh/oso_metrics/key_active_address_count.sql, warehouse/metrics_mesh/oso_metrics/key_active_contract_count.sql, warehouse/metrics_mesh/oso_metrics/key_active_developer_count.sql, warehouse/metrics_mesh/oso_metrics/key_comment_count.sql, warehouse/metrics_mesh/oso_metrics/key_developer_active_day_count.sql, warehouse/metrics_mesh/oso_metrics/key_first_commit.sql, warehouse/metrics_mesh/oso_metrics/key_last_commit.sql, warehouse/metrics_tools/factory/factory.py, warehouse/metrics_tools/factory/proxy/proxies.py
@Jabolol I made some changes I was almost certain we had discussed for the original PR and I must have completely forgot to follow up on, but you can take a look at the examples here. I removed some of the use of `metrics_entity_type_col` and just use `events.to_artifact_id` and now I can use some of the automagic. 
That being said, we still definitely need some of local trino runner cause these things are hard to catch. I'll write up an issue for it.
=> More key metrics fixes

warehouse/metrics_mesh/models/staging/defi_llama/defi_llama.py, warehouse/metrics_tools/local/utils.py, warehouse/oso_dagster/assets/defillama.py
Also:
* Updates the utils.py bq_to_duckdb so that it won't download data if the table already exists
=> Connect all configured defi_llama protocols

warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
This PR adds progress logging to the `ossd` SBOMs asset. It is a really large asset (~120000 repositories), so having progress helps with time estimation.
=> fix: add `sbom` progress logging

ops/k8s-apps/base/nessie/kustomization.yaml, ops/k8s-apps/base/nessie/nessie.yaml, ops/k8s-apps/local/kustomization.yaml, ops/k8s-apps/local/nessie/custom-helm-values.yaml, ops/k8s-apps/local/nessie/kustomization.yaml, ops/k8s-apps/local/nessie/secrets.yaml, ops/k8s-apps/local/trino/custom-helm-values.yaml, warehouse/metrics_mesh/README.md, warehouse/metrics_mesh/macros/json_array_length.py, warehouse/metrics_mesh/macros/json_extract.py, warehouse/metrics_mesh/models/intermediate/directory/int_artifacts_in_ossd_by_project.sql, warehouse/metrics_mesh/models/intermediate/directory/int_projects.sql, warehouse/metrics_tools/local/loader.py, warehouse/metrics_tools/local/utils.py, warehouse/oso_lets_go/cli.py
Lots of things:
* Adds iceberg to the local trino deployment (turns out because of how sqlmesh works this was necessary)
* Uses nessie as the metastore (ended up not being so hard to do)
* Adds a `json_extract` macro that can be used in multiple places
* Adds a `json_array_length` because `array_length` doesn't exist on trino (or sqlglot transpiles to the wrong thing).
=> Fix some sqlmesh models on trino

warehouse/oso_lets_go/cli.py
* We were using the wrong path for the derivation
=> fix: derive trino path from duckdb path

warehouse/oso_dagster/assets/op_atlas.py, warehouse/oso_dagster/factories/sql.py
* Current user that we have has strict connection limits
* This PR will add a concurrency key to all assets that connect to op-atlas
* Also turns on defer_table_reflect to reduce the number of connections
=> fix: op-atlas replication

warehouse/metrics_tools/local/loader.py
* Previously we force casted all structs into JSON, seemed like a shortcut at the time, but hurts performance and made it inconsistent with BigQuery and Trino
* This PR will recursively convert nested structs into the correct type in DuckDB when loading data.
=> fix: DuckDB struct support

warehouse/metrics_mesh/models/staging/github/stg_github__pull_request_merge_events.sql
This PR closes #2934 by using `BIGINT` instead of `INT` so the casting does not fail.
=> fix: change pull request id type from `INT` to `BIGINT`

ops/k8s-apps/production/trino/custom-helm-values.yaml, warehouse/metrics_mesh/models/events_daily_to_artifact_with_lag.sql, warehouse/metrics_mesh/models/intermediate/events/int_events__github.sql, warehouse/metrics_mesh/models/intermediate/events/int_events_aux_issues.sql, warehouse/metrics_mesh/models/intermediate/openrank/int_openrank_developer.py, warehouse/metrics_mesh/models/marts/events/timeseries_events_aux_issues_by_artifact_v0.sql, warehouse/metrics_mesh/models/marts/events/timeseries_events_by_artifact_v0.sql, warehouse/metrics_mesh/models/staging/defillama/stg_defillama.py, warehouse/metrics_mesh/models/staging/github/stg_github__comments.sql, warehouse/metrics_mesh/models/staging/github/stg_github__issues.sql, warehouse/metrics_mesh/models/staging/github/stg_github__pull_request_merge_events.sql, warehouse/metrics_mesh/models/staging/github/stg_github__pull_requests.sql, warehouse/metrics_mesh/models/staging/superchain/stg_superchain__factories.sql, warehouse/metrics_mesh/models/staging/superchain/stg_superchain__traces.sql, warehouse/metrics_mesh/models/staging/superchain/stg_superchain__transactions.sql, warehouse/oso_lets_go/cli.py
Ran into these while running production
Fixes:
* Some models were incorrectly trying to cast very large numbers to INT32. We need INT64
* We had some partitions that didn't specify any bucketing. We need to always use `DAY({time_column})` or `MONTH({time_column})` when using `INCREMENTAL_BY_TIME_RANGE` otherwise trino will attempt to use a very fine granularity for partitioning which will cause it to error.
=> SQLMesh Production Fixes

.github/workflows/check-duckdb-schema.yml, .github/workflows/ci-default.yml, poetry.lock, pyproject.toml, warehouse/metrics_tools/local/loader.py
Closes https://github.com/opensource-observer/oso/issues/2090
=> feat: add sqlmesh plan step for CI

warehouse/metrics_tools/transfer/bq.py, warehouse/metrics_tools/transfer/duckdb.py, warehouse/oso_dagster/definitions.py, warehouse/oso_dagster/resources/bq.py, warehouse/oso_dagster/resources/duckdb.py, warehouse/oso_dagster/resources/sqlmesh.py
This PR closes #2576 by implementing two new sqlmesh `exporter`s: `Trino2BigQuerySQLMeshExporter` and `DuckDB2BigQuerySQLMeshExporter`. The latter comes in handy in case we have our data in a DuckDB provider such as MotherDuck and we decide to do a backup to BigQuery.
> [!WARNING]
> The `DuckDB` -> `BigQuery` export is disabled since we don't have a useful use case yet. As Ray said, it's never bad to have another data transfer tool :)
In order to use the new `Trino` -> `BigQuery` exporter, materialize the assets below `bigquery_metrics`. Each asset corresponds to one model.
=> add: `new` sqlmesh exporters

warehouse/metrics_tools/transfer/duckdb.py, warehouse/oso_dagster/definitions.py, warehouse/oso_dagster/resources/duckdb.py, warehouse/oso_dagster/resources/sqlmesh.py
This PR closes #2347 by implementing the `Trino` -> `DuckDB` SQLMesh exporter. It is not exposed yet in the configuration, since we do not use `MotherDuck`, but it is as easy as:
1. Authenticate with MotherDuck, e.g. [via an `auth_token`](https://motherduck.com/docs/getting-started/connect-query-from-python/installation-authentication/#using-an-access-token), and add a new `env` variable, e.g. `MOTHERDUCK_CONN_URI`
2. Add the following `config` to the existing `sqlmesh_exporter` variable in `warehouse/oso_dagster/definitions.py`
```diff
sqlmesh_exporter = [
Trino2ClickhouseSQLMeshExporter(
["clickhouse_metrics"],
destination_catalog="clickhouse",
destination_schema="default",
source_catalog="metrics",
source_schema="metrics",
),
Trino2BigQuerySQLMeshExporter(
["bigquery_metrics"], …
```
=> add: `Trino` -> `DuckDB` SQLMesh exporter

warehouse/metrics_mesh/macros/onchain/factory_deployments.py
I guess the one problem with sqlglot is some logic is harder to visualize. This should have been an `!=` not an `=` when i translated it 🤦
=> hotfix: factory deployments bug

warehouse/metrics_tools/transfer/bq.py, warehouse/oso_dagster/resources/sqlmesh.py
This PR modifies the functionality of the SQLMesh BigQuery importer to allow for multiple files in a GCS folder.
It was designed to only allow the absolute bucket path to one file, which has been updated to resolve all `parquet` files and import them.
=> fix: SQLMesh `BigQuery` multiple file import

warehouse/oso_dagster/definitions.py, warehouse/oso_dagster/factories/alerts.py, warehouse/oso_dagster/utils/alerts.py
Closes https://github.com/opensource-observer/oso/issues/2599
=> feat: add freshness alert sensor and job for assets to dagster

apps/hasura-clickhouse/oso_subgraph/connector/oso_clickhouse/configuration.json, apps/hasura-clickhouse/oso_subgraph/metadata/KeyMetricsByArtifactV0.hml, apps/hasura-clickhouse/oso_subgraph/metadata/KeyMetricsByCollectionV0.hml, apps/hasura-clickhouse/oso_subgraph/metadata/KeyMetricsByProjectV0.hml, apps/hasura-clickhouse/oso_subgraph/metadata/oso_clickhouse.hml
* Latest sqlmesh models removed the column.
* This is just the API refresh to reflect that change
=> fix: remove `metric` from KeyMetricsBy* models in API

warehouse/oso_dagster/factories/archive2bq.py
This PR sets the write disposition for the `archive2bq` factory as `write_truncate` to avoid saving data which we don't need. Should take effect on the next run for the dependent assets.
=> fix: use `write_truncate` for `archive2bq` factory

warehouse/metrics_mesh/models/intermediate/metrics/int_key_metric_names_from_artifact.sql, warehouse/metrics_mesh/models/intermediate/metrics/int_key_metric_names_from_collection.sql, warehouse/metrics_mesh/models/intermediate/metrics/int_key_metric_names_from_project.sql, warehouse/metrics_mesh/models/marts/metrics/metrics_v0.sql
This PR closes #3052 by adding the missing metrics to `metrics_v0`. Populating description/display_name etc is being tracked on #3055.
=> add: expose `key_metrics` in `metrics_v0`

warehouse/oso_dagster/utils/http.py
This PR fixes the fact that the `async` transport was configured to use the `sync` resources, probably a typo! It caused assets requiring `async` transports to fail.
```
TypeError: Expected subclass of `AsyncBaseStorage` but got `RedisStorage`
File "/usr/local/lib/python3.12/dist-packages/dlt/extract/utils.py", line 212, in run
item = await gen.__anext__()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/app/warehouse/oso_dagster/utils/dlt.py", line 97, in _wrapper
await future for future in asyncio.as_completed(group_coroutines)
^^^^^^^^^^^^
File "/usr/lib/python3.12/asyncio/tasks.py", line 631, in _wait_for_one
return f.result()  # May raise f.exception().
^^^^^^^^^^
File "/usr/src/app/warehouse/oso_dagster/dlt_sources/github_repos/__init__.py", line 288, in get_sbom_for_repo
sbom = await …
```
=> fix: use `async` config instead of `sync` resources

warehouse/oso_dagster/utils/dlt.py
githubkit yields `None` values for the coroutines (sboms that fail), we need to filter these out since we cannot `await` None values.
=> fix: filter out `none` coroutines

warehouse/metrics_mesh/models/marts/metrics/key_metrics_by_artifact_v0.sql, warehouse/metrics_mesh/models/marts/metrics/key_metrics_by_collection_v0.sql, warehouse/metrics_mesh/models/marts/metrics/key_metrics_by_project_v0.sql, warehouse/metrics_mesh/models/marts/metrics/timeseries_metrics_by_artifact_v0.sql, warehouse/metrics_mesh/models/marts/metrics/timeseries_metrics_by_collection_v0.sql, warehouse/metrics_mesh/models/marts/metrics/timeseries_metrics_by_project_v0.sql
This should improve DX (speed and costs) when tinkering with these tables as an user, specially on the `artifact` level.
I didn't include `cluster_by` in the PR as that might affect random queries' performance. I think this is something that could be added once query patterns are clear!
=> Add partitioning to metrics timeseries tables

warehouse/oso_dagster/dlt_sources/github_repos/__init__.py, warehouse/oso_dagster/utils/dlt.py
This PR makes providing `_chunk_resource_update` and `_chunk_retrieve_failed` less verbose and hides them when using `dlt_parallelize`, so that the consumer doesn't have to declare them in the function signature. It also adds comments and examples to the `process_chunked_resource` function, with explanations of the current tweaks.
=> fix: hide internal `process` functions for `dlt_parallelize`

warehouse/metrics_mesh/models/intermediate/directory/int_artifacts_by_user.sql, warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_onchain_user_labels.sql, warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_s7_onchain_metrics_by_project.sql, warehouse/metrics_mesh/models/intermediate/users/int_first_time_addresses.sql, warehouse/metrics_mesh/models/intermediate/users/int_superchain_potential_bots.sql, warehouse/metrics_mesh/models/marts/directory/artifacts_by_user_v1.sql, warehouse/metrics_mesh/models/staging/superchain/stg_superchain__first_time_addresses.sql, warehouse/metrics_mesh/models/staging/superchain/stg_superchain__potential_bots.sql
This PR disables `first_time_addresses`, `potential_bots` staging SQLMesh models and all downstream models of those
=> chore: disable sqlmesh `first_time_addresses`, `potential_bots`

ops/helm-charts/oso-dagster/Chart.yaml
This PR closes #3096 by upgrading the Dagster version in the Helm chart.
=> chore: upgrade dagster daemon `helm` chart version

ops/helm-charts/oso-dagster/Chart.lock
This PR updates the Helm chart lock file to the new specific new version.
=> chore: update helm `chart` lock file

warehouse/metrics_tools/factory/proxy/proxies.py
Previously we filtered metadata table names in a hardcoded manner, making an assumption about the source catalog name. This caused production to fail. This PR addresses that problem by computing the metadata table name dynamically. Closes #3114
=> fix: filter metadata table names `correctly`

warehouse/metrics_mesh/models/marts/metrics/metrics_v0.sql, warehouse/metrics_tools/factory/factory.py, warehouse/metrics_tools/factory/proxy/proxies.py
This PR updates the way in which we generate metadata to make it more performant. Instead of creating one table for each rendered query (`timeseries`/`rolling`/`key metrics` etc.), we generate one intermediate metadata table per metric factory definition (e.g. stars, commits which will _later_ expand downstream to `timeseries`/`rolling`/`key metrics` stars, commits etc.). These are joined downstream on `metrics_v0` joining on `%` + `metric` + `%`, since metrics are in the form of `event_source` + `metric` + `suffix`.
This will **finally** allow us to set metadata in the metric factory which the frontend will consume easily, for a better UX. Related to #3117.
=> fix: trino metadata `performance` issues

ops/k8s-apps/production/dagster/custom-helm-values.yaml, warehouse/oso_dagster/assets/clickhouse_dbt_marts.py, warehouse/oso_dagster/assets/eas_optimism.py, warehouse/oso_dagster/assets/open_collective.py, warehouse/oso_dagster/factories/alerts.py, warehouse/oso_dagster/factories/goldsky/assets.py
Removed CPU limits for dagster pods.
Changed memory limit/requests for the alerts jobs because it was constantly failing with `OOMKilled`. Might need to investigate why it started happening, by guess it is related to the changes in the dagster definitions.
=> Chore: remove CPU limits for dagster pods and change memory limit/requests

apps/docs/docs/integrate/datasets/index.mdx, warehouse/metrics_tools/local/utils.py, warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__4337_traces.sql, warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__4337_userop_logs.sql
@ravenac95 this PR includes the following changes:
- increments the sources in utils.py to v2
- updates the source in the logs staging model
- updates the source in the enriched traces model AND implements [Kofi's logic](https://github.com/Jam516/superchain-4337/blob/main/models/userops/superchain_4337_userops.sql)
The key thing to review for dialect compatibility is this field. Kofi had it as:
```
case WHEN input != '0x' THEN 0
else SAFE.PARSE_NUMERIC('0x' || SUBSTRING(userop_calldata, 75, 64))/1e18 
end as value
```
and my implementation is:
```
CAST(
CASE WHEN input != '0x' 
THEN 0 
ELSE CAST(CONCAT('0x', SUBSTRING(userop_calldata, 75, 64)) AS DECIMAL(38,0)) / CAST(1e18 AS DECIMAL(38,18))
END AS DECIMAL(38,18)
) AS value
```
=> fix: use updated 4337 source models

warehouse/oso_dagster/assets/defillama.py
The defillama `tvl` op got OOM killed on kubernetes. This PR adds some extra resources for it to run successfully.
=> fix: improve defillama op `k8s` resources

warehouse/oso_dagster/assets/ossd.py, warehouse/oso_dagster/dlt_sources/github_repos/__init__.py, warehouse/oso_dagster/utils/http.py
This PR closes #3085, closes #3124 by rewriting the `ossd` resources in an `async` way. They now used `process_chunked_resource` to maintain state on `GCS` and are parallelized thanks to `@dlt_parallelize`, allowing us to configure limits on their execution rate and cooldown. The HTTP cache has been removed as well, since it is no longer needed.
It also adds support for a new tag, `max-sbom-age-days`. When this tag is set (defaults to `7` days), it will only fetch SBOMs who are either older than `7` days or not present yet in SBOMs (for those new repositories added).
=> fix: use `dlt_parallelize` for `ossd` resources

warehouse/oso_dagster/assets/ossd.py, warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
This PR makes long-lasting `ossd` jobs (`SBOMs`, `repositories`) use `spot` instances to save up on costs, since they use `@dlt_parallelize` + `process_chunked_resource` to keep state on `GCS`, making them resistant to random pod outages.
It also adds logging at every `5%` for these jobs, and hides redundant longs (e.g. "fetching SBOM ..."), in favor of these progress updates.
=> feat: make `ossd` jobs run on `spot` instances

pyproject.toml, uv.lock, warehouse/oso_dagster/assets/ossd.py
This PR closes part 1 of #3209 by using `pandas` under the hood to address the missing columns in `ossd` projects.
=> fix: use `pandas` and `polars` to address missing columns

warehouse/oso_dagster/assets/eas_optimism.py, warehouse/oso_dagster/assets/open_collective.py
OpenCollective and EAS jobs have been getting `OOMKilled` errors. This PR addresses this by giving them a higher limit.
=> add: increase `k8s` resources limits

warehouse/oso_dagster/assets/ossd.py, warehouse/oso_dagster/definitions.py, warehouse/oso_dagster/utils/dlt.py
This PR closes #3352 by splitting the `process_chunked_resource` steps into two separate processes. Now, the main process acts as a wrapper that handles error recovery and state management in GCS. The new addition is a sensor that automatically deletes outdated files from previous runs after a **48-hour grace period** to keep storage clean.  
It also adds a custom retry policy for `ossd` assets, since spot instances need more retries than the default limit of **3**.  
On top of that, there are some performance improvements like replacing `to_string_fn` with `to_serializable_fn`, which removes an extra layer of indirection, reduces storage usage, and speeds things up.
=> feat: improve dlt `chunked` resource robustness

apps/frontend/components/widgets/algolia.tsx
AlgoliaSearchList
* Previously we wouldn't have a key for the repeated item, which leads to a React warning
=> fix: set a key when enumerating default search results in

warehouse/oso_dagster/assets/defillama.py
This PR fixes the `defillama/tvl` asset which had an incorrect name (thanks for pointing it out Carl!).
=> fix: use correct `defillama` tvl dataset name

warehouse/metrics_tools/local/utils.py
* We are indexing the universe already in sqlmesh/Trino, so no need to pull this data from dbt
=> fix: remove github and blockchain events from `oso initialize`

warehouse/docker/trino/seed/sqlmesh.sql, warehouse/metrics_tools/factory/constants.py, warehouse/metrics_tools/factory/factory.py, warehouse/metrics_tools/factory/proxy/proxies.py, warehouse/metrics_tools/local/utils.py, warehouse/oso_dagster/assets/sqlmesh_render.py, warehouse/oso_sqlmesh/models/marts/metrics/metrics_v0.sql, warehouse/oso_sqlmesh/models/marts/sqlmesh/models_v0.sql, warehouse/oso_sqlmesh/models/marts/sqlmesh/rendered_models.sql, warehouse/oso_sqlmesh/models/staging/sqlmesh/stg_sqlmesh__rendered_models.sql
This PR closes #3078 by introducing two new columns: `rendered_sql` and `sql_source_path` for the `metrics_factories` assets.
The former is an array of the pretty-printed rendered `sql` queries. Each `MetricQueryDef`'s `time_aggregations`/`rolling`/`entity_types`/... adds a rendered query to this array. The idea is to have a page for e.g. `stars`, which has all grouped queries and some plots and metrics.
The latter is the path to the `sql` model source relative to the `SQLMesh` project root. This will be useful to link to GitHub itself.
It also introduces a new dagster asset, `sqlmesh/rendered_models` which exports all rendered models, and a SQLMesh staging model for these models and a mart so we can consume them via Clickhouse.
=> feat: `oso` web model `reference` tables

apps/frontend/app/models/[...name]/error.tsx, apps/frontend/app/models/[...name]/page.tsx, apps/frontend/app/models/page.tsx, apps/frontend/lib/clickhouse/cached-queries.ts, apps/frontend/lib/clickhouse/queries.ts
* Adds a /models/[...name] route that just shows the rendered SQL of a model
* Enables querying anything from `models_v0`
* Also added support for the Algolia index to serve any model
=> feat: ModelPage route

warehouse/metrics_tools/definition.py, warehouse/metrics_tools/factory/constants.py, warehouse/metrics_tools/factory/factory.py, warehouse/metrics_tools/factory/proxy/proxies.py, warehouse/metrics_tools/intermediate.py, warehouse/metrics_tools/macros/macros.py, warehouse/metrics_tools/runner.py, warehouse/metrics_tools/transformer/transformer.py, warehouse/metrics_tools/utils/glot.py, warehouse/oso_lets_go/cli.py, warehouse/oso_sqlmesh/config.py, warehouse/oso_sqlmesh/models/intermediate/events/int_events_aux_issues.sql, warehouse/oso_sqlmesh/models/metrics_factories.py, warehouse/oso_sqlmesh/models/staging/github/stg_github__comments.sql, warehouse/oso_sqlmesh/models/staging/github/stg_github__issues.sql, warehouse/oso_sqlmesh/models/staging/github/stg_github__pull_request_merge_events.sql, warehouse/oso_sqlmesh/models/staging/github/stg_github__pull_requests.sql, warehouse/oso_sqlmesh/oso_metrics/code/change_in_developers.sql, warehouse/oso_sqlmesh/oso_metrics/code/contributor_activity_classification.sql, warehouse/oso_sqlmesh/oso_metrics/code/developer_activity_classification.sql, warehouse/oso_sqlmesh/oso_metrics/code/lifecycle.sql, warehouse/oso_sqlmesh/oso_metrics/code/prs_time_to_merge.sql, warehouse/oso_sqlmesh/oso_metrics/code/time_to_first_response.sql, warehouse/oso_sqlmesh/tests/test_developer_active_days_over_window.yml, warehouse/oso_sqlmesh/tests/test_developer_classification_over_window.yml
Replaces the rolling windows with larger time buckets. Some things to note, we should not display the last of a given time bucket because it won't be completed. I tried a way to prevent it calculating unnecessarily but unfortunately that seems to bug out on tests. I think it's best to just skip any "unfinished" results that might appear when we render on the frontend.
=> fix!: replace rolling windows

warehouse/oso_sqlmesh/models/intermediate/events/int_events__dependencies.sql, warehouse/oso_sqlmesh/models/intermediate/events/int_events_daily__dependencies.sql, warehouse/oso_sqlmesh/models/marts/events/event_types_v1.sql, warehouse/oso_sqlmesh/models/metrics_factories.py, warehouse/oso_sqlmesh/models/staging/github/stg_github__distinct_commits_resolved_mergebot.sql, warehouse/oso_sqlmesh/models/staging/github/stg_github__releases.sql, warehouse/oso_sqlmesh/models/staging/github/stg_github__stars_and_forks.sql, warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__4337_userop_logs.sql, warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__deployers.sql, warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__factories.sql, warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__proxies.sql, warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__traces.sql, warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__transactions.sql
This ensures that we don't unnecessarily restate things in the next production run. Also this disables dependencies for now.
=> revert some staging models to "duckdb"

ops/k8s-apps/base/redis/redis.yaml, ops/k8s-apps/production/dagster/custom-helm-values.yaml, ops/k8s-infrastructure/gke/gcp-secrets-store-plugin/gcp-secrets-store-plugin.yaml, warehouse/oso_dagster/utils/dlt.py
Trying to do some cost reduction. The run launcher spins up a bunch of pods just to monitor steps. I'm wondering if we can do better here.
=> chore: reduce run launcher request sizes

warehouse/oso_sqlmesh/audits/has_at_least_n_rows.sql, warehouse/oso_sqlmesh/models/marts/directory/artifacts_by_collection_v1.sql
* Follows the sqlmesh generic audit pattern for counting rows and reporting if it falls below a threshold
=> feat: add row count audit

warehouse/oso_dagster/config.py, warehouse/oso_dagster/definitions.py
* Trino exporters - renaming prefix from `metrics` to `export`
* The Trino2Bigquery exporter should go to the `oso` dataset
=> Fix: rename where export goes

warehouse/metrics_tools/compute/types.py
Without this, array(varchar) would become [varchar] instead of Array(varchar), from trino to clickhouse
=> fix(exporter): specify that ColumnsDefinition need to parse into a type, and not a constant

apps/frontend/app/api/v1/graphql/route.ts, apps/frontend/app/api/v1/sql/route.ts, apps/frontend/components/widgets/supabase-write.tsx, apps/frontend/jest.config.js, apps/frontend/lib/auth/auth.ts, apps/frontend/lib/clients/posthog.ts, apps/frontend/lib/parsing.test.ts, apps/frontend/lib/parsing.ts, apps/frontend/lib/types/posthog.ts, apps/frontend/package.json, apps/frontend/tsconfig.json, pnpm-lock.yaml
* Identifies `api_call` events by user
* Also tags the api key name in case we need that label
* Introduces SQL and GraphQL parsing to get the table/model names from the query
* Adds those names as metadata to the event
=> feat: track API calls by user and models

apps/frontend/components/dataprovider/apollo-wrapper.tsx, apps/frontend/components/dataprovider/metrics-data-provider.tsx, apps/frontend/components/widgets/apollo-sandbox.tsx, apps/frontend/lib/auth/auth.ts, apps/frontend/lib/clients/supabase.ts
* Cleanup tech debt. Removing the hacky global variable `userToken`
* Replace with getting the token in a `useAsync` where needed
* Populate the token in the Apollo explorer
=> fix: remove ensureAuth()

ops/helm-charts/generic/Chart.yaml, ops/helm-charts/generic/lint-only-values.yaml, ops/helm-charts/generic/templates/_helpers.tpl, ops/helm-charts/generic/templates/app.yaml, ops/helm-charts/generic/templates/service-account.yaml, ops/helm-charts/generic/templates/service.yaml, ops/helm-charts/generic/values.yaml
Adds a generic app chart to deploy things. I really didn't want to make this as a helm chart but we don't have a good alternative yet that would work with flux.
=> feat: adds generic app chart

.github/workflows/post-production-sync.yml, .github/workflows/warehouse-publish-docker-containers.yml
This is a bit better than our previous delete and pray setup with our docker publishing actions. As a push to production means that there's a new docker container, this is a better place to but deployment hooks.
=> chore: sets up a post production sync action

ops/k8s-apps/production/consumer-trino/catalog-store-config.yaml, ops/k8s-apps/production/consumer-trino/custom-helm-values.yaml, ops/k8s-apps/production/consumer-trino/kustomization.yaml, ops/k8s-apps/production/consumer-trino/trino-catalog-volume.yaml
Still need to test this setup on kubernetes, but it worked on docker.
Spent a lot of time trying to make `catalog.config-dir` work because it is badly documented. Had to do a small workaround for now since it's not supported by default on their helmchart, by manually creating a ConfigMap and mounting the `catalog-store.properties` file. Also did tweaked the initContainers to copy the static catalogs into the dynamic catalogs folder, so we can have "both"
Commented on a closed issue from their repo here https://github.com/trinodb/charts/issues/332 to document the usage of `catalog.config-dir`.
Draft until tested.
=> feat(consumer-trino): make consumer trino accept dynamic connectors and create admin role

apps/frontend/components/dataprovider/oso-data-provider.tsx, apps/frontend/components/dataprovider/oso-global-context.tsx, apps/frontend/lib/types/plasmic.ts, apps/frontend/plasmic-init-client.tsx
* Previous approach wasn't working
* This makes it cleaner, where write actions are exposed globally, but read data context is local
* Also exposes config as a global context
=> feat: separate OsoAppProvider into OsoDataProvider and OsoGlobalContext

apps/frontend/app/layout.tsx, apps/frontend/components/dataprovider/apollo-wrapper.tsx, apps/frontend/components/dataprovider/auth-router.tsx, apps/frontend/components/dataprovider/metrics-data-provider.tsx, apps/frontend/components/dataprovider/oso-data-provider.tsx, apps/frontend/components/dataprovider/oso-global-context.tsx, apps/frontend/components/dataprovider/supabase-query.tsx, apps/frontend/components/hooks/oso-app.ts, apps/frontend/components/hooks/supabase.tsx, apps/frontend/components/widgets/apollo-sandbox.tsx, apps/frontend/components/widgets/auth-actions.tsx, apps/frontend/components/widgets/auth-form.tsx, apps/frontend/components/widgets/oso-chat.tsx, apps/frontend/components/widgets/supabase-write.tsx, apps/frontend/lib/clients/oso-app.ts, apps/frontend/lib/clients/supabase.ts
* Previously, we had really hacky ways to store the Supabase client in global variables
* This properly fixes this up to store the client and session data in a Context Provider
* Also supports manually revalidating the Supabase session on log in/out
* Update all components to just read session/user data from the context, rather than spamming Supabase
=> fix: Supabase global variables tech debt

ops/k8s-apps/base/trino/trino.yaml
Just discovered that trino has a graceful shutdown for workers. This hopefully makes scaling up/down less disruptive for sqlmesh. Enabling it.
=> chore: add trino graceful shutdown

warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/github/int_github_repositories.sql, warehouse/oso_sqlmesh/models/intermediate/entities/users/github/int_github_users.sql, warehouse/oso_sqlmesh/models/intermediate/events/github/first-last/int_first_last_commit_from_github_user.sql, warehouse/oso_sqlmesh/models/intermediate/events/github/first-last/int_first_last_commit_to_github_repository.sql, warehouse/oso_sqlmesh/models/intermediate/events/github/int_events_weekly__github.sql
The Type 2 models continue to create issues; at this point probably easiest just to do standard full materializations and we can optimize at some point in the future.
=> fix(sqlmesh): change github history model type to full

ops/k8s-apps/base/agent/agent.yaml, pyproject.toml, uv.lock, warehouse/metrics_tools/semantic/definition.py, warehouse/metrics_tools/semantic/testing.py, warehouse/oso_agent/oso_agent/agent/__init__.py, warehouse/oso_agent/oso_agent/agent/agent_registry.py, warehouse/oso_agent/oso_agent/agent/base.py, warehouse/oso_agent/oso_agent/agent/basic_agent.py, warehouse/oso_agent/oso_agent/agent/decorator.py, warehouse/oso_agent/oso_agent/agent/default.py, warehouse/oso_agent/oso_agent/agent/react_agent.py, warehouse/oso_agent/oso_agent/agent/semantic_agent.py, warehouse/oso_agent/oso_agent/agent/sql_agent.py, warehouse/oso_agent/oso_agent/cli/commands.py, warehouse/oso_agent/oso_agent/eval/experiment_registry.py, warehouse/oso_agent/oso_agent/eval/text2sql.py, warehouse/oso_agent/oso_agent/server/app.py, warehouse/oso_agent/oso_agent/server/bot.py, warehouse/oso_agent/oso_agent/types/__init__.py, warehouse/oso_agent/oso_agent/types/agent.py, warehouse/oso_agent/oso_agent/types/response.py, warehouse/oso_agent/oso_agent/types/sql_query.py, warehouse/oso_agent/oso_agent/util/config.py, warehouse/oso_agent/pyproject.toml
TODOs:
Implementation Notes:
* Added a new `WrappedResponse` type
* This is used as the common response object from the agents. Currently the response types are:
* `StrResponse` - The default
* `SqlResponse` - A SQL Response (using the `SqlQuery` type)
* `SemanticResponse` - A semantic query response
* `ErrorResponse` - If an error is detected we wrap all errors in this type
* This is done so that any experiment should be able to target any agent and handle their respective responses through pattern matching in a `match...case` stanza. 
* Makes the agent loading lazy (for server startup this is by default forced into eager mode)
Closes #3863
=> feat: start wiring the semantic agent

warehouse/metrics_tools/semantic/definition.py, warehouse/metrics_tools/semantic/test_definition.py, warehouse/metrics_tools/semantic/testing.py
Mostly cosmetic. This matches us more closely to cube but also disambiguates descriptions to any LLM between OSO metrics and the semantic measures.
=> feat: rename semantic metrics to measures

ops/k8s-apps/production/dagster/custom-helm-values.yaml
I couldn't quite tell if this was related to the `failed to start` issues but I know I was a bit too conservative with these values before. I also didn't do much investigation yet, as it's not fully disruptive, just a nuissance. If this doesn't help we should just increase the start timeout on the helm chart at `dagsterDaemon.runMonitoring.startTimeoutSeconds` which is currently set to 300 seconds (or decrease to improve responsiveness?)
=> chore: bump size for dagster pods

uv.lock, warehouse/pyoso/pyoso/client.py, warehouse/pyoso/pyproject.toml
Stupid bug I ran into yesterday when the agent started generating queries with semicolons and the error returned was confusing. This will prevent that from happening to users of the pyoso library but doesn't necessarily make the errors any better on the server. Though the error _directly_ from the api does say that `;` is not expected. I'm not sure we fix this on the server though, most people should be using pyoso so I'm fine only changing it here for now. 
On the server, the limitation appears to be the trino client which doesn't accept the semicolons at the end of the query. Instead of not accepting it, we accept it here but also ensure that you've only included a _single_ query.
=> fix: include better errors when ending queries with semicolons in pyoso

apps/frontend/components/dataprovider/oso-data-provider.tsx
* If we use variableName (which I commonly do), SWR will cache things improperly, re-using the variable name.
* This PR separates the caching key and the Plasmic key
=> fix: caching bug in OsoDataProvider

warehouse/oso_dagster/assets/ossd.py, warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
Closes #4170 and also removes the unused `sbom_relationships` asset, since it had data we didnt need.
=> Add `graphql` support to GitHub `dlt` connector

apps/frontend/components/dataprovider/auth-router.tsx, apps/frontend/components/dataprovider/oso-chat-provider.tsx, apps/frontend/components/dataprovider/oso-data-provider.tsx, apps/frontend/components/dataprovider/provider-view.tsx, apps/frontend/components/dataprovider/supabase-query.tsx
* These are studio only props that allow us to render those children for design purposes
* Also changes the behavior of useTestData so that we automatically replace the data in the common DataProviderView, rather than expect the consumer to pass in the right thing
=> fix: add forceError and forceLoading into DataProviderView

apps/frontend/app/api/v1/chat/route.ts, apps/frontend/app/api/v1/graphql/route.ts, apps/frontend/app/api/v1/sql/route.ts
This PR closes #4209 and fixes #4207 by adding back tracking, without enforcing org belonging
=> fix: relax `credit` enforcement checks

warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/packages/int_packages__current_maintainer_only.sql, warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/packages/int_sbom__latest_snapshot.sql, warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/packages/int_sbom__snapshots.sql, warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/packages/int_sbom_artifacts.sql, warehouse/oso_sqlmesh/models/staging/oss-directory/stg_ossd__current_sbom.sql
This pull request introduces new intermediate models and refactors how Software Bill of Materials (SBOM) snapshots and package maintainer data are processed within the SQLMesh data warehouse, specifically under the `warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/packages/` directory. The main changes include:
1. **New Models Added:**
- **`int_packages__current_maintainer_only.sql`**  
- Extracts current maintainers from `oso.int_packages` into a dedicated view for easier and consistent downstream usage.
- **`int_sbom__snapshots.sql`**  
- Creates a partitioned, full model representing SBOMs linked to package owner GitHub repos, joining current maintainer info.
- **`int_sbom__latest_snapshot.sql`**  
- Provides a view of the most recent SBOM snapshot for each dependent …
=> refactor(sqlmesh): update SBOM models to incremental and maintain snapshot dates

warehouse/oso_lets_go/cli.py, warehouse/oso_sqlmesh/README.md
If the user want to debug on trino UI locally, the user would fail if using the following commands:
``` bash
cd warehouse
docker compose up --wait
oso local sqlmesh-test plan dev --start '1 week' --end now
```
This is because the sqlmesh-test will shutdown the docker containers by default as last step; however, this would be confusing to users who followed the readme and tried to debug (and frustrating since it took loooong to run, but all the logs are gone after the run)
Add a flag `--keep-containers` and default value=false so wont affect the actions pipeline.
=> feat(cli): add option to keep Docker containers running after sqlmesh test

uv.lock
When merging PR's from dependabot, since we use uv, we need to run `uv sync` to update the `uv.lock` file. This will change when dependabot supports more uv features (e.g: https://github.com/dependabot/dependabot-core/issues/12072)
=> chore: run uv sync

apps/docs/docs/index.mdx, apps/docs/docusaurus.config.ts, apps/docs/plasmic.lock, apps/docs/src/components/plasmic/Overview.tsx, apps/docs/src/components/plasmic/generated/docs_opensource_observer/PlasmicCard.tsx, apps/docs/src/components/plasmic/generated/docs_opensource_observer/PlasmicLinkCard.module.css, apps/docs/src/components/plasmic/generated/docs_opensource_observer/PlasmicLinkCard.tsx, apps/docs/src/components/plasmic/generated/docs_opensource_observer/PlasmicOverview.module.css, apps/docs/src/components/plasmic/generated/docs_opensource_observer/PlasmicOverview.tsx, apps/docs/src/pages/index.mdx
* Previously Docusaurus lazy-loading of CSS caused reordering and weird behavior.
* This will make the CSS conventions closer to what the Kariba docs do, making it more resistent to re-ordering
* Also fixes to use PlasmicRootProvider
=> fix: make Plasmic components resistent to CSS re-ordering

warehouse/oso_sqlmesh/models/staging/github/stg_github__releases.sql
Small fix to make this in sync with my debugging changes that I had manually run on sqlmesh.
=> fix: make stg_github__releases use a larger batch_size

warehouse/oso_dagster/assets/crypto_ecosystems.py, warehouse/oso_dagster/factories/archive2bq.py
This PR adds a dagster asset replicating the data from [`crypto-ecosystems.xyz`](https://crypto-ecosystems.xyz/#).
It uses an interesting toolchain with zig and data embedded in the WebAssembly, so we've had to jump through some hoops, like creating our own mirror at [`opensource-observer/crypto-ecosystems/`](http://github.com/opensource-observer/crypto-ecosystems/).
=> feat: add `crypto_ecosystems` dasgter asset

lib/oso-core/oso_core/logging/__init__.py, lib/oso-core/oso_core/logging/decorators.py, warehouse/metrics-service/metrics_service/test_app.py, warehouse/metrics-service/metrics_service/worker.py, warehouse/metrics_tools/factory/factory.py, warehouse/metrics_tools/utils/gcs.py, warehouse/oso_dagster/assets/sqlmesh_export.py, warehouse/oso_dagster/definitions.py, warehouse/oso_lets_go/cli.py
First part of #4519 
Keeping this one very simple. It moves some of the logging utilities to a new place and also adds a timing function for the `load_definitions` dagster function. 
I'm making a larger PR after this that instruments all of the assets but for now I wanted to make this a small PR and try to get this in first.
=> Instrument timing in logs for dagster `load_definitions` 

pyproject.toml, uv.lock, warehouse/oso_dagster/definitions/resources.py, warehouse/oso_dagster/resources/io_manager.py
This fixes an issue we ran into with ossd.projects not materializing with the correct schema. Updated packages must have caused this, but an error pointed me to the fact that the bq lib needs `pandas-gbq` to work properly because the dataframe goes polars -> pandas -> BQ insert job.
=> fix(oso_dagster): hotfix polars io manager with bq

warehouse/oso_agent/oso_agent/workflows/default.py, warehouse/oso_agent/oso_agent/workflows/text2sql/basic.py, warehouse/oso_agent/oso_agent/workflows/text2sql/mixins.py, warehouse/oso_agent/oso_agent/workflows/types.py
This PR closes #4412 and refactors the `QueryEngineTool` from an opaque tool abstraction into explicit workflow steps. The changes replace the single `QueryEngineTool` call with a multi-step workflow that breaks down SQL generation into three distinct phases: schema analysis to identify relevant tables, row context retrieval using embedding-based similarity search, and SQL generation using LLM with enriched context.
The new `OsoQueryEngineWorkflowMixin` exposes these previously hidden steps as workflow events (`StartQueryEngineEvent`, `SchemaAnalysisEvent`, `RowContextEvent`), making the entire SQL generation process transparent and inspectable for evaluation purposes. This refactoring enables better debugging, more granular testing of individual steps, and the ability to reuse specific …
=> feat: add `OsoQueryEngineWorkflowMixin` with schema analysis and context retrieval steps

apps/docs/docs/tutorials/quickstart.md
This PR introduces the initial scaffolding for adding **semantic layer query tabs** to each tutorial. This is part of the effort to improve semantic layer reference documentation as discussed in [#4448](https://github.com/opensource-observer/oso/issues/4448).
- Added semantic layer tab UI elements to tutorials
- Wrote semantic layer equivalent for all query in [quickstart](https://docs.opensource.observer/docs/tutorials/quickstart) (yet to be tested)
- Laid structural foundation to support tab switching and content rendering
- Finalize semantic query examples for each tutorial
- Adjust styles and layout if needed based on design feedback
- Refactor the semantic layer getting started (0 to 1)
- Create reference documentation on the current entities that are registered with the semantic …
=> feat(tutorials/semantic-layer): add semantic layer tab scaffolding to tutorials

ops/helm-charts/generic/Chart.yaml, ops/helm-charts/generic/templates/app.yaml, ops/helm-charts/generic/values.yaml, ops/helm-charts/oso-dagster/Chart.yaml, ops/helm-charts/oso-dagster/templates/config-map.yaml, ops/helm-charts/oso-dagster/values.yaml, ops/k8s-apps/production/dagster/custom-helm-values.yaml
These are some settings we need to set to get the best load times, I had previously left the sql eager loading on but now we can turn it off. Additionally this fixes an issue with json logs no longer being the default. So we make that the case for deployments now.
=> fix: improve dagster load times

warehouse/oso_sqlmesh/models/intermediate/entities/projects/int_artifacts_by_project_all_sources.sql, warehouse/oso_sqlmesh/models/intermediate/entities/projects/int_projects.sql
This PR adds three new project data sources (crypto ecosystems, DeFiLlama, and OpenLabels Initiative) to the `int_artifacts_by_project` and `int_project` models, enabling metric derivation for a a much larger set of projects. 
Note: each of these project sources only has one type of artifact associated with it (eg, DefiLlama is only DefiLlama protocol slugs).
Tagging @ravenac95 for review because we probably need some macros to assist with this kind of work in the future, and would love his thoughts on how best to approach this. See also: https://github.com/opensource-observer/oso/issues/4797
=> feat(sqlmesh): add new artifacts_by_project models so we can derive metrics

warehouse/metrics_tools/seed/schemas/openlabelsinitiative/labels_decoded.py, warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/blockchain/addresses/int_addresses__openlabelsinitiative.sql, warehouse/oso_sqlmesh/models/intermediate/entities/collections/int_collections.sql, warehouse/oso_sqlmesh/models/intermediate/entities/collections/int_projects_by_collection.sql
This is the final step in having metrics for categories of projects, eg, TVL of all lending protocols and gas generated by all trading bots.
=> feat(sqlmesh): collections for defillama and OLI-defined project categories

.env.example, apps/docs/docs/contribute-data/setup/index.md, pyproject.toml, uv.lock, warehouse/oso_dagster/assets/sqlmesh/sqlmesh.py
Closes #4757 
Adds:
* Some new docs
* Makes restatements go directly to production as opposed to use the dev environment
* Uses `dagster-sqlmesh` 0.20.0
TODO:
=> fix: sqlmesh materializations

uv.lock, warehouse/pyoso/pyoso/__init__.py, warehouse/pyoso/pyoso/analytics.py, warehouse/pyoso/pyoso/client.py, warehouse/pyoso/pyoso/semantic.py, warehouse/pyoso/pyproject.toml
`Type | None` is not supported in python < 3.10
=> chore(pyoso) bump package version

warehouse/oso_dagster/factories/alerts.py
Noticed that the failure sensor was not triggering
=> fix: alert sensor should monitor all code locations

apps/frontend/supabase/migrations/20250826192155_create_dynamic_replication_config.sql, warehouse/oso_dagster/assets/dynamic/rest_api.py, warehouse/oso_dagster/definitions/dynamic.py, warehouse/oso_dagster/definitions/resources.py, warehouse/oso_dagster/factories/dlt.py, warehouse/oso_dagster/resources/__init__.py, warehouse/oso_dagster/resources/postgres.py, warehouse/oso_dagster/utils/__init__.py, warehouse/oso_dagster/utils/dynamic.py
One thing that I really dislike about the current implementation is that it has a lot of integrations that are hard to track, specially when making changes, e.g: the replication data in the database needs to be in a specific format for the asset to work correctly, the sensor and the asset being coupled because the partition key is an important part of the asset.
Another thing to think about is how to expose all the available configuration inside the dlt rest api resource in the frontend. We could always have an advanced mode where the user enters JSON, but how can we make the experience good for less technical users or users that do not want to read the dlt docs?
This closes OSO-856
=> Dynamic replication assets

.github/workflows/deploy-marimo-wasm.yml
Changed redirect from `302` to `307` to prevent browsers from converting POST requests to GET when following the redirect. The `marimo` AI completion endpoint requires POST, but 302 redirects cause browsers to change the method, resulting in `405` Method Not Allowed errors.
`307` preserves the original HTTP method and request body during redirects.
=> fix: redirect status code to preserve `POST` method for marimo API calls

apps/frontend/app/api/v1/marimo/ai/completion/route.ts
The AI completion endpoint only reads auth tokens from the Authorization header, which gets stripped by browsers during Cloudflare's 307 redirect from `marimo.opensource.observer` to `opensource.observer/api/v1/`. I modified the endpoint to check for `osoApiKey` in the request body (which survives redirects).
=> add: extract `osoApiKey` from body to avoid cross-origin header strip

apps/docs/docs/tutorials/project-deepdive.mdx
This PR introduces the initial scaffolding for adding **semantic layer query tabs** to each tutorial. This is part of the effort to improve semantic layer reference documentation as discussed in [#4448](https://github.com/opensource-observer/oso/issues/4448).
- Added semantic layer tab UI elements to tutorials
- Wrote semantic layer equivalent for all query in [Deep Dive into a Project](https://docs.opensource.observer/docs/tutorials/project-deepdive)
- Laid structural foundation to support tab switching and content rendering
- Finalize semantic query examples for other tutorials.
- Adjust styles and layout if needed based on design feedback
- Refactor the semantic layer getting started (0 to 1)
- Create reference documentation on the current entities that are registered with the semantic …
=> feat(tutorials/semantic-layer): add semantic layer tab scaffolding to tutorial 3

apps/frontend/lib/services/credits.ts, apps/frontend/lib/types/schema-types.ts, apps/frontend/lib/types/schema.ts, apps/frontend/lib/types/supabase.ts, apps/frontend/supabase/migrations/20250918230503_create_pricing_plans.sql
> [!NOTE]
> Migration is already done and live on prod, subsequent PRs need the schema changes on this PR to land or CI will fail
This PR closes #5089 by creating a new table `pricing_plan` with different plans (free, enterprise). It also wires the credit service to use these plans to deduct credits, etc.
=> feat: create dynamic `pricing` plans

apps/frontend/.env.local.example, apps/frontend/app/api/v1/invitations/create/route.ts, apps/frontend/components/dataprovider/oso-global-context.tsx, apps/frontend/lib/clients/oso-app/oso-app.ts, apps/frontend/lib/config.ts, apps/frontend/lib/services/email.ts, apps/frontend/lib/types/schema-types.ts, apps/frontend/lib/types/schema.ts, apps/frontend/lib/types/supabase.ts, apps/frontend/package.json, apps/frontend/supabase/migrations/20250919000000_create_invitations_table.sql, pnpm-lock.yaml
This PR is related to #5058 and allows users to join an organization via an invite link.
> [!WARNING]
> Currently, users must be already logged in on their account to accept the invite. We want to allow users to accept invitations even when they don't have an account, WIP.
~~New env vars that need to be added to vercel:~~ Added!
```sh
MJ_API_KEY=
MJ_SECRET_KEY=
MJ_FROM_EMAIL=no-reply@opensource.observer
```
=> feat: setup `email` invite flow

.github/workflows/deploy-marimo-wasm.yml
The wasm build does not have the correct allow list for domains
=> hotfix: fix wasm build to allow new domains

apps/frontend/components/widgets/auth-actions.tsx
Closes: #5262
We can then change the configuration on plasmic to use the the current domain. Supabase auth handles ensuring that the auth uses a valid redirect, so we should be ok to do this on the frontend.
=> feat(frontend): allow dynamically setting post login redirect

apps/frontend/lib/types/schema.ts, apps/frontend/lib/types/supabase.ts, apps/frontend/supabase/migrations/20251003175104_fix_notebooks_rls.sql
> [!NOTE]
> Migration is not yet on prod, pending review
This PR:
- Fixes notebook RLS policies by splitting the generic "Org members and permitted users can access notebooks" policy into granular policies and checking the returned `role` to instead of only `hasAccess` (part of #5248)
- Removes unused `accessed_at` columns and indexes from notebooks and organizations tables (closes #5151)
- Adds priority column to `pricing_plan` table for traffic routing by importance (1 for ENTERPRISE, 100 for FREE tier) (closes #5150)
=> fix: notebook permissions `rls` policies and `misc`

.github/workflows/deploy-marimo-wasm.yml
NOTE: We need to simultaneously update plasmic to use `marimo.oso.xyz` for the notebook host. If we do not, the generative AI features will be broken until we do (due to the 307 redirect). Unfortunately, this is a limitation of cloudflare that we cannot overcome without our own deployment.
=> chore: setup marimo build to use oso.xyz

ops/k8s-apps/production/kustomization.yaml, ops/k8s-apps/production/podinfo/kustomization.yaml
whoops hrm it seems the domains aren't automatically managed and I didn't actually have the podinfo deployed. merging again to test
=> chore: temporarily add test-podinfo to production

ops/k8s-apps/production/consumer-trino/custom-helm-values.yaml, ops/k8s-apps/production/dagster/custom-helm-values.yaml
I've already handled all of the manual things on the backend (took longer than expected cause I messed some silly things up) but this is a purely cosmetic change.
Closes: #5212
=> chore: reference oso.xyz in non-www deployments
