opensource-observer/oso

- indexer/src/events/npm.ts
- indexer/src/utils/parsing.ts
- indexer/test/utils/parsing.test.ts
* Use URL(), instead of my own regex
* Add a parser for npm URLs
> feat: updating parsing logic

- .github/workflows/indexer-autocrawl.yml
- .github/workflows/indexer-manual.yml
Saw this while messing around with things on my side. Hopefully this fixes that whole pipeline.
> Fix workflow vars

- .github/workflows/indexer-autocrawl.yml
- .github/workflows/indexer-manual.yml
Not sure if we can use the built in `GITHUB_TOKEN` this'll try that first.
> adds github vars

- frontend/lib/projects.ts
Makes that value functional for that data table.
> Fix dependents rendering

- .github/scripts/load-cache.sh
- .github/scripts/write-cache.sh
- .github/workflows/fetch-daily-contract-usage.yml
- .github/workflows/indexer-autocrawl.yml
- .github/workflows/indexer-manual.yml
- indexer/src/actions/dune/daily-contract-usage/client.test.ts
- indexer/src/actions/dune/daily-contract-usage/client.ts
- indexer/src/actions/dune/index.ts
- indexer/src/db/contributors.ts
- indexer/src/db/events.ts
- indexer/src/utils/array.ts
Merging this now as it's what's working. We can clean up more things later but this will work to pull contract usage every Monday for the last week.
> Daily Contract Usage Fixes

- frontend/.env.local.example
- frontend/next.config.js
- frontend/package.json
- frontend/tsconfig.json
- pnpm-lock.yaml
* Fixing the Vercel error: `PrismaClientInitializationError: Your schema.prisma could not be found`
* For reference see: https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-monorepo
* Also update .env.local.example for frontend
> fix: using @prisma/nextjs-monorepo-workaround-plugin

- frontend/components/dataprovider/supabase-query.tsx
- frontend/plasmic-init-client.tsx
* Use SWR to better cache supabase queries
* Automatically generate a unique key based on the query if we need to
* Allow user to specify children to render on error
* Provide way to specify test data
> feat: beef up the SupabaseQuery

- indexer/src/actions/github/fetch/commits.ts
Hrm. My little tool has a race condition I'll have to deal with later. This fixes it for now.
> Fixes commit race condition

- frontend/app/globals.css
- frontend/app/layout.tsx
- frontend/package.json
- frontend/postcss.config.js
- frontend/tailwind.config.js
- pnpm-lock.yaml
* Turns out it's a pre-requisite for Tremor
> feat: install TailwindCSS

- frontend/components/dataprovider/event-data-provider.tsx
- frontend/lib/common.ts
- frontend/lib/errors.ts
- frontend/plasmic-init-client.tsx
* Currently just a does a really simple SQL query no matter what the visualization is
* Formats the resulting Event data into a format appropriate for the viz
* TODO: we should do the aggregation in the SQL query instead if possible, to save on bandwidth and computation and memory
> feat: EventDataProvider

- indexer/prisma/migrations/20230907212459_add_contributor_groups/migration.sql
- indexer/prisma/schema.prisma
> Add contributor groups

- frontend/components/dataprovider/event-data-provider.tsx
* Checks if artifactIds or eventTypes are empty
* Checks if endDate <= startDate
* Turn off revalidation for SWR
> fix: EventDataProvider bypasses supabase is query is null set

- frontend/components/dataprovider/event-data-provider.tsx
* This will enable SWR to cache it
> fix: just use dates for the EventDataProvider query

- indexer/prisma/migrations/20230912174703_add_details_to_contributors/migration.sql
- indexer/prisma/schema.prisma
Needed for now. We will eventually merge artifacts and contributors but need this to complete some current tasks.
> Optionally add details to contributor

- indexer/prisma/migrations/20230913233330_add_logs_and_jobs/migration.sql
- indexer/prisma/schema.prisma
Made this during travel. Want to keep this synced across my code but also intend to use this as part of the github action work for #152
> Add logging and job tracking to DB

- indexer/src/actions/dune/funding-event-collector.ts
- indexer/src/actions/dune/funding-events/client.ts
- indexer/src/cacher/time-series.ts
- indexer/src/cli.ts
- indexer/src/db/artifacts.ts
- pnpm-lock.yaml
A bit messy but will be cleaned up once all of the github actions related work is completed. For now, this was just to get it across the finish line for #187.
Closes #187
> Collect funding events

- indexer/prisma/migrations/20230919085740_ranged_event_pointers/migration.sql
- indexer/prisma/schema.prisma
Part of #170. Instead of transitioning everything (which turns out to be a bit of a massive lift). We will add a new table and slowly get rid of the other one.
> Adds ranged event pointer

- indexer/README.md
- indexer/package.json
- indexer/prisma/migrations/20230920203753_tweak_event_ts/migration.sql
- indexer/prisma/schema.prisma
- pnpm-lock.yaml
* Add to/from artifactIds
* Remove details from EventTs
* Added instructions on how to dump the database in README
* Update supabase CLI version
> feat: update EventTs table

- indexer/package.json
- indexer/src/actions/github/upsertOrg/upsertGithubReposForOrg.ts
- indexer/src/db/entities.ts
- indexer/src/events/github/getOrgRepos.ts
- pnpm-lock.yaml
Needed to fix this before moving onto the big hairy db rewrite
> ImportOssDirectory Fixes

- indexer/src/actions/dune/funding-event-collector.ts
- indexer/src/cacher/time-series.test.ts
- indexer/src/cacher/time-series.ts
- indexer/src/cli.ts
- indexer/src/db/entities.ts
- indexer/src/recorder/recorder.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/jobs.ts
- indexer/src/scheduler/pointers.ts
- indexer/src/scheduler/types.ts
- indexer/src/utils/ranges.ts
This is actually just the start. However, I don't want what we have to drift too far from this so I'd like to merge this in already. It works now (woo!). It needs some clean up that I was hoping to accomplish sooner but this is fine for now. This handles event pointers and caching properly with any given collector. I'll need to make some documentation and also there're opportunities to clean this up much more. It's a bit jank at the moment to get this working quickly. Primarily the function that configures the scheduler `defaults` needs to be redone. 
If we'd like to use it, the CLI command is:
```
pnpm start scheduler funding-events
```
Eventually the idea is simply that we'd have a github action that calls
```
pnpm start scheduler 
```
To schedule all events. Then
```
pnpm start worker …
```
> Scheduler/Collector Interface

- docker/compose.yaml
- docker/install.sh
Just a start. everything still broken haha
> Docker to run db tests

- indexer/src/db/jobs.ts
This thing is still unused so it was an easy lift
> move jobs repository around

- indexer/package.json
- indexer/src/db/data-source.ts
- indexer/src/db/migration/1695752959358-create.ts
- indexer/src/db/orm-entities.ts
* Creates all the entities and event hyperctable
* Adds some convenience scripts for migration
> feat: initial TypeORM migrations

- indexer/src/db/data-source.ts
- indexer/src/db/migration/1695756174303-view_daily.ts
- indexer/src/db/orm-entities.ts
* Adds continuous aggregates for EventsDailyByArtifact and EventsDailyByProject
* Updates the migration to add continuous policies
> feat: continuous aggregates

- frontend/app/artifact/[namespace]/[...name]/page.tsx
- frontend/lib/common.ts
- frontend/lib/paths.ts
- frontend/middleware.ts
- indexer/README.md
- indexer/src/db/migration/1695756174303-view_daily.ts
- indexer/src/db/migration/1695760450566-tweaks.ts
- indexer/src/db/orm-entities.ts
* Fixed TypeORM enum to use lower-case strings
* Strip out the translation to ArtifactNamespace, since they're all lowercase anyway
* Added unsafeCast
* Fix down migration to remove continuous aggregate policy
> fix: misc typeorm migration bugs

- frontend/next.config.js
- frontend/package.json
- pnpm-lock.yaml
> fix: remove prisma monorepo workaround from next.js. Add typeorm into

- docker/Dockerfile
- docker/compose.yaml
- docker/install.sh
- docker/test.sh
- indexer/src/config.ts
- indexer/src/db/artifacts.ts
- indexer/src/db/data-source.ts
- indexer/src/db/events.ts
- indexer/src/db/migration/1695752959358-create.ts
- indexer/src/db/project.ts
- indexer/src/recorder/recorder.test.ts
- indexer/src/recorder/recorder.ts
* Fixes docker test
* Not all linting is yet addressed
* Fixes any indexer build errors
> Various Build Fixes

- docker/compose.yaml
- indexer/src/actions/dune/funding-event-collector.ts
- indexer/src/cli.ts
- indexer/src/config.ts
- indexer/src/db/data-source.ts
- indexer/src/db/entities.ts
- indexer/src/db/migration/1695752959358-create.ts
- indexer/src/db/migration/1695760450566-tweaks.ts
- indexer/src/db/orm-entities.ts
- indexer/src/recorder/recorder.test.ts
- indexer/src/recorder/recorder.ts
- indexer/src/recorder/types.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/pointers.ts
- indexer/src/scheduler/types.ts
- package.json
Discovered out the errors I was getting were with a local set of caching. The recorder doesn't inherently record duplicates. Only if the cache is somewhat corrupted. This addresses many issues to move forward with all of the collectors.
> Fixes Funding Collector

- indexer/package.json
- indexer/src/actions/github/fetch/commits.ts
- indexer/src/cli.ts
- indexer/src/scheduler/index.ts
- pnpm-lock.yaml
Commits load for a given time range
> Fix commit loading

- .github/cache.Dockerfile
- .github/scripts/write-cache.sh
Cache writer wasn't using the right directory to upload the cache.
> Fixes issues with the cache writing

- indexer/src/actions/dune/funding-events/client.ts
- indexer/src/actions/github/fetch/commits.ts
- indexer/src/actions/github/fetch/common.ts
- indexer/src/actions/github/fetch/pull-requests.ts
- indexer/src/cacher/time-series.test.ts
- indexer/src/cacher/time-series.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/types.ts
Running into some github 500 errors but otherwise this is working for many projects.
> Fixes pull-request collector

- indexer/src/actions/github/fetch/repo-followers.ts
- indexer/src/recorder/actors.ts
- indexer/src/recorder/recorder.ts
- indexer/src/scheduler/index.ts
- indexer/src/utils/ranges.test.ts
- indexer/src/utils/ranges.ts
- indexer/src/utils/sourceIds.ts
> Fix all repo-followers

- indexer/src/actions/github/fetch/repo-followers.ts
> fix build error

- indexer/src/actions/dune/daily-contract-usage/client.ts
- indexer/src/actions/dune/index.ts
- indexer/src/cacher/time-series.ts
- indexer/src/db/artifacts.ts
- indexer/src/recorder/recorder.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/types.ts
Fairly big rewrite of this. It now uses the recorder and the updated caching interface while also properly recording event pointers. 
Still need to run some tests.
> Fix Dune Daily Contract Usage Collection

- .github/scripts/write-cache.sh
- .github/workflows/indexer-create-job.yml
- .github/workflows/indexer-worker-dune.yml
- .github/workflows/indexer-worker-github.yml
- .github/workflows/indexer-worker.yml
This will run jobs daily and weekly now
> Automatic Actions Running

- indexer/src/actions/dune/funding-event-collector.ts
- indexer/src/actions/dune/index.ts
- indexer/src/actions/github/fetch/commits.ts
- indexer/src/actions/github/fetch/common.ts
- indexer/src/actions/github/fetch/pull-requests.ts
- indexer/src/actions/github/fetch/repo-followers.ts
- indexer/src/cli.ts
- indexer/src/recorder/recorder.test.ts
- indexer/src/recorder/recorder.ts
- indexer/src/recorder/types.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/types.ts
- indexer/src/utils/pubsub.test.ts
- indexer/src/utils/pubsub.ts
- indexer/src/utils/ranges.ts
* Made recorder flushing continuous and more frequent. 
* Added a timeout to the recorder responses (this will hopefully catch any major problems that we had with hanging)
* Some CLI updates
> Various improvements

- frontend/.eslintrc.json
- indexer/.eslintrc.json
- indexer/src/actions/dune/funding-event-collector.ts
- indexer/src/actions/dune/index.ts
- indexer/src/actions/github/fetch/commits.ts
- indexer/src/actions/github/fetch/common.ts
- indexer/src/actions/github/fetch/pull-requests.ts
- indexer/src/actions/github/fetch/repo-followers.ts
- indexer/src/cacher/time-series.ts
- indexer/src/recorder/recorder.test.ts
- indexer/src/recorder/recorder.ts
- indexer/src/recorder/types.ts
- indexer/src/scheduler/common.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/types.ts
- indexer/src/utils/array.ts
* Fixes a silly bug in the commit collector
* Improves performance and memory usage of the recorder
* Updates all collectors for update to the recorder
* Improves some logging
> Recorder Bug Fixes and Performance Fixes

- indexer/src/actions/github/fetch/pull-requests.ts
- indexer/src/db/jobs.test.ts
- indexer/src/db/testing.ts
- indexer/src/index.ts
- indexer/src/recorder/recorder.test.ts
- indexer/src/scheduler/pointers.test.ts
- indexer/src/scheduler/pointers.ts
- indexer/src/scheduler/types.ts
- indexer/src/utils/array.ts
Found a bug related to an overly complicated query I wrote (which I've simplified)
Added tests. Also am tests for the recorder to be flakey. I'll file a follow on task to get docker compose in CI and also to fix those tests
> Fix event pointer handling

- indexer/src/actions/github/fetch/commits.ts
- indexer/src/actions/github/fetch/common.ts
- indexer/src/events/npm.ts
- indexer/src/recorder/recorder.ts
- indexer/src/recorder/types.ts
- indexer/src/scheduler/common.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/types.ts
* Migrates NPM
This has already collected up to Oct 5th.
closes #268
> Migrate NPM to Collector interface

- .eslintrc.js
- frontend/next.config.js
- frontend/tsconfig.json
* /docs to GitHub markdown directory
* /discord to discord server
> feat: add next.js redirects

- indexer/src/db/events.test.ts
- indexer/src/db/events.ts
- indexer/src/recorder/recorder.ts
Updating events won't work correctly unless source and type are passed to the bulk updater. 
Bulk update likely needs to have it's performance improved but this works for now.
> Bulk event update needs additional params

- .github/workflows/indexer-worker-dune.yml
- .github/workflows/indexer-worker-manual.yml
- .github/workflows/indexer-worker.yml
Apologies. I missed this commit the last time
> Fixing logging take-2

- indexer/src/actions/github/fetch/pull-requests.ts
- indexer/src/db/testing.ts
- indexer/src/recorder/group.ts
- indexer/src/recorder/recorder.ts
- indexer/src/recorder/types.ts
- indexer/src/scheduler/pointers.test.ts
- indexer/src/scheduler/pointers.ts
- indexer/src/scheduler/types.ts
Found a variety of problems debugging an issue on the `github-issues` collector. 
* Fixes pointer math, so pointers are properly joined (updates tests)
* Fixes recorder error reporting
* Fixes date time usage for `github-issues`
> Fix bugs on github-issues collector

- .github/workflows/indexer-worker-dune.yml
- .github/workflows/indexer-worker-github.yml
- .github/workflows/indexer-worker-npm.yml
- .github/workflows/indexer-worker.yml
Fixes:
* Fixes: #355 
* Reduces code copy/paste by using a reusable action
> Add NPM for daily cron

- .github/workflows/indexer-worker-dune.yml
- .github/workflows/indexer-worker-github.yml
- .github/workflows/indexer-worker-npm.yml
Those didn't work as expected. Let's use absolute for now.
> Reusable GH actions: Remove relative paths

- frontend/app/not-found.tsx
* Import the 404Page from Plasmic
* Create a custom not-found page that renders it
> feat: Custom Plasmic 404 page

- frontend/.gitignore
- frontend/codegen.ts
- frontend/lib/config.ts
- frontend/lib/graphql/queries.ts
- frontend/package.json
- frontend/tsconfig.json
- pnpm-lock.yaml
* Use graphql-codegen to create types
* Leverage the generated `gql` for queries
* Add package.json scripts for generating types
* Update config.ts to load .env files (since it's also used for codegen)
> feat: apollo with TypeScript

- frontend/components/dataprovider/event-data-provider.tsx
- frontend/lib/config.ts
- frontend/lib/graphql/queries.ts
- frontend/plasmic-init-client.tsx
* Add queries for continuous aggregates
* Remove invalid import in config
* Allow selection of entityType
> feat: update EventDataProvider to use GraphQL

- indexer/src/actions/github/fetch/common.ts
- indexer/src/actions/oss-directory.ts
- indexer/src/cli.ts
- indexer/src/db/artifacts.ts
- indexer/src/db/entities.ts
Fixes some bugs in importOssDirectory #319
Fixes #309
> Address idempotency in importOssDirectory

- indexer/database/get_indexer_progress.sql
Addresses (in a manumatic way) #179. For now this doesn't have Dune progress, but I will add that later today once I start indexing. It will be different for different queries likely. 
Closes #179
> Indexer progress query

- frontend/components/widgets/algolia.tsx
* Adding a simple popover for search results from Algolia. We can make this prettier in the future
> feat: Styling for Algolia search box

- frontend/components/dataprovider/event-data-provider.tsx
* Fill in empty data, even if 0s
* Trim empty data points at the beginning and end of time range
* Abstract out default entityType and xAxis
* Add comments
* Abstract out the ProviderView
> fix: EventDataProvider fixes

- frontend/components/dataprovider/event-data-provider.tsx
- frontend/components/dataprovider/provider-view.tsx
- frontend/components/dataprovider/supabase-query.tsx
- frontend/components/dataprovider/table-data-provider.tsx
- frontend/plasmic-init-client.tsx
* Abstract out some of the common logic in data providers into DataProviderView
* Use this in the EventDataProvider and SupabaseQuery components
* Start the shell of the TableDataProvider
> feat: DataProviderView

- frontend/README.md
- indexer/utilities/database/hasura.sh
* Convenience scripts to start up a docker container with Hasura
* Instructions on how to run the application with Hasura
> feat: Run Hasura locally

- .github/scripts/scheduler.sh
- indexer/src/config.ts
- indexer/src/scheduler/index.ts
This is just a quick hack to make this work for now.
> Dune Client Needs Path to CSV of contracts

- frontend/components/dataprovider/event-data-provider.tsx
- frontend/lib/graphql/queries.ts
> Fixes the frontend build

- indexer/src/actions/github/fetch/commits.ts
- indexer/src/cli.ts
- indexer/src/db/data-source.ts
- indexer/src/db/events.ts
- indexer/src/db/testing.ts
- indexer/src/recorder/recorder.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/pointers.test.ts
- indexer/src/scheduler/types.ts
This is currently executing to address #410 and #397
> Webflow reindexing fixes

- frontend/components/dataprovider/event-data-provider.tsx
- frontend/plasmic-init-client.tsx
* We will be detangling the EventDataProvider and deprecating the general one soon
> feat: Add ProjectEventDataProvider and ArtifactEventDataProvider

- indexer/src/events/npm.ts
- indexer/src/recorder/recorder.ts
I noticed issues with npm due to luxon comparisons. Turns out `.equals` doesn't determine equality to the actual second. It determines if the `DateTime` objects are configured the same. So something set to timezone `Z` isn't the same as timezone `00:00` 🤦 
Also fixed some other bits of weirdness and reran for the last few days.
> bug fixes in npm downloads

- frontend/components/dataprovider/event-data-provider.tsx
- frontend/lib/graphql/queries.ts
- frontend/plasmic-init-client.tsx
* Create new GraphQL queries for retrieving projects and artifacts by ids
* Create a constant for the default startDate
* Provide a way to pull the artifact/project name by ID
* ArtifactEventDataProvider and ProjectEventDataProvider need to query for the artifact/project metadata now
* Make queries explicit on artifactId or projectId
> feat: show artifact or project names in the barlist

- frontend/components/dataprovider/event-data-provider.tsx
* If there are dates with no data, we should make that explicit and return 0's where appropriate. Otherwise, the area chart looks busier than it actually is
* We now properly segregate area chart on both the entityId and the eventType
> fix: fill empty dates

- indexer/src/db/data-source.ts
- indexer/src/db/migration/1698253664753-first-contribution-view.ts
- indexer/src/db/orm-entities.ts
* Adding a FirstContribution materialized view that fetches the first event for each (to,from) pair.
> feat: FirstContribution materialized view

- docs/grants.md
- indexer/src/actions/github/fetch/commits.ts
- indexer/src/actions/github/fetch/common.ts
- indexer/src/cli.ts
- indexer/src/db/events.ts
- indexer/src/recorder/recorder.ts
- indexer/src/scheduler/common.ts
- indexer/src/scheduler/index.ts
This fixes a lot of bugs that continously stopped a long reindexing job from running properly. 
Fixes #410
Fixes #397
> Webflow reindexing related bugs

- indexer/src/actions/dune/daily-contract-usage/client.ts
- indexer/src/actions/dune/index.ts
- indexer/src/actions/dune/utils/csv-uploader.ts
- indexer/src/scheduler/index.ts
Realized, new contracts getting added weren't properly being indexed. I'll find where those are and make sure they get taken care of.
> Continously upload the Dune Contracts Table

- indexer/src/recorder/recorder.ts
Caught this while I was back at a computer. One of the backfill jobs was hanging... I made a silly error.
> Logic typo fix

- indexer/src/collectors/github-followers.ts
- indexer/src/collectors/github-issues.ts
- indexer/src/scheduler/index.ts
Using the project grouping didn't make much sense anyway.
> Use the batch grouping instead of project grouping for github collectors

- indexer/src/db/migration/1698954113655-first-contribution-type.ts
- indexer/src/db/orm-entities.ts
* Previously it was on toId and fromId, so we couldn't see the first commit for example
> fix: FirstContribution DISTINCT on toId, fromId, typeId

- frontend/components/dataprovider/event-data-provider.tsx
- frontend/plasmic-init-client.tsx
* Recommending using ProjectEventDataProvider and ArtifactEventDataProvider
> fix: remove EventDataProvider

- frontend/lib/graphql/queries.ts
* Adding the cached directive to most graphql queries. The only ones I don't cache are EventData from the continuous aggregates
> fix: add caching to most GraphQL queries

- frontend/components/dataprovider/event-data-provider.tsx
- frontend/lib/graphql/queries.ts
- frontend/lib/types/db.ts
- frontend/plasmic-init-client.tsx
* Creates a new GraphQL query and DataProvider that wraps the new materialized view.
> feat: ProjectUserDataProvider

- .github/scripts/backfill.sh
- .github/workflows/indexer-create-backfill-job.yml
- indexer/src/cli.ts
- indexer/src/collectors/dune-daily-contract-usage.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/types.ts
> Fix daily-contract-usage factories retreival

- .github/scripts/backfill.sh
My bad. This will fix the usage of this script
> Fixes variable interpolation

- indexer/src/config.ts
- indexer/src/db/data-source.ts
@ccerv1 i believe this should address issue we've been experiencing with `first_contribution` materialized view. We (read as I) mistakenly set an unsafe value for production
> removes db synchronize by default

- frontend/app/api/project-event-aggregates/route.ts
- frontend/lib/graphql/queries.ts
* Also change ? => 0 in the table
> use events_monthly_to_project for event aggregates

- frontend/app/api/project-event-aggregates/route.ts
- frontend/components/dataprovider/table-data-provider.tsx
- frontend/lib/graphql/cached-queries.ts
- frontend/lib/graphql/queries.ts
* Hasura max is 300 seconds
* Next.js routes is 1 day
* Sort the SWR key so it can cache properly if re-ordered
> feat: up the TTL

- indexer/src/cli.ts
- indexer/src/collectors/github-followers.ts
- indexer/src/collectors/github/common.ts
- indexer/src/scheduler/types.ts
Found some issues in the followers though it potentially affected other collectors. This will actually now properly print all errors related to any artifacts at the end of a given collection. It's a bit noisy but that's better than nothing for now.
> Followers Issues

- frontend/app/[...catchall]/page.tsx
- frontend/app/api/project-event-aggregates/route.ts
- frontend/app/artifact/[namespace]/[...name]/page.tsx
- frontend/app/project/[...slug]/page.tsx
- frontend/components/widgets/algolia.tsx
- frontend/lib/graphql/cached-queries.ts
- frontend/plasmic-init-client.tsx
> fix: disable isr, force-static where we can and disable revalidate where

- indexer/src/recorder/recorder.ts
- indexer/src/recorder/types.ts
- indexer/src/scheduler/types.ts
> Safe clean of the recorder's temp table

- indexer/src/cli.ts
- indexer/src/scripts/db-utilities.ts
- indexer/src/utils/cli.ts
I can make a GH action for this later. For now this was useful to run locally.
> Add a CLI command to refresh materialized views

- package.json
- pnpm-lock.yaml
* This is because devDependencies don't seem to be installed on production
> fix: devDependencies to dependencies at root

- frontend/next.config.js
* /forms/kariba-interest
* /forms/oso-data-collective
> feat: add new form redirects

- indexer/src/db/data-source.ts
- indexer/src/db/migration/1699775810960-events-to-collection.ts
- indexer/src/db/orm-entities.ts
* EventsDailyToCollection
* EventsWeeklyToCollection
* EventsMonthlyToCollection
* Migration to run against database
> feat: events to collection aggregates

- frontend/components/dataprovider/event-data-provider.tsx
- frontend/lib/graphql/queries.ts
- frontend/plasmic-init-client.tsx
* Follows closely what we did for projects and artifacts
> feat: Add CollectionEventDataProvider

- frontend/components/dataprovider/event-data-provider.tsx
* Removed the hardcoded event types in EventDataProvider
* Fetch from GraphQL and make maps dynamically
> fix: remove hard-coded eventTypes

- frontend/components/widgets/algolia.tsx
* Replaced the search bar with a button icon
* When you click the icon, it opens up a modal search interface
> feat: update search UX

- indexer/src/collectors/npm-downloads.ts
- indexer/src/recorder/recorder.ts
- indexer/src/scheduler/index.ts
- indexer/src/scripts/db-utilities.ts
Fixes after running an NPM reindex.
> Small reindex fixes

- .github/scripts/start-redis.sh
- .github/scripts/stop-redis.sh
- .github/workflows/indexer-worker-dune.yml
- .github/workflows/indexer-worker-github.yml
- .github/workflows/indexer-worker-npm.yml
- .github/workflows/indexer-worker.yml
- .github/workflows/indexer-worker/action.yml
- indexer/src/scheduler/index.ts
- indexer/src/scripts/db-utilities.ts
Commits the redis cache to disk for use on every action. Hopefully this prevents things from hanging as they are hanging right now.
> Improve redis usage

- .github/workflows/indexer-refresh-mvs.yml
> Fix refresh-mv action name

- indexer/package.json
- indexer/src/collectors/dependents.ts
- indexer/src/collectors/github-followers.ts
- indexer/src/collectors/github/common.ts
- indexer/src/collectors/github/multiplex-graphql.ts
- indexer/src/db/orm-entities.ts
- indexer/src/recorder/group.ts
- indexer/src/scheduler/index.ts
- indexer/src/scheduler/types.ts
- pnpm-lock.yaml
Was developing this for use with package dependencies. I tested with followers and it works really well. I am committing in before completing deps.
> Multiplex GraphQL

- .github/scripts/start-redis.sh
Sometimes this is failing if the docker load is slow.
> Fix redis startup

- .github/scripts/start-redis.sh
- .github/scripts/stop-redis.sh
Unfortunately, only way to fix is to test here
> Fix redis start (Take 2)

- .github/workflows/indexer-clear-cache.yml
- indexer/src/collectors/github/common.ts
- indexer/src/collectors/npm-downloads.ts
- indexer/src/recorder/recorder.ts
Luckily this only affected NPM. This could have caused problems elsewhere but magically did not.
> Fixes NPM Caching issues

- indexer/src/collectors/import-oss-directory.ts
Fixes #542 
Tested on a local data set
> Mark deprecated collections as deleted

- indexer/package.json
- pnpm-lock.yaml
Schema had some breaking changes from 0.0.5 -> 0.0.7.
> update oss-directory dep

- frontend/README.md
- frontend/lib/types/supabase.ts
- frontend/package.json
- frontend/supabase/.gitignore
- frontend/supabase/config.toml
- frontend/supabase/migrations/20240125160035_user_management.sql
- package.json
- pnpm-lock.yaml
* Added Supabase CLI and migrations for the user table
* Generated the Supabase schema into TypeScript types
* Updated README to remove deprecated stuff
> feat: Supabase migrations for users

- docs/docs/index.mdx
- docs/docs/integrate/getting-started.md
- docs/docs/intro.md
- docs/docusaurus.config.ts
- frontend/next.config.js
* Redirecting /data-collective to kariba.network
* Fix the sidebar order in docs
> docs: outline getting started

- cloudquery/github-resolve-repos/package.json
- cloudquery/github-resolve-repos/src/github/get-org-repos.ts
- cloudquery/github-resolve-repos/src/github/repositories.ts
- cloudquery/github-resolve-repos/src/github/unpaginate.ts
- cloudquery/github-resolve-repos/src/plugin.ts
- cloudquery/github-resolve-repos/src/tables.ts
- pnpm-lock.yaml
We need to add some more information when we pull down the repositories. This supports some of the changes required to get gharchive's commits to match the original OSO db a bit more.
> Update github-resolve-repos to pull more repo info

- frontend/components/dataprovider/auth-context.tsx
- frontend/components/dataprovider/supabase-query.tsx
- frontend/components/widgets/auth-form.tsx
- frontend/lib/clients/supabase.ts
* Not sure if this is causing Plasmic to not load, just trying
> fix: switching from Next.js supabase client to the generic JS one

- frontend/app/[...catchall]/page.tsx
- frontend/app/artifact/[namespace]/[...name]/page.tsx
- frontend/app/project/[...slug]/page.tsx
- frontend/components/dataprovider/auth-context.tsx
* See if this fixes the 500 errors
* Add supabase client to the AuthContext
> fix: remove searchParams from dyanmic pages

- frontend/app/[...catchall]/page.tsx
- frontend/app/artifact/[namespace]/[...name]/page.tsx
- frontend/app/project/[...slug]/page.tsx
> feat: restore searchParams, dynamically modify force-dynamic/static

- dbt/models/artifacts.sql
- dbt/models/github_commits.sql
- dbt/models/github_distinct_main_commits.sql
- dbt/models/github_events.sql
- dbt/models/github_push_events.sql
This gets us closer (not yet completely the way there) to something similar in shape to v1 of `oso`.
> Adds github commit transforms in dbt

- cloudquery/dune-contract-usage/README.md
- cloudquery/dune-contract-usage/dune_contract_usage/__init__.py
- cloudquery/dune-contract-usage/dune_contract_usage/client/__init__.py
- cloudquery/dune-contract-usage/dune_contract_usage/client/client.py
- cloudquery/dune-contract-usage/dune_contract_usage/load_csvs.py
- cloudquery/dune-contract-usage/dune_contract_usage/parse.py
- cloudquery/dune-contract-usage/dune_contract_usage/plugin.py
- cloudquery/dune-contract-usage/dune_contract_usage/serve.py
- cloudquery/dune-contract-usage/dune_contract_usage/tables/__init__.py
- cloudquery/dune-contract-usage/dune_contract_usage/tables/table.py
- cloudquery/dune-contract-usage/pyproject.toml
- cloudquery/dune-contract-usage/testdata/config.yml
- cloudquery/github-resolve-repos/src/github/get-org-repos.ts
- cloudquery/github-resolve-repos/src/tables.ts
- dbt/models/all_events.sql
- dbt/models/all_events_by_project.sql
- dbt/models/artifacts.sql
- dbt/models/collections_projects.sql
- dbt/models/github_commits.sql
- dbt/models/github_distinct_commits_resolved_mergebot.sql
- dbt/models/github_events.sql
- dbt/models/github_issues.sql
- dbt/models/github_pull_request_merge_events.sql
- dbt/models/github_pull_requests.sql
- dbt/models/github_push_events.sql
- dbt/models/github_sources.yml
- dbt/models/github_stars_and_forks.sql
- poetry.lock
- pyproject.toml
* Adds Arbitrum Data
* Adds the remaining github events
> Arbitrum Data and more Github Events

- frontend/components/dataprovider/auth-context.tsx
- frontend/components/dataprovider/auth-router.tsx
- frontend/package.json
- frontend/plasmic-init-client.tsx
- pnpm-lock.yaml
* Renamed AuthContext to AuthRouter, which is only responsible for showing different things depending on if you are logged in or not
* Added AuthGlobalContext, a global context with signin/signout interactions that are defined, plus a global user object that should be accessible in Studio
> feat: AuthGlobalContext and AuthRouter

- frontend/package.json
- frontend/plasmic-init-client.tsx
- pnpm-lock.yaml
* Add it as a Plasmic function
> feat: generate API keys

- frontend/components/dataprovider/auth-router.tsx
- frontend/components/widgets/auth-actions.tsx
- frontend/components/widgets/supabase-write.tsx
- frontend/lib/clients/supabase.ts
- frontend/plasmic-init-client.tsx
* Generic click handler for writing to Supabase, supports insert, upsert, update, and delete
> feat: SupabaseWrite code component

- oso/bq2cloudsql/cloudsql.py
- oso/bq2cloudsql/script.py
- oso/bq2cloudsql/synchronizer.py
* Rename's bigquery tables to add a `bq_` prefix
* Adds retry loop for api calls
* Combines CSV files in place at GCS to speed up table sync
> Bug fixes for BigQuery table sync

- frontend/components/widgets/auth-actions.tsx
- frontend/components/widgets/supabase-write.tsx
* Add the ability in Plasmic to specify a redirect after login or logout
* Removed deprecated `redirect` and use router
> feat: redirect after logout

- frontend/app/api/auth/route.ts
* For now just return the anon role all the time while we debug the API rate limits
> feat: starting an Auth hook

- frontend/app/api/auth/route.ts
* Also fixes the webhook response to conform to spec
> feat: auth hook cache control

- .github/scripts/create-dbt-profile.sh
- .github/workflows/cloudquery/github-resolve-repos.yml
- .github/workflows/cloudquery/oss-directory.yml
- .github/workflows/warehouse-run-data-pipeline.yml
The data pipeline is now working without issue. I had to introduce a silly fix to deal with the fact that cloudquery plugins are supposed to be run from docker containers. It's a bit of a punt but I included some info inline about it. We will need to potentially consider meltano anyhow. I'll do some reading tonight. 
Closes #756 and #757
> Working data pipeline

- .github/workflows/warehouse-run-data-pipeline.yml
Accidentally left this in the workflow
> Fix testing string

- dbt_project.yml
- docs/docs/contribute/adding-dbt-models.md
- docs/docs/contribute/intro.md
Still collecting a few things here. I would like to have at least some of the staging configuration actually figured out so this can be used but this should be enough to get started as an explanation of what the directories are and how and when things are deployed.
> Adding a DBT model docs

- dbt/models/marts/github_metrics/github_metrics_by_collection.sql
This addresses some of the issues with this model's execution.
> Fix issues with model

- docs/docs/contribute/extract/write-data-connector.md
> Docs: Add CloudQuery Plugin to the pipeline

- dbt/.gitignore
- dbt/models/staging/dune/stg_dune__schema.yml
- dbt/models/staging/github/stg_github__schema.yml
- dbt/models/staging/oss-directory/stg_ossd__schema.yml
**Aim**: add `stg_<source>__schema.yml` in each folder for staging models.
**Benefits**:
- grow documentation of the existing schema while keeping it close to the codebase
- add basic data quality checks: not_null, unique, accepted_values
- potential to add more tests using `dbt_utils` (for example: `dbt_utils.unique_combination_of_columns`)
> dbt: add schema for staging models

- dbt/models/staging/dune/stg_dune__schema.yml
- dbt/models/staging/github/stg_github__schema.yml
- dbt/models/staging/oss-directory/stg_ossd__schema.yml
Removing tests, to be revisited some other time. Reason: inflated load time + costs.
> dbt: staging schema - remove tests

- ops/tf-modules/warehouse/main.tf
Seems odd to have this for a public dataset but it's for external connection's we're using that need read access through a service account (like algolia)
> Add readonly user for a dataset

- docs/docs/contribute/transform/adding-dbt-models.md
- docs/docs/contribute/transform/setting-up-gcp.md
Addresses #925 though we should add screenshots. I will try to do this tomorrow but I'll need to setup a new Google Account as my personal already has gone through all the GCP first time steps.
> Add docs for setting up GCP

- README.md
- dbt/models/staging/dune/stg_dune__arbitrum_contract_invocation.sql
- docs/docs/contribute/transform/create-impact-metrics.md
> Remove references to old dataset

- oso/bq2cloudsql/cloudsql.py
Saw that the script was failing here periodically. Perhaps this can help to retry the SSL errors that might occur.
> bq2cloudsql small fixes

- dbt/models/marts/code_metrics/code_metrics_by_collection.sql
- dbt/models/marts/code_metrics/code_metrics_by_project.sql
- dbt/models/marts/onchain_metrics/onchain_metrics_by_collection.sql
- dbt/models/marts/onchain_metrics/onchain_metrics_by_project.sql
Marts should be namespace flattened and should have a very obvious name when being read by external parties
> Address mart naming

- apps/docs/docs/contribute/impact-models.md
- poetry.lock
- pyproject.toml
- warehouse/oso_lets_go/README.md
- warehouse/oso_lets_go/wizard.py
Probably, I shouldn't have pursued this but I got a working wizard (I really wanted this haha). 
I need to integrate this into the docs but essentially, it can pick up immediately after the point when someone _initializes_ a GCP account. It will also ask to copy the playground data into their playground area.
> Setup Wizard

- apps/docs/docs/index.mdx
- apps/docs/package.json
- apps/docs/plasmic.json
- apps/docs/src/components/plasmic/Overview.tsx
- apps/docs/src/components/plasmic/plasmic-tokens.theo.json
- apps/docs/src/pages/index.mdx
- pnpm-lock.yaml
* Change Plasmic to use latest published version
* Add color mode toggles for Plasmic components
* There's something broken about how Docusaurus exposes the colorMode, need to file an issue around this
> docs: dark mode Plasmic partial progress

- .github/scripts/publish-cloudquery-plugins.sh
We have some build issues. Tested this locally. This _should_ fix them.
> Cloudquery prefix is interfering with correct naming

- .github/workflows/test-meltano-pipeline.yml
- warehouse/meltano-setup/.gitignore
- warehouse/meltano-setup/README.md
- warehouse/meltano-setup/meltano.yml
- warehouse/meltano-setup/output/.gitignore
- warehouse/meltano-setup/plugins/extractors/tap-airbyte-wrapper--meltanolabs.lock
- warehouse/meltano-setup/plugins/extractors/tap-github--meltanolabs.lock
- warehouse/meltano-setup/plugins/extractors/tap-postgres--airbyte.lock
- warehouse/meltano-setup/plugins/loaders/target-jsonl--andyh1203.lock
- warehouse/meltano-setup/pyproject.toml
I've gotten this to work easily with postgres using airbyte's "STANDARD" replication which they suggest for databases with less than 500GB. However, seeing as we want to replicate some rather large db's i'm still doing some testing. However, I need to merge this in to do that (It seems that my local ISP doesn't support ipv6 connections which i need for the supabase test DB i'm using)
> Meltano testing

- apps/frontend/app/api/auth/route.ts
- apps/frontend/package.json
- apps/hasura/metadata/api_limits.yaml
- pnpm-lock.yaml
* Elevate to user role, if you have a developer key but not on kariba data collective. previously this was stuck at anon role
* Add JWT token decoding, just for seeing if we can get this to work
* Up some API limits
> feat: adjust api auth route

- .github/workflows/test-meltano-pipeline.yml
- warehouse/meltano-setup/README.md
- warehouse/meltano-setup/meltano.yml
- warehouse/meltano-setup/pyproject.toml
Finally got everything setting up local the way that it works. I ran _multiple_ tests (had run into another bug for something I thought would be seemingly simple). HOWEVER, I now have very good data for being able to write up the docs we need for this to be setup correctly. 
Closing #971 for now because we can't do a sync of our supabase dbs (which is what would make the most sense)
> Meltano CDC Sync Working

- apps/frontend/app/project/[...slug]/page.tsx
* Previously we'd await on each GraphQL query in sequence, which led to a slow render.
* This tries to parallelize what we can so that project pages can load faster
> feat: parallelize server-side queries in project page render

- apps/frontend/app/api/auth/route.ts
* Decode JWT tokens from HTTP headers and make user roles in the auth route
* Note, this only decodes, not verify. We need to come back and find a library that can actually verify on the edge
> feat: /api/auth can decode JWT tokens and return user roles

- apps/frontend/app/project/[...slug]/page.tsx
* I'm hoping this will speed up the project page
> fix: remove pre-fetching artifacts and collections

- .github/workflows/external-prs-handle-comment.yml
Thought this was addressed but it wasn't
> Fixes the parse-comment call

- warehouse/dbt/models/github_sources.yml
> Fix `int_events` and `stg_github__events`

- ops/tf-modules/warehouse/main.tf
Been doing some manual queries to get data in and trying to make sure certain things are not duplicated. Originally was doing this through airbyte + GCE but realized that bigquery can _hopefully_ do all of this without any external tool.
This dataset is meant to have less _human_ interaction from our side (the side that can write/destroy things) so that we don't accidentally lose data we've collected.
> Adding a raw sources dataset for data collection

- ops/github-app-utils/.eslintrc.json
- ops/github-app-utils/README.md
- ops/github-app-utils/package.json
- ops/github-app-utils/src/app.ts
- ops/github-app-utils/src/checks.ts
- ops/github-app-utils/src/cli.ts
- ops/github-app-utils/src/commands.ts
- ops/github-app-utils/src/error.ts
- ops/github-app-utils/src/index.ts
- ops/github-app-utils/src/logger.ts
- ops/github-app-utils/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
This is a start to writing a PR utility for oss-directory.
> Starts github app utilities

- apps/frontend/app/layout.tsx
- apps/frontend/app/plasmic-host/page.tsx
- apps/frontend/components/widgets/analytics.tsx
- apps/frontend/lib/clients/segment.ts
- apps/frontend/package.json
- pnpm-lock.yaml
Following this tutorial FWIW
https://github.com/vercel/next.js/tree/canary/examples/with-segment-analytics
> feat: upgrade to Segment analytics-next (v2)

- apps/oss-artifact-validators/.eslintrc.json
- apps/oss-artifact-validators/README.md
- apps/oss-artifact-validators/package.json
- apps/oss-artifact-validators/src/onchain/evm.ts
- apps/oss-artifact-validators/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Currently have bits of #1051 #1047. Just need to wire this into `oss-directory` for those two things. 
For factory, I think we should actually wait until all the traces data is ready. We can then actually do some historical checks to see if the contract has actually deployed another contract.
> Basic setup for evm related address validations

- warehouse/bq2cloudsql/synchronizer.py
This was the last fix to get hasura consistent
> bq2cloudsql: support copying booleans

- .github/workflows/refresh-test-credentials.yml
This is for the github workflows on oss-directory
> Add creds for oss-directory

- apps/oss-artifact-validators/src/common/config.ts
- apps/oss-artifact-validators/src/index.ts
- apps/oss-artifact-validators/src/onchain/evm.ts
- apps/oss-artifact-validators/test/test.ts
- ops/external-prs/package.json
- ops/external-prs/src/base.ts
- ops/external-prs/src/checks.ts
- ops/external-prs/src/cli.ts
- ops/external-prs/src/ossd/index.ts
- ops/external-prs/src/ossd/messages/list-changes.md
- ops/external-prs/src/ossd/messages/validation-errors.md
- ops/external-prs/src/ossd/queries/artifacts_summary.sql
- ops/external-prs/src/ossd/queries/changed_blockchain_artifacts_to_validate.sql
- ops/external-prs/src/ossd/queries/unchanged_projects.sql
- pnpm-lock.yaml
Debugging an error on optimism deployer addresses otherwise, I _believe_ this works.
> Running validations and send errors to PR

- ops/external-prs/src/ossd/index.ts
- Support setting memory limits for duckdb
> Allow setting memory limit for duckdb

- warehouse/dbt/models/lens_sources.yml
- warehouse/dbt/models/staging/lens/stg_lens__profiles.sql
* Creates a new source from the Lens public dataset
* Creates a staging model to pull out the user profiles and ownership information of each profile
> feat: lens staging data

- apps/docs/docs/how-oso-works/index.mdx
- Fixed a broken link to OSS Directory
> fix: broken link

- .github/workflows/test-deploy-clean.yml
- ops/external-prs/src/oso/deploy.ts
- Write stdout as a message into the PR
- Fixes cleaning of external-prs
Closes #1298, Closes #1254
> Various external-pr fixes

- ops/tf-modules/warehouse-cluster/README.md
- ops/tf-modules/warehouse-cluster/main.tf
- ops/tf-modules/warehouse-cluster/output.tf
- ops/tf-modules/warehouse-cluster/variables.tf
Adds a GKE cluster with spot and preemptible nodes
Closes #1279
> Add warehouse cluster tf

- .github/workflows/ci-default.yml
- ops/external-prs/src/base.ts
- ops/external-prs/src/cli.ts
- ops/external-prs/src/github.ts
- ops/external-prs/src/oso/deploy.ts
- ops/external-prs/src/oso/index.ts
- ops/external-prs/src/ossd/index.ts
- ops/external-prs/src/ossd/messages/list-changes.md
- ops/external-prs/src/ossd/messages/validation-errors.md
The github app annoyingly creates a bunch of spam messages. This addresses that by editing a single comment.
> External-PRs comment updates a single comment

- warehouse/dbt/models/lens_sources.yml
- warehouse/dbt/models/staging/lens/stg_lens__owners.sql
- warehouse/dbt/models/staging/lens/stg_lens__profiles.sql
* Update lens staging models to use the OSO copy of raw lens data
* Split up the lens models so there's no joins at the staging layer
* Includes separately now, ownership table and profile table
> fix: lens staging models

- warehouse/dbt/models/farcaster_sources.yml
- warehouse/dbt/models/staging/farcaster/stg_farcaster__addresses.sql
- warehouse/dbt/models/staging/farcaster/stg_farcaster__profiles.sql
* Add Farcaster sources
* Pull out profile data from the JSON
* Get non-deleted verifications
> feat: farcaster staging models

- warehouse/dbt/models/marts/onchain_metrics/onchain_metrics_by_collection_v1.sql
- warehouse/dbt/models/marts/onchain_metrics/onchain_metrics_by_project_v1.sql
* Add `_v1` to the model name
* Update names to be more consistent
> fix: onchain_metrics renaming

- README.md
- warehouse/dbt/models/marts/code_metrics/code_metrics_by_collection_v1.sql
- warehouse/dbt/models/marts/code_metrics/code_metrics_by_project_v1.sql
* Trying to follow better best practices on mart and column naming
* Add guide in README on how to setup VS Code for dbt
* add version number to mart name
* Add missing collection_slug
> fix: update the column names in code_metrics

- apps/docs/blog/2024-03-20-request-for-impact-metrics/index.md
- apps/docs/docs/contribute/impact-models.md
- apps/docs/docs/integrate/api.md
- apps/docs/docs/integrate/data-science.md
- apps/frontend/app/project/[...slug]/page.tsx
- warehouse/dbt/models/marts/code_metrics/code_metrics_by_collection_v1.sql
- warehouse/dbt/models/marts/directory/artifacts_by_project.sql
- warehouse/dbt/models/marts/directory/artifacts_v1.sql
- warehouse/dbt/models/marts/directory/collections_v1.sql
- warehouse/dbt/models/marts/directory/projects_by_collection.sql
- warehouse/dbt/models/marts/directory/projects_v1.sql
- warehouse/dbt/models/marts/directory/repos_by_project.sql
- warehouse/dbt/models/marts/events/event_indexing_status_by_project.sql
- warehouse/dbt/models/marts/onchain_metrics/onchain_metrics_by_collection_v1.sql
- warehouse/dbt/models/marts/onchain_metrics/onchain_metrics_by_project_v1.sql
- warehouse/dbt/models/marts/onchain_metrics/onchain_metrics_by_project_v2.sql
* Update references to these models
* Update the frontend queries, including the new onchain_metrics and code_metrics names
> fix: add `_v1` versioning to artifacts/projects/collections models

- warehouse/dbt/models/intermediate/directory/int_projects_by_collection.sql
- warehouse/dbt/models/marts/directory/artifacts_by_project_v1.sql
- warehouse/dbt/models/marts/directory/collections_v1.sql
- warehouse/dbt/models/marts/directory/deployers_by_project.sql
- warehouse/dbt/models/marts/directory/projects_by_collection_v1.sql
- warehouse/dbt/models/marts/directory/projects_v1.sql
- warehouse/dbt/models/marts/onchain_metrics/onchain_metrics_by_project_v2.sql
- warehouse/dbt/models/marts/project_metrics/beta/pm_contracts_deployed.sql
* Update references
* Rename user_namespace to project_namespace and collection_namespace
> fix: Add _v1 to artifacts_by_project and projects_by_collection

- poetry.lock
- pyproject.toml
- warehouse/oso_dagster/assets.py
- warehouse/oso_dagster/goldsky.py
> Sets up additional goldsky data sources

- warehouse/dbt/macros/oso_artifact_id.sql
- warehouse/dbt/models/intermediate/directory/int_artifacts.sql
- warehouse/dbt/models/intermediate/directory/int_ossd__artifacts_by_project.sql
- warehouse/dbt/models/intermediate/directory/int_ossd__repositories_by_project.sql
- warehouse/dbt/models/intermediate/events/int_events.sql
- warehouse/dbt/models/intermediate/events/int_events_with_artifact_id.sql
Redefines the inputs into `oso_artifact_id`
> Fixes oso_artifact_id to new schema

- apps/docs/docs/contribute/impact-models.md
- warehouse/oso_dagster/assets.py
- warehouse/oso_dagster/cbt/__init__.py
- warehouse/oso_dagster/cbt/bq.py
- warehouse/oso_dagster/cbt/operations/_cbt_merge.sql
- warehouse/oso_dagster/goldsky.py
> Optimize BQ merge and handle goldsky pipeline_start_time timestamp changes

- warehouse/dbt/macros/models/filtered_blockchain_events.sql
- warehouse/dbt/macros/models/goog_blockchain_deployers.sql
- warehouse/dbt/macros/models/ossd_filtered_blockchain_events.sql
- warehouse/dbt/macros/models/transactions_with_receipts_deployers.sql
- warehouse/dbt/models/base_sources.yml
- warehouse/dbt/models/frax_sources.yml
- warehouse/dbt/models/intermediate/blockchain/int_base_traces.sql
- warehouse/dbt/models/intermediate/blockchain/int_base_transactions.sql
- warehouse/dbt/models/intermediate/blockchain/int_optimism_contract_invocation_events.sql
- warehouse/dbt/models/intermediate/blockchain/int_optimism_traces.sql
- warehouse/dbt/models/intermediate/blockchain/int_optimism_transactions.sql
- warehouse/dbt/models/intermediate/events/int_events.sql
- warehouse/dbt/models/mode_sources.yml
- warehouse/dbt/models/pgn_sources.yml
- warehouse/dbt/models/playground/base__traces.sql
- warehouse/dbt/models/playground/base__transactions.sql
- warehouse/dbt/models/playground/mode__transactions.sql
- warehouse/dbt/models/playground/optimism__logs.sql
- warehouse/dbt/models/playground/optimism__receipts.sql
- warehouse/dbt/models/playground/optimism__transactions.sql
- warehouse/dbt/models/playground/superchain__optimism_traces.sql
- warehouse/dbt/models/staging/base/stg_base__deployers.sql
- warehouse/dbt/models/staging/ethereum/stg_ethereum__deployers.sql
- warehouse/dbt/models/staging/mode/stg_mode__deployers.sql
- warehouse/dbt/models/superchain_sources.yml
> Setup Optimism and Base (partial)

- warehouse/dbt/macros/models/contract_invocation_events_with_l1.sql
- warehouse/dbt/macros/models/filtered_blockchain_events.sql
- warehouse/dbt/models/intermediate/blockchain/int_base_contract_invocation_events.sql
- warehouse/dbt/models/intermediate/blockchain/int_frax_contract_invocation_events.sql
- warehouse/dbt/models/intermediate/blockchain/int_frax_traces.sql
- warehouse/dbt/models/intermediate/blockchain/int_frax_transactions.sql
- warehouse/dbt/models/intermediate/blockchain/int_mode_contract_invocation_events.sql
- warehouse/dbt/models/intermediate/blockchain/int_mode_traces.sql
- warehouse/dbt/models/intermediate/blockchain/int_mode_transactions.sql
- warehouse/dbt/models/intermediate/blockchain/int_optimism_contract_invocation_events.sql
- warehouse/dbt/models/intermediate/blockchain/int_pgn_contract_invocation_events.sql
- warehouse/dbt/models/intermediate/blockchain/int_pgn_traces.sql
- warehouse/dbt/models/intermediate/blockchain/int_pgn_transactions.sql
- warehouse/dbt/models/intermediate/blockchain/int_zora_contract_invocation_events.sql
- warehouse/dbt/models/intermediate/blockchain/int_zora_traces.sql
- warehouse/dbt/models/intermediate/blockchain/int_zora_transactions.sql
- warehouse/dbt/models/intermediate/events/int_events.sql
- warehouse/dbt/models/playground/frax__traces.sql
- warehouse/dbt/models/playground/frax__transactions.sql
- warehouse/dbt/models/playground/mode__traces.sql
- warehouse/dbt/models/playground/pgn__traces.sql
- warehouse/dbt/models/playground/pgn__transactions.sql
- warehouse/dbt/models/playground/zora__traces.sql
- warehouse/dbt/models/playground/zora__transactions.sql
- warehouse/dbt/models/zora_sources.yml
> Set up Mode, Frax, PGN, Zora events

- warehouse/cloudquery-github-resolve-repos/package.json
- warehouse/cloudquery-github-resolve-repos/src/github/get-org-repos.ts
- warehouse/cloudquery-github-resolve-repos/src/tables.ts
> Adds license information to the github resolver

- ops/clusters/warehouse/apps.yaml
- ops/k8s-apps/base/podinfo/kustomization.yaml
- ops/k8s-apps/staging/kustomization.yaml
- ops/k8s-infrastructure/base/ingress-cloudflare.yaml
- Add a podinfo deployment
- Add apps
> Add Podinfo For testing

- .github/scripts/create-dbt-profile.sh
- .github/workflows/warehouse-run-data-pipeline.yml
- warehouse/dbt/models/intermediate/blockchain/int_optimism_transactions.sql
- warehouse/dbt/models/optimism_sources.yml
- Some small fixes for int_events
- Add base playground to the pipeline
> Fix Warehouse Pipeline

- warehouse/cloudquery-github-resolve-repos/src/tables.ts
- warehouse/cloudquery-github-resolve-repos/test.yml
> Cloudquery github resolver should handle null github fields

- warehouse/cloudquery-github-resolve-repos/src/github/get-org-repos.ts
- warehouse/cloudquery-github-resolve-repos/src/tables.ts
Closes #1434. @ccerv1 this is only a partial solution. It won't grab all languages. We will need to do more work to get that (additional API calls)
> Adds language to the github-repos resolver

- warehouse/dbt/macros/models/factory_deployments.sql
- warehouse/dbt/models/ethereum_sources.yml
- warehouse/dbt/models/intermediate/blockchain/int_derived_contracts.sql
- warehouse/dbt/models/intermediate/directory/int_artifacts_by_project.sql
- warehouse/dbt/models/staging/base/stg_base__factories.sql
- warehouse/dbt/models/staging/ethereum/stg_ethereum__factories.sql
- warehouse/dbt/models/staging/frax/stg_frax__factories.sql
- warehouse/dbt/models/staging/mode/stg_mode__factories.sql
- warehouse/dbt/models/staging/optimism/stg_optimism__factories.sql
- warehouse/dbt/models/staging/pgn/stg_pgn__factories.sql
- warehouse/dbt/models/staging/zora/stg_zora__factories.sql
> Derives all contracts from factories

- .github/workflows/ci-default.yml
- apps/frontend/app/artifact/[source]/[...name]/page.tsx
- apps/frontend/app/project/[...name]/page.tsx
- apps/frontend/components/dataprovider/event-data-provider.tsx
- apps/frontend/lib/graphql/cached-queries.ts
- apps/frontend/lib/graphql/queries.ts
- apps/frontend/lib/paths.ts
* This needs to wait until Hasura/pipeline redeploy
> fix: frontend queries to use new schema

- apps/docs/.env.local.example
- apps/docs/package.json
- apps/docs/plasmic.json
- apps/docs/plasmic.lock
- pnpm-lock.yaml
* Update deps in apps/docs
* I'm not sure where the .env.local.example went, added it back
> fix: docs build

- .github/workflows/ci-default.yml
- .github/workflows/deploy-docusaurus-docs.yml
- pnpm-lock.yaml
* Testing the GitHub actions workflow instead of Vercel
> feat: deploy docusaurus docs via GitHub Actions to Cloudflare

- ops/external-prs/package.json
- ops/external-prs/src/ossd/index.ts
- ops/external-prs/src/ossd/messages/validation-errors.md
- ops/external-prs/src/ossd/messages/validation-message.md
- pnpm-lock.yaml
* Add a summary message to ossd validation
* Separate messages by address/name
* Provide a way to share informational messages, not just errors
* Fix the status title for the GitHub app
> feat: pretty print results from external-prs

- warehouse/dbt/macros/models/contract_invocation_events_with_l1.sql
- warehouse/dbt/models/intermediate/blockchain/int_optimism_contract_invocation_events.sql
> Fixes event filtering for any_evm

- .github/workflows/test-deploy-owners.yml
- lib/oss-artifact-validators/src/onchain/evm.ts
- ops/external-prs/.env.example
- ops/external-prs/src/ossd/index.ts
* Adds validate-pr options to .env.example
* Adds base and any_evm validators to the GitHub app
* Fixes test-deploy-owners to not run for contributors
> fix: Add any_evm and base validators to PR GitHub app

- ops/external-prs/src/ossd/index.ts
So the bug was that we are using strings that don't match the oss-directory networks.
This fixes the mismatch found --- `arbitrum`, but also adds some typing to prevent this in the future.
> fix: match the validator key type from oss-directory networks

- ops/external-prs/.gitignore
- ops/external-prs/src/ossd/index.ts
- ops/external-prs/src/utils/logger.ts
* We have to wrap validators in a lambda
* Improve logger to use colorized timestamps
> fix: bug with validators

- ops/external-prs/README.md
- ops/external-prs/src/ossd/index.ts
- ops/external-prs/src/ossd/queries/blockchain_status.sql
* For some networks, we won't have validation logic. Skip those, but add an informational message
* Add better error messages in general
* Add Google project ID where applicable
* Exhaustive checking in blockchain_status
> fix: Don't throw on missing validators

- ops/external-prs/src/ossd/index.ts
- ops/external-prs/src/ossd/messages/validation-message.md
* Be more verbose, report more warnings and success cases
> fix: external-prs add warnings and successes

- warehouse/bq2cloudsql/cloudsql.py
* Limit the number of retries for CREATE INDEX to 3
* After 3 retries, just give up and keep going, rather than raise an exception
> fix: retry logic can silently just give up when creating indices

- ops/clusters/warehouse/flux-system/gotk-sync.yaml
- ops/helm-charts/oso-dagster/Chart.yaml
- ops/helm-charts/oso-dagster/templates/_helpers.tpl
- ops/helm-charts/oso-dagster/values.yaml
- Working fix for read only
- reset to main
> Proper read only fix

- warehouse/oso_dagster/utils/bq.py
- warehouse/oso_dagster/utils/retry.py
> Fix GCS loading failures

- poetry.lock
- pyproject.toml
- warehouse/cloudquery-example-plugin/pyproject.toml
- warehouse/oso_dagster/assets.py
- warehouse/oso_dagster/cbt/__init__.py
- warehouse/oso_dagster/cbt/bq.py
- warehouse/oso_dagster/cbt/context.py
- warehouse/oso_dagster/cbt/duckdb.py
- warehouse/oso_dagster/cbt/macros/__init__.py
- warehouse/oso_dagster/cbt/macros/test_macros.py
- warehouse/oso_dagster/cbt/macros/time_constrain.py
- warehouse/oso_dagster/cbt/utils/__init__.py
- warehouse/oso_dagster/cbt/utils/compare.py
- warehouse/oso_dagster/cbt/utils/replace.py
- warehouse/oso_dagster/cbt/utils/test_utils.py
- warehouse/oso_dagster/factories/goldsky/assets.py
- warehouse/oso_dagster/factories/goldsky/checks.py
- warehouse/oso_dagster/factories/goldsky/config.py
- warehouse/oso_dagster/factories/goldsky/queries/block_number_check.sql
- warehouse/oso_dagster/factories/goldsky/queries/traces_check.sql
- warehouse/oso_dagster/factories/goldsky/queries/transactions_check.sql
- warehouse/oso_dagster/utils/testing/duckdb.py
* Includes a basic sql aware transformation framework
* Includes some basic tests (not wired yet to the github actions)
* Blocks, Transactions, and Traces now have automatic checks that have a 5 day rolling window that is checked.
> Dagster Checks for Traces and Transactions

- warehouse/oso_dagster/assets.py
> Expose `full_refresh` for dbt assets

- warehouse/dbt/models/static_data_sources.yml
Adding them to dbt model sources
cc: @ryscheng
> Add OP airdrop addresses in static sources

- .github/workflows/warehouse-run-data-pipeline-cloudquery.yml
- warehouse/dbt/models/intermediate/blockchain_artifacts/int_derived_contracts.sql
> Fix `int_derived_contracts`

- poetry.lock
- pyproject.toml
- warehouse/oso_dagster/assets/__init__.py
- warehouse/oso_dagster/assets/ossd.py
- warehouse/oso_dagster/compile.py
- warehouse/oso_dagster/definitions.py
> OSS Directory as a dagster asset

- apps/docs/docs/contribute/connect-data/bigquery/replication.md
- apps/docs/docs/contribute/connect-data/gcs.md
> docs: Flesh out BigQuery Data Transfer asset guide

- apps/docs/docs/contribute/connect-data/database.md
> Connect a database documentation

- apps/docs/docs/get-started/index.mdx
- apps/docs/docs/integrate/3rd-party.mdx
- apps/docs/docs/integrate/api.md
- apps/docs/docs/integrate/index.md
- apps/docs/docs/integrate/overview/index.mdx
* Gitcoin, OpenRank, Farcaster, Lens are now on the Data Exchange.
* Update the Data Overview to showcase these datasets
* Minor text edits
> docs: Add new data sources to Data Overview

- apps/docs/docs/contribute/challenges/2024-07-02-rf4-metrics-audit.md
- warehouse/oso_dagster/assets/farcaster.py
- warehouse/oso_dagster/assets/lens.py
* Update farcaster and lens Dagster assets to have the right prefix
* Show the current challenge in the left sidebar
> fix: update some names

- warehouse/oso_dagster/factories/goldsky/assets.py
- warehouse/oso_dagster/factories/goldsky/checks.py
> Various Goldsky Asset Factory Fixes

- ops/external-prs/package.json
- ops/external-prs/src/oso/deploy.ts
- pnpm-lock.yaml
- warehouse/dbt/macros/models/factory_deployments.sql
- warehouse/dbt/macros/models/first_time_addresses.sql
- warehouse/dbt/macros/models/goog_blockchain_deployers.sql
- warehouse/dbt/macros/models/known_proxies.sql
- warehouse/dbt/macros/models/potential_bots.sql
- warehouse/dbt/macros/models/transactions_with_receipts_deployers.sql
- warehouse/dbt/models/base_playground_sources.yml
- warehouse/dbt/models/intermediate/directory/int_potential_bots.sql
- warehouse/dbt/models/marts/superchain/verification/rf4_transactions_window.sql
- warehouse/dbt/models/staging/ethereum/stg_ethereum__deployers.sql
- warehouse/dbt/models/staging/ethereum/stg_ethereum__factories.sql
- warehouse/dbt/models/staging/ethereum/stg_ethereum__potential_bots.sql
This does a few things:
* Updates models to be a little friendlier to our wallets by ensuring we don't hit the main databases when setting up a playground. 
* Ensures that any PRs _without_ changes to the dbt models do not run the deployment. 
Closes #1783
> Address ballooning costs

- .github/workflows/test-deploy/action.yml
> Fix: Checkout all history of external pr

- warehouse/oso_dagster/constants.py
- warehouse/oso_dagster/definitions.py
- warehouse/oso_dagster/resources/__init__.py
- warehouse/oso_dagster/resources/clickhouse.py
* Loads config from environment variables
> feat: add a ClickhouseResource in Dagster

- warehouse/oso_dagster/utils/bq.py
- warehouse/oso_dagster/utils/clickhouse.py
- warehouse/oso_dagster/utils/common.py
- warehouse/oso_dagster/utils/dbt.py
- warehouse/oso_dagster/utils/gcs.py
* BigQuery export to GCS
* Clickhouse create table, drop table, rename table, import data
* Adds some more comments to dbt and common
* GCS batch delete a folder in a bucket
> feat: Update Dagster utils to support bq2clickhouse copy

- warehouse/oso_dagster/assets/dbt.py
- warehouse/oso_dagster/assets/farcaster.py
- warehouse/oso_dagster/assets/lens.py
- warehouse/oso_dagster/factories/bq_dts.py
- warehouse/oso_dagster/utils/bq_dts.py
* Use the latest way to structure BigQuery Dataset configs
> fix: update BQ DTS Dagster assets

- warehouse/dbt/macros/models/first_time_addresses.sql
- warehouse/dbt/models/base_playground/base_playground__ossd_collections.sql
- warehouse/dbt/models/base_playground/base_playground__ossd_projects.sql
- warehouse/dbt/models/base_playground/base_playground__ossd_repositories.sql
- warehouse/dbt/models/intermediate/directory/int_artifacts_in_ossd_by_project.sql
- warehouse/dbt/models/intermediate/directory/int_projects.sql
- warehouse/dbt/models/marts/superchain/verification/rf4_oso_contract_discovery.sql
- warehouse/dbt/models/oss_directory_source.yml
- warehouse/dbt/models/staging/oss-directory/stg_ossd__current_collections.sql
- warehouse/dbt/models/staging/oss-directory/stg_ossd__current_projects.sql
- warehouse/dbt/models/staging/oss-directory/stg_ossd__current_repositories.sql
- warehouse/dbt/models/staging/oss-directory/stg_ossd__schema.yml
- warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
> Wire the new ossd source from dagster

- .env.example
- warehouse/oso_dagster/factories/bq2clickhouse.py
* Bucket URLs now are prefixed with gs://, so we need to check for that
> fix: bq2clickhouse

- warehouse/oso_dagster/assets/clickhouse_dbt_marts.py
- warehouse/oso_dagster/factories/bq2clickhouse.py
- warehouse/oso_dagster/factories/bq_dts.py
* Add tags and deps for these assets
> fix: Dagster tags and deps for bq2clickhouse

- warehouse/oso_dagster/definitions.py
- warehouse/oso_dagster/resources/clickhouse.py
- warehouse/oso_dagster/utils/secrets.py
We will need to rotate our clickhouse secret
> Fix secrets usage for clickhouse

- warehouse/oso_dagster/factories/common.py
- warehouse/oso_dagster/factories/goldsky/network.py
Noticed this while materializing the goldsky missing blocks data
> Fix goldsky asset dependency graph

- apps/hasura3/README.md
- apps/hasura3/globals/auth-config.cloud.hml
- apps/hasura3/oso_subgraph/metadata/ArtifactsByProjectV1.hml
- apps/hasura3/oso_subgraph/metadata/ArtifactsV1.hml
- apps/hasura3/oso_subgraph/metadata/CodeMetricsByProjectV1.hml
- apps/hasura3/oso_subgraph/metadata/CollectionsV1.hml
- apps/hasura3/oso_subgraph/metadata/ContractsV0.hml
- apps/hasura3/oso_subgraph/metadata/EventIndexingStatusByProjectV1.hml
- apps/hasura3/oso_subgraph/metadata/EventTypesV1.hml
- apps/hasura3/oso_subgraph/metadata/EventsDailyToArtifact.hml
- apps/hasura3/oso_subgraph/metadata/EventsDailyToCollection.hml
- apps/hasura3/oso_subgraph/metadata/EventsDailyToProject.hml
- apps/hasura3/oso_subgraph/metadata/EventsMonthlyToArtifact.hml
- apps/hasura3/oso_subgraph/metadata/EventsMonthlyToCollection.hml
- apps/hasura3/oso_subgraph/metadata/EventsMonthlyToProject.hml
- apps/hasura3/oso_subgraph/metadata/EventsWeeklyToArtifact.hml
- apps/hasura3/oso_subgraph/metadata/EventsWeeklyToCollection.hml
- apps/hasura3/oso_subgraph/metadata/EventsWeeklyToProject.hml
- apps/hasura3/oso_subgraph/metadata/OnchainMetricsByProjectV1.hml
- apps/hasura3/oso_subgraph/metadata/ProjectsByCollectionV1.hml
- apps/hasura3/oso_subgraph/metadata/ProjectsV1.hml
- apps/hasura3/oso_subgraph/metadata/UsersV1.hml
- apps/hasura3/oso_subgraph/metadata/oso_clickhouse-types.hml
- apps/hasura3/oso_subgraph/metadata/oso_clickhouse.hml
- apps/hasura3/package.json
* This will run metadata sync and update to allow public access
* Updated the README for instructions on how to run as well
> feat: Hasura configurations for public access

- warehouse/oso_dagster/definitions.py
- warehouse/oso_dagster/factories/goldsky/assets.py
- warehouse/oso_dagster/factories/goldsky/errors.py
> Send an alert when goldsky data is missing

- warehouse/oso_dagster/schedules.py
> Reduce dbt materializations

- warehouse/oso_dagster/assets/ossd.py
> Always materialize ossd projects and collections

- .github/workflows/ci-default.yml
- apps/frontend/app/artifact/[source]/[...name]/page.tsx
- apps/frontend/app/project/[...name]/page.tsx
- apps/frontend/lib/clickhouse/cached-queries.ts
- apps/frontend/lib/clickhouse/queries.ts
- apps/frontend/lib/clients/clickhouse.ts
- apps/frontend/lib/config.ts
> Converts cached graphql queries to use clickhouse sql client

- apps/frontend/app/project/[...name]/page.tsx
Reverts clickhouse changes just for the project page. My bad. Was wishful thinking I could just replace some of the code underneath. I _thought_ i had a similar output but it is not. So I'm looking into it now.
> Reverting project page

- apps/frontend/app/project/[...name]/page.tsx
- apps/frontend/lib/clickhouse/cached-queries.ts
- apps/frontend/lib/clickhouse/queries.ts
- apps/frontend/lib/clients/clickhouse.ts
This is now functioning completely correctly on my local tests. The fix is a bit janky, but it works for now. Was originally going for something that wouldn't change the interface much (or at all) but that ended up not actually working in practice.
> Clickhouse Fix

- warehouse/dbt/models/intermediate/metrics/int_metrics.sql
- warehouse/dbt/models/marts/metrics/timeseries_metrics_by_artifact_v0.sql
- warehouse/dbt/models/marts/metrics/timeseries_metrics_by_project_v0.sql
* Set the timeseries_metrics to be copied to Clickhouse
* Fix a bug for duplicate values in metrics_v0
> fix: Copy metrics to Clickhouse

- warehouse/oso_dagster/factories/goldsky/additional.py
- warehouse/oso_dagster/factories/goldsky/assets.py
Caught these randomly while checking in on the previous run attempt to get on a persistent node. Also the docker containers didn't build so will debug that if needed.
> Fix more op tags

- warehouse/oso_dagster/assets/dbt.py
- warehouse/oso_dagster/factories/common.py
- warehouse/oso_dagster/factories/goldsky/additional.py
- warehouse/oso_dagster/factories/goldsky/config.py
Think this might be it but merging immediately to test (really need a better staging area)
> Testing deployment options

- apps/frontend/lib/metrics-utils.ts
- apps/frontend/lib/plasmic-register.ts
- apps/frontend/plasmic-init-client.tsx
Using this so we can easily map metrics to cards in the plasmic studio. I considered just doing the transform on the backend but that would leave less flexibility for the studio.
> Convenience function for dynamic card rendering

- apps/docs/docs/integrate/overview/index.mdx
* We should not be linking to public datasets
> Update Data Overview

- .gitignore
- warehouse/oso_dagster/assets/open_collective.py
- warehouse/oso_dagster/factories/dlt.py
This PR creates a dagster asset in charge of scraping the [`Open Collective API`](https://docs.opencollective.com/help/contributing/development/api) to extract the funding in and out of collectives.
> feat: `dlt` open_collective scraper

- warehouse/dbt/models/intermediate/events/int_events_daily_to_artifact.sql
Timeseries metrics are having some issues. Let's see if this helps with that at all.
> Materialize int events daily to a table

- warehouse/dbt/models/intermediate/metrics/timeseries/int_timeseries_code_metrics_by_artifact__developers.sql
- warehouse/dbt/models/intermediate/metrics/timeseries/int_timeseries_code_metrics_by_artifact_developer_days.sql
- warehouse/dbt/models/intermediate/metrics/timeseries/int_timeseries_code_metrics_commits.sql
I don't think this is actually the best solution but might be the best thing to do to get this done quickly.
> Attempt to fix timeseries model by materializing more intermediates

- warehouse/oso_dagster/assets/open_collective.py
This PR enhances the base models for better accuracy, makes partitions since the first transaction in Open Collective, adds additional logging at various steps, and resolves a mismatch between `yield` and `yield from`.
> fix: `open_collective` scraper pipeline

- apps/frontend/components/widgets/algolia.tsx
- apps/frontend/plasmic-init-client.tsx
* This sets us up to start factoring out the search list function
> fix: rename AlgoliaSearchModal

- apps/frontend/components/widgets/algolia.tsx
- apps/frontend/plasmic-init-client.tsx
* Moving away from modal-only search for Algolia, towards a generic infinite list we can use in various places
* This removes the modal component until we implement a fully-Plasmic version of it.
> feat: Adding AlgoliaSearchList

- apps/frontend/components/widgets/algolia.tsx
- apps/frontend/plasmic-init-client.tsx
* Adding infinite scroll
* Add ability to specify the placeholder for search box
* Wire up toggle to show results on empty query
> feat: Algolia infinite scroll

- .gitignore
- model/cubes/artifacts_by_project_v1.yml
- model/cubes/artifacts_v1.yml
- model/cubes/timeseries_events_by_artifact_v0.yml
- model/views/example_view.yml
- pnpm-lock.yaml
- pnpm-workspace.yaml
- warehouse/cube/README.md
- warehouse/cube/compose.yml
- warehouse/cube/model/cubes/artifacts_by_project_v1.yml
- warehouse/cube/model/cubes/artifacts_v1.yml
- warehouse/cube/model/cubes/collections_v1.yml
- warehouse/cube/model/cubes/event_types_v1.yml
- warehouse/cube/model/cubes/from_artifacts.yml
- warehouse/cube/model/cubes/projects_by_collection_v1.yml
- warehouse/cube/model/cubes/projects_v1.yml
- warehouse/cube/model/cubes/timeseries_events_by_artifact_v0.yml
- warehouse/cube/model/cubes/to_artifacts.yml
- warehouse/cube/model/views/example_view.yml
- warehouse/cube/package.json
A basic cube dev setup. Currently it's able to get a count/sum by event types for a time period.
> Testing cube dev

- apps/frontend/components/widgets/algolia.tsx
- apps/frontend/plasmic-init-client.tsx
* Fixes infinite scroll, follows aria-hidden guidance and moves it out of the map
* Change Algolia to be loaded dynamically client-side. No need to server-side render this
* Found the issues around missing Plasmic children
> fix: algolia search

- apps/frontend/app/collections/[...name]/page.tsx
- apps/frontend/app/collections/page.tsx
- apps/frontend/lib/clickhouse/cached-queries.ts
- apps/frontend/lib/clickhouse/queries.ts
* Adding a simple collection page that builds on a table of code metrics
* Enables cross linking from collections => projects => artifacts
* Adds new queries to support this page
> feat: collection pages

- apps/frontend/components/widgets/algolia.tsx
- apps/frontend/plasmic-init-client.tsx
* Allow the ability to define multiple indices to search over
> feat: multi-index search on Algolia

- apps/frontend/components/dataprovider/metrics-data-provider.tsx
* ensure fails on the first time MetricsDataProvider is rendered. That should be expected since it takes time for data to load. We should handle that gracefully
* We weren't properly making chart categories previously. Now translating ID => name
> fix: MetricsDataProvider error

- apps/frontend/.env.local.example
- apps/frontend/components/dataprovider/apollo-wrapper.tsx
- apps/frontend/components/dataprovider/cube-data-provider.tsx
- apps/frontend/components/dataprovider/provider-view.tsx
- apps/frontend/lib/clients/cube.ts
- apps/frontend/lib/config.ts
- apps/frontend/package.json
- apps/frontend/plasmic-init-client.tsx
- pnpm-lock.yaml
* Setup the cube.dev react library to provide data as a Plasmic DataProvider
* Setup credentialing similar to how we handle Apollo
* Minor - change Apollo imports to match current conventions
> feat: CubeDataProvider

- poetry.lock
- pyproject.toml
Thanks to the sqlmesh folks the clickhouse adapter is now on the mainline of sqlmesh. This should also fix our docker build for prod.
> Fixes prod docker build

- warehouse/metrics_mesh/models/measures_factories.py
- warehouse/metrics_mesh/oso_metrics/active_days.sql
- warehouse/metrics_mesh/oso_metrics/contributor_activity_classification.sql
@ravenac95 goes with https://www.loom.com/share/720468291fa54cbe8cb99d57f12331c3?sid=5ffbe44c-2e9b-4500-8cfe-23c0b5892db7
> testing contributor activity metrics in SQL mesh

- ops/k8s-apps/base/cloudsql-proxy/proxy.yaml
- ops/k8s-apps/base/dagster/dagster.yaml
Reverts opensource-observer/oso#2041
> Revert "Redeploy with small scale up to unblock dagster"

- ops/k8s-apps/base/dagster/dagster.yaml
> Set run concurrency limit to `30`

- apps/docs/docs/how-oso-works/architecture.md
- apps/docs/package.json
- apps/docs/plasmic.json
- apps/docs/plasmic.lock
- pnpm-lock.yaml
* We've added a lot since this was last touched, including Clickhouse, sqlmesh, Apollo, Dagster.
> docs: update technical architecture

- poetry.lock
> Fixes lock for dagster-sqlmesh

- apps/docs/src/components/BlogTagsPostsPage.tsx
> docs: reduce space between heading and post list

- warehouse/metrics_mesh/lib/factories/factory.py
Started running that model `stars.sql` that we made today and that ended up actually showing me there was an additional bug with the factory that joins together all the metrics. This _hopefully_ addresses most of it, but essentially clickhouse returns a `Uint64` for `COUNT` and `Int64` for Sum and when the metrics factory joins datasets with a `UNION ALL` these two types mismatch and cause an issue. This doesn't happen on duckdb.
> Force casting during the union for clickhouse

- warehouse/oso_dagster/assets/open_collective.py
This PR enables BigQuery `partitions` for [`dlt`](https://dlthub.com/docs/dlt-ecosystem/destinations/bigquery#supported-column-hints) to avoid writes to the same location.
> add: enable bigquery `resources` on open collective

- warehouse/dbt/models/intermediate/directory/int_artifacts_in_ossd_by_project.sql
- warehouse/dbt/models/staging/oss-directory/stg_ossd__current_projects.sql
* Just pull it from the oss-directory and expose as artifacts
> feat: social media artifacts

- warehouse/oso_dagster/resources/bq_dts.py
* Provide an escape hatch for development if the impersonation env variable is not set
* Fix default credential fetching
> fix: attempting another fix at impersonating service account

- warehouse/oso_dagster/resources/bq_dts.py
* Pick a valid scope. Previously I was using a role value
> fix: trying again impersonation fix

- apps/frontend/app/api/v1/sql/route.ts
* Provide the ability to run arbitrary SQL to Clickhouse via API
* Moved the Clickhouse client to be read-only, so this should be reasonably safe for now
> feat: /api/v1/sql

- apps/frontend/app/api/v1/sql/route.ts
* Forgot an await
* Only return back the data, not metadata
> fix: /api/v1/sql bugs

- apps/frontend/app/metrics/[...name]/error.tsx
- apps/frontend/app/metrics/[...name]/page.tsx
- apps/frontend/app/metrics/page.tsx
- apps/frontend/lib/clickhouse/cached-queries.ts
- apps/frontend/lib/clickhouse/queries.ts
* This is everything related to the routing via code.
* Everything else should be able to be wired up via Plasmic
> feat: MetricPage wired up to /metrics/

- warehouse/oso_dagster/factories/sql.py
> Skip any missing table in asset configuration

- apps/docs/docs/integrate/overview/index.mdx
Added a small query as an example on how the data could be used.
PS: Seems I also did some accidental space formatting. Happy to remove that part if you want!
> Add Filecoin SQL query example

- warehouse/oso_dagster/assets/metal.py
- warehouse/oso_dagster/assets/mode.py
- warehouse/oso_dagster/factories/goldsky/assets.py
- warehouse/oso_dagster/utils/bq.py
Closes #1996 
Still testing
TODO:
> Fixes mode and metal transactions

- warehouse/oso_dagster/assets/arbitrum.py
caught this while debugging the pipeline
> fixes schema override for arbitrum

- warehouse/oso_dagster/factories/goldsky/assets.py
We introduced a bug when adding the automatic schema evolution within the goldsky factory. This now works so we shouldn't have failing daily syncs.
> Fixes for arbitrum traces backfill

- warehouse/oso_dagster/assets/open_collective.py
- warehouse/oso_dagster/schedules.py
This PR issues some simple problems, such as style fixes and lint issues. They're grouped here to avoid multiple CI runs.
> chore: miscellaneous fixes

- warehouse/oso_dagster/assets/open_collective.py
While building the `dbt` models, I realized that additional data was needed for the Open Collective model, which wasn’t available in our current data source. After reviewing the [transactions example](https://graphql-docs-v2.opencollective.com/queries/transactions#response), I found several missing fields. To resolve this, I manually added the missing fields to both the GraphQL query and the corresponding Pydantic model.
Since BigQuery supports Schema Evolution, these changes are applied in place.
> add: open collective properties needed by `dbt` models

- poetry.lock
- pyproject.toml
- warehouse/metrics_mesh/oso_metrics/active_days.sql
- warehouse/metrics_tools/models.py
This was incorrectly written before to roll up all "from addresses" together which isn't what we want for active days.
This is the first of many fixes for the metrics bugs.
> Fix metrics for active days

- apps/docs/blog/2023-11-07-open-source-open-data-open-infra.mdx
- apps/docs/blog/2023-11-20-retropgf3-ecosystem-analysis/index.md
- apps/docs/blog/2023-12-14-levels-of-the-game.mdx
- apps/docs/blog/2023-12-15-pln-ecosystem-analysis/index.mdx
- apps/docs/blog/2024-01-03-fund-your-dependencies/index.mdx
- apps/docs/blog/2024-01-19-what-builders-can-learn-from-retropgf3/index.mdx
- apps/docs/blog/2024-01-26-octant-epoch-02-ecosystem-analysis.mdx
- apps/docs/blog/2024-01-31-arb-ecosystem-analysis/index.mdx
- apps/docs/blog/2024-02-21-gitcoin-grants-impact/index.mdx
- apps/docs/blog/2024-02-28-arbitrum-impact-pools/index.mdx
- apps/docs/blog/2024-03-20-request-for-impact-metrics/index.md
- apps/docs/blog/2024-04-24-octant-epoch-03-ecosystem-analysis.md
- apps/docs/blog/2024-05-16-impact-metrics-rf4/index.md
- apps/docs/blog/2024-05-30-fil-retropgf-1/index.md
- apps/docs/blog/2024-06-29-impact-metrics-rf4-deep-dive/index.md
- apps/docs/blog/2024-07-15-impact-of-retro-funding/index.md
- apps/docs/blog/2024-07-16-oso-data-portal/index.md
- apps/docs/blog/2024-07-23-rf4-ballot-box/index.md
- apps/docs/blog/2024-08-12-war-for-public-goods/index.md
- apps/docs/blog/2024-08-30-impact-data-scientists.mdx
- apps/docs/docusaurus.config.ts
* Trying to separate out opinions, from data science, from product launches, etc.
> docs: organize blog under certain tags

- manual-work-log.md
- ops/clusters/warehouse/flux-system/gotk-sync.yaml
- ops/k8s-apps/base/trino/kustomization.yaml
- ops/k8s-apps/base/trino/trino.yaml
- ops/k8s-apps/production/kustomization.yaml
- ops/k8s-apps/production/trino/custom-helm-values.yaml
- ops/k8s-apps/production/trino/kustomization.yaml
- ops/tf-modules/warehouse-cluster/main.tf
- poetry.lock
- pyproject.toml
- warehouse/metrics_mesh/config.py
- warehouse/metrics_mesh/models/events_daily_to_artifact.sql
- warehouse/metrics_mesh/models/metrics_factories.py
- warehouse/metrics_tools/lib/factories/factory.py
- warehouse/metrics_tools/lib/factories/macros.py
So, this ended up actually being easier to configure some of the custom iceberg this just by deploying onto k8s myself. 
Very much a wip. 
Current status:
> Deploy trino

- apps/docs/docs/references/faq.md
- apps/docs/docs/references/index.md
- Just a few questions to start, we can always add more later
> docs: add an FAQ

- warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
Reverts opensource-observer/oso#2342
Double revert ftw
> Revert "revert: github `repository` model properties"

- warehouse/dbt/models/staging/oss-directory/stg_ossd__current_repositories.sql
> Ensures the correct columns in repositories

- apps/docs/docs/how-oso-works/architecture.md
- apps/docs/docs/how-oso-works/ecosystems/arbitrum.md
- apps/docs/docs/how-oso-works/impact-metrics/package.md
- apps/docs/docs/how-oso-works/oss-directory/artifact.md
- apps/docs/docs/how-oso-works/oss-directory/index.md
- apps/docs/docs/references/talks.md
> fix: typos

- warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
Some URLs in the `ossd` project's dataset are invalid, so this PR takes care of that without failing.
> fix: handle `invalid` urls in `sbom` job

- ops/tf-modules/warehouse-cluster/main.tf
- warehouse/metrics_mesh/models/events_daily_to_artifact.sql
- warehouse/metrics_tools/hack/load_sources.py
- warehouse/metrics_tools/hack/run_metrics.sh
Still not quite working, I need to scale up a bit.
> Some manual loading fixes

- ops/k8s-apps/base/trino/trino.yaml
One day we will setup a testing area for trino
> remove invalid trino configs

- warehouse/oso_dagster/dlt_sources/github_repos/__init__.py
> fix: skip malformed `sboms`

- warehouse/metrics_mesh/tests/test_developer_active_days_over_window.yml
- warehouse/metrics_mesh/tests/test_developer_active_days_to_artifact_over_60_day_window.yml
- warehouse/metrics_mesh/tests/test_events_daily_to_artifact.yml
- warehouse/metrics_tools/factory/factory.py
- warehouse/metrics_tools/transformer/tables.py
- warehouse/metrics_tools/utils/logging.py
@Jabolol Ray mentioned you ran into an issue with duckdb. I made a regression that only appeared when running locally. This should hopefully address any issues you have with writing the metrics.
This also adds a test for the regression
> Fix issues with duckdb local run

- warehouse/dbt/models/intermediate/analyses/int_github_pr_issue_threads.sql
- warehouse/dbt/models/intermediate/events/int_events__github.sql
- warehouse/dbt/models/intermediate/events/int_events_aux_issues.sql
- warehouse/dbt/models/staging/github/stg_github__comments.sql
- warehouse/dbt/models/staging/github/stg_github__issues.sql
- warehouse/dbt/models/staging/github/stg_github__pull_request_merge_events.sql
- warehouse/dbt/models/staging/github/stg_github__pull_requests.sql
Realized I could use already available fields to simplify some of the metrics.
> Add additional aux data for github issues

- warehouse/metrics_tools/models.py
This PR improves the SQLMesh diff by making it more useful and easier to read. Previously, the diff was minimized, so it was hard to see what actually changed. Now, when SQLMesh is running in local mode, the serialized config (which includes all models and metadata) is pretty-printed. This shows a clean, readable diff that highlights only the changes that matter.
cc @ravenac95 :)
> add: rich sqlmesh `markdown` diff

- poetry.lock
- pyproject.toml
* For some reason the new version leads to references.from issues
> fix: downgrade sqlfluff from 3.3.0 to 3.2.5

- warehouse/dbt/models/intermediate/directory/int_repositories.sql
- warehouse/dbt/models/marts/directory/repositories_v0.sql
- **feat(dbt): int_repositories**
- **feat(dbt): repositories mart model**
> feat(dbt): repos mart model

- warehouse/dbt/models/intermediate/directory/int_repositories.sql
- warehouse/dbt/models/marts/directory/repositories_v0.sql
- **feat(dbt): int_repositories**
- **feat(dbt): repositories mart model**
- **fix(dbt): include artifact_id**
> fix(dbt): add artifact_id to model

- warehouse/metrics_mesh/models/artifacts_by_project_v1.sql
- warehouse/metrics_mesh/models/code/first_contribution_to_artifact.sql
- warehouse/metrics_mesh/models/code/first_contribution_to_collection.sql
- warehouse/metrics_mesh/models/code/first_contribution_to_project.sql
- warehouse/metrics_mesh/models/code/issue_event_time_deltas.sql
- warehouse/metrics_mesh/models/events_daily_to_artifact.sql
- warehouse/metrics_mesh/models/events_daily_to_artifact_with_lag.sql
- warehouse/metrics_mesh/models/first_of_event_from_artifact.sql
- warehouse/metrics_mesh/models/last_of_event_from_artifact.sql
- warehouse/metrics_mesh/models/metrics_v0.sql
- warehouse/metrics_mesh/models/projects_by_collection_v1.sql
- warehouse/metrics_mesh/models/timeseries_metrics_by_artifact_v0.sql
- warehouse/metrics_mesh/models/timeseries_metrics_by_collection_v0.sql
- warehouse/metrics_mesh/models/timeseries_metrics_by_project_v0.sql
- warehouse/metrics_mesh/oso_metrics/contributor_activity_classification.sql
- warehouse/metrics_tools/factory/factory.py
- warehouse/metrics_tools/macros/macros.py
* Also added sqlmesh format changes
> Metrics model performance tweaks

- apps/docs/docs/tutorials/network-graph.md
- warehouse/dbt/models/intermediate/users/int_users.sql
- **feat(dbt): add github users to users model**
- **refactor(docs): network graph queries**
> Update user model and network graph tutorial

- docker/images/oso/Dockerfile
Not sure how this broke to be honest. It was working a couple or commits back, but it apparently doesn't like the config it had previously.
> Fixes docker build

- ops/k8s-apps/base/trino/trino.yaml
- ops/k8s-apps/production/trino/custom-helm-values.yaml
- warehouse/metrics_mesh/models/metrics_v0.sql
- warehouse/metrics_mesh/models/timeseries_metrics_by_artifact_v0.sql
- warehouse/metrics_mesh/models/timeseries_metrics_by_collection_v0.sql
- warehouse/metrics_mesh/models/timeseries_metrics_by_project_v0.sql
Testing to see if a trino direct connection to clickhouse is simpler.
> Connect trino directly to clickhouse

- warehouse/oso_dagster/assets/defillama.py
- warehouse/oso_dagster/assets/growthepie.py
Closes #2703, needed for the docs which are in progress.
> fix: dedupe `rest` resources

- warehouse/metrics_tools/compute/cache.py
- warehouse/metrics_tools/compute/manual_testing_utils.py
- warehouse/metrics_tools/compute/result.py
- warehouse/metrics_tools/compute/service.py
- warehouse/metrics_tools/compute/test_cache.py
- warehouse/metrics_tools/compute/test_service.py
- warehouse/metrics_tools/compute/types.py
- warehouse/metrics_tools/compute/worker.py
- warehouse/metrics_tools/transfer/__init__.py
- warehouse/metrics_tools/transfer/base.py
- warehouse/metrics_tools/transfer/clickhouse.py
- warehouse/metrics_tools/transfer/coordinator.py
- warehouse/metrics_tools/transfer/gcs.py
- warehouse/metrics_tools/transfer/storage.py
- warehouse/metrics_tools/transfer/trino.py
- warehouse/oso_dagster/assets/sqlmesh_export.py
- warehouse/oso_dagster/definitions.py
- warehouse/oso_dagster/resources/clickhouse.py
- warehouse/oso_dagster/resources/sqlmesh.py
- warehouse/oso_dagster/resources/storage.py
- warehouse/oso_dagster/resources/trino.py
- warehouse/oso_dagster/utils/clickhouse.py
Still incomplete but have some data on it working now.
* Refactoring a little bit to reuse some logic from the metrics calculation service
* Adds periodic cleanup
> Refactor clickhouse copy to use trino to gcs export

- apps/docs/docs/references/talks.md
Ray and Carl's Talk at L2BEAT Podcast
> Add L2BEAT Podcast Talk

- warehouse/metrics_mesh/models/intermediate/events/int_events_to_collection.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_project.sql
* We'll need these intermediate models later
> feat: int_events_to_project and int_events_to_collection

- warehouse/metrics_mesh/models/intermediate/directory/int_artifacts.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_daily_to_project.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_monthly_to_project.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_collection.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_project.sql
* Adding more event aggregate intermediate models for OpenRank calculations
> feat: pre-requisite intermediate models for DevRank

- warehouse/metrics_tools/factory/factory.py
We actually need to force recalculation of these so that's what I'm doing here, it just so happened that I needed to fix this one issue here.
> key metrics model fix

- warehouse/dbt/models/intermediate/directory/int_artifacts_in_ossd_by_project.sql
- warehouse/dbt/models/marts/metrics/optimism/int_superchain_potential_bots.sql
* This is necessary to copy them into sqlmesh
> dbt: materialize some intermediate models as tables

- warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_filtered_events.sql
- warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_onchain_builder_filter.sql
- warehouse/metrics_tools/local/utils.py
- int_superchain_potential_bots
- int_superchain_filtered_events
- int_superchain_onchain_builder_filter
- Adds these models as intermediate models in sqlmesh
> feat: intermediate models for rf7 in sqlmesh

- warehouse/metrics_mesh/config.py
- warehouse/metrics_mesh/macros/oso_source.py
- warehouse/metrics_mesh/models/artifacts_by_project_v1.sql
- warehouse/metrics_mesh/models/code/issue_event_time_deltas.sql
- warehouse/metrics_mesh/models/events_daily_to_artifact.sql
- warehouse/metrics_mesh/models/first_of_event_from_artifact.sql
- warehouse/metrics_mesh/models/intermediate/directory/int_artifacts.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_collection.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_project.sql
- warehouse/metrics_mesh/models/intermediate/superchain/devtools/int_superchain_code_dependencies.sql
- warehouse/metrics_mesh/models/intermediate/superchain/devtools/int_superchain_devtool_artifact_filter.sql
- warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_filtered_events.sql
- warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_onchain_builder_activity_metrics.sql
- warehouse/metrics_mesh/models/last_of_event_from_artifact.sql
- warehouse/metrics_mesh/models/metrics_factories.py
- warehouse/metrics_mesh/models/projects_by_collection_v1.sql
- warehouse/metrics_mesh/models/staging/defillama.py
- warehouse/metrics_mesh/models/staging/defillama/defillama.py
- warehouse/metrics_tools/local/utils.py
Turns out Trino and Duckdb have some varying capabilities for json but both didn't actually support anything we needed to run this outside of doing it with a pandas dataframe. 
This is still incomplete.
> Initial defillama staging models

- lib/oss-artifact-validators/package.json
- lib/oss-artifact-validators/src/common/interfaces.ts
- lib/oss-artifact-validators/src/index.ts
- lib/oss-artifact-validators/src/web/defillama.test.ts
- lib/oss-artifact-validators/src/web/defillama.ts
- lib/oss-artifact-validators/test/test.ts
- ops/external-prs/src/ossd/index.ts
- pnpm-lock.yaml
* This will check if the URLs are well formed
* It will also check whether the slugs are valid against the DefiLlama API
* Then I added the validator to the GitHub app so that it can generate error messages in PR comments
> feat: DefiLlama validator for oss-directory

- warehouse/metrics_mesh/models/intermediate/openrank/int_openrank_developer.py
@ryscheng this should address the openrank execution problems but I found that the query `seeded_developers_query` currently comes up empty. As opposed to getting it debugged let's just get it all running. 
Still to do:
* Fix the references to bigquery views and materialize those as tables (subsequent fix)
> Fix openrank model execution

- warehouse/dbt/models/intermediate/events/int_events__dependencies.sql
- warehouse/dbt/models/intermediate/events/int_events__open_collective.sql
* Needed for sqlmesh transition
> data: materialize int_events__* as tables

- warehouse/metrics_mesh/models/events_daily_to_artifact.sql
- warehouse/metrics_mesh/models/first_of_event_from_artifact.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_daily_to_project.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_monthly_to_project.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_collection.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_project.sql
- warehouse/metrics_mesh/models/intermediate/superchain/devtools/int_superchain_devtool_artifact_filter.sql
- warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_filtered_events.sql
- warehouse/metrics_mesh/models/last_of_event_from_artifact.sql
- warehouse/metrics_mesh/models/marts/directory/artifacts_by_user_v1.sql
- warehouse/metrics_mesh/models/marts/directory/repositories_v0.sql
- warehouse/metrics_mesh/models/marts/directory/users_v1.sql
- warehouse/metrics_mesh/models/marts/events/event_types_v1.sql
- warehouse/metrics_mesh/models/marts/events/timeseries_events_by_artifact_v0.sql
- warehouse/metrics_mesh/tests/test_events_daily_to_artifact.yml
- warehouse/metrics_tools/local/utils.py
* Removing references to timeseries_events_by_artifact_v0
* Make most of the event-based models incremental
* Placeholders for the remaining directory mart models
> feat: int_events in sqlmesh

- warehouse/metrics_mesh/macros/onchain/deployers.py
- warehouse/metrics_mesh/macros/onchain/factory_deployments.py
- warehouse/metrics_mesh/models/staging/superchain/stg_superchain__deployers.sql
- warehouse/metrics_mesh/models/staging/superchain/stg_superchain__factories.sql
- warehouse/metrics_tools/local/utils.py
- warehouse/metrics_tools/utils/glot.py
Factories and Deployers
Still more to add
Part of #2786
> Initial Superchain Models

- warehouse/metrics_mesh/macros/oso_source.py
- warehouse/metrics_tools/local/utils.py
- warehouse/metrics_tools/source/rewrite.py
Apparently broke this with the large refactor from yesterday.
> Fixes some duckdb running issues

- CONTRIBUTING.md
- README.md
- apps/frontend/next.config.js
Fixes https://github.com/opensource-observer/oso/issues/2862
> Fix docs url redirect

- README.md
- ops/opsscripts/cli.py
- poetry.lock
- pyproject.toml
- warehouse/metrics_mesh/config.py
- warehouse/metrics_mesh/macros/oso_source.py
- warehouse/metrics_tools/local/utils.py
- warehouse/oso_lets_go/cli.py
Merging this before I actually start fixing things. This is a documented usage of setting up and running trino. It does not _yet_, have the metrics calculation service wired together so that isn't being tested but in general this will work by using trino + python dataframe model to do the calculations for metrics models.
> Local Trino Sqlmesh Runner

- warehouse/oso_dagster/assets/op_atlas.py
- warehouse/oso_dagster/dlt_sources/sql_database/helpers.py
- warehouse/oso_dagster/factories/sql.py
I also manually fixed the secret.
> Additional op atlas tables

- apps/docs/docs/integrate/api.md
- apps/docs/docs/integrate/query-data.mdx
- apps/docs/docs/projects/get-project-metrics.mdx
- apps/docs/docs/projects/index.md
- apps/docs/docs/projects/update-artifacts.md
* Remove some references to dbt, replace with sqlmesh
* Update project metrics to use key metrics and timeseries metrics
> docs edits

- ops/k8s-apps/local/trino/custom-helm-values.yaml
- warehouse/metrics_mesh/macros/from_unix_timestamp.py
- warehouse/metrics_mesh/macros/onchain/deployers.py
- warehouse/metrics_mesh/models/intermediate/directory/int_projects_by_collection.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_daily_to_project.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_monthly_to_project.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_collection.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_project.sql
- warehouse/metrics_mesh/models/staging/defillama/stg__defillama.py
- warehouse/metrics_mesh/models/staging/superchain/stg_superchain__deployers.sql
- warehouse/metrics_tools/local/config.py
- warehouse/metrics_tools/local/loader.py
- warehouse/metrics_tools/local/manager.py
- warehouse/metrics_tools/local/utils.py
- warehouse/oso_lets_go/cli.py
Been at this a while, but I think this needs to be merged in.
Current status:
* Had to make some changes to the download mechanism because it was too different from how trino + bigquery actually communicated. This seems to have fixed at least the loading and creating step for sqlmesh
* Still some bugs to fix around some json things in models
* Had to fix batch sizes of some of the incremental models
TODOs:
* I need to improve the efficiency of the defillama model. It can be made to be an incremental model by only trying to add new things. 
Notes:
@IcaroG I made some changes that will likely affect what you are working on. Also, I realized that the `REAL` problem and also another `INTEGER` problem were in the same code that handled type conversions. I hackily added some additional …
> Various SQLMesh Model Fixes For Trino

- warehouse/metrics_mesh/macros/onchain/factory_deployments.py
- warehouse/metrics_mesh/macros/onchain/known_proxies.py
- warehouse/metrics_mesh/models/intermediate/defillama/int_defillama_tvl_events.sql
- warehouse/metrics_mesh/models/staging/defillama/stg_defillama.py
- warehouse/metrics_mesh/models/staging/superchain/stg_superchain__factories.sql
- warehouse/metrics_mesh/models/staging/superchain/stg_superchain__proxies.sql
- warehouse/metrics_tools/macros/macros.py
Fixes:
* Makes defillama tvl processing incremental
* This vastly improves the processing time of this model
* Fixes partitioning columns for superchain data
* Fixes the defillama intermediate model
> Sqlmesh further debugging

- ops/k8s-apps/local/trino/custom-helm-values.yaml
- poetry.lock
- pyproject.toml
- warehouse/metrics_mesh/macros/array_index.py
- warehouse/metrics_mesh/models/events_daily_to_artifact.sql
- warehouse/metrics_mesh/models/events_daily_to_artifact_with_lag.sql
- warehouse/metrics_mesh/models/intermediate/defillama/int_defillama_tvl_events.sql
- warehouse/metrics_mesh/models/intermediate/directory/int_artifacts_in_ossd_by_project.sql
- warehouse/metrics_mesh/models/intermediate/directory/int_packages.sql
- warehouse/metrics_mesh/models/intermediate/directory/int_projects.sql
- warehouse/metrics_mesh/models/intermediate/directory/int_users.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events__github.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_aux_issues.sql
- warehouse/metrics_mesh/models/marts/events/timeseries_events_by_artifact_v0.sql
- warehouse/metrics_mesh/models/staging/defillama/stg_defillama.py
- warehouse/metrics_mesh/models/staging/github/stg_github__comments.sql
- warehouse/metrics_mesh/models/staging/github/stg_github__commits.sql
- warehouse/metrics_mesh/models/staging/github/stg_github__issues.sql
- warehouse/metrics_mesh/models/staging/github/stg_github__pull_request_merge_events.sql
- warehouse/metrics_mesh/models/staging/github/stg_github__pull_requests.sql
- warehouse/metrics_mesh/models/staging/github/stg_github__push_events.sql
- warehouse/metrics_tools/local/config.py
- warehouse/metrics_tools/local/customfss.py
- warehouse/metrics_tools/local/loader.py
- warehouse/metrics_tools/local/manager.py
- warehouse/metrics_tools/local/tls_portforward.py
- warehouse/metrics_tools/utils/logging.py
- warehouse/oso_lets_go/cli.py
* Works on Trino, not on duckdb
* I realized that some of the data that we had been loading into postgres was actually the wrong format. This instead pipes the output of bigquery directly to iceberg in the local trino setup. That ended up being _closest_ to the actual data types that I've seen (though I've only spot checked)
* We need to either create macros of figure out how to fix duckdb to work with the changes in here
* Adds colorized logs (cosmetic fix)
* Fixes an issue with the `oso metrics local initialize` command hanging
cc @ryscheng could this pr is likely quite relevant to you
> SQLMesh Trino Further Debugging

- warehouse/metrics_tools/local/loader.py
Closes https://github.com/opensource-observer/oso/issues/2919
> fix(metrics): do not replace substrings accidently when fixing column types

- warehouse/metrics_mesh/macros/unnested_ref.py
- warehouse/metrics_mesh/models/intermediate/directory/int_artifacts_in_ossd_by_project.sql
Added some extensive inline docs for this in the macro. 
Closes: #2917
> A compatibility macro for unnesting in trino and duckdb

- warehouse/dbt/models/staging/open-collective/stg_open_collective__deposits.sql
- warehouse/dbt/models/staging/open-collective/stg_open_collective__expenses.sql
* Need them to be tables, not views, for sqlmesh
> fix: materialize open collective staging models

- warehouse/metrics_mesh/models/intermediate/events/int_events__funding.sql
* Tested on both DuckDB and Trino locally
> fix: replace JSON_VALUE with json_extract_scalar in int_events__funding

- warehouse/metrics_mesh/models/code/issue_event_time_deltas.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events__dependencies.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events__funding.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events__github.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_aux_issues.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_daily_to_project.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_monthly_to_project.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_collection.sql
- warehouse/metrics_mesh/models/intermediate/events/int_events_to_project.sql
- warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_events.sql
- warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_events_by_project_and_user.sql
- warehouse/metrics_mesh/models/intermediate/superchain/int_superchain_traces_txs_joined.sql
- warehouse/metrics_mesh/models/marts/events/timeseries_events_aux_issues_by_artifact_v0.sql
- warehouse/metrics_mesh/models/marts/events/timeseries_events_by_artifact_v0.sql
* Explicitly sets time ranges for all incremental models
* Fixes an issue with `int_events__dependencies` processing far too much data
> More sqlmesh production fixes

- .github/workflows/test-deploy-owners.yml
* We are slowly deprecating our use of dbt.
> fix: disabling the dbt run on test-deploy

- warehouse/oso_dagster/assets/ossd.py
- warehouse/oso_dagster/factories/bq2clickhouse.py
- warehouse/oso_dagster/factories/bq_dts.py
- warehouse/oso_dagster/factories/dlt.py
- warehouse/oso_dagster/factories/gcs.py
- warehouse/oso_dagster/factories/goldsky/additional.py
- warehouse/oso_dagster/factories/goldsky/assets.py
- warehouse/oso_dagster/factories/sql.py
- warehouse/oso_dagster/schedules.py
- warehouse/oso_dagster/utils/tags.py
Defining new jobs for closing https://github.com/opensource-observer/oso/issues/2609, https://github.com/opensource-observer/oso/issues/2598 and https://github.com/opensource-observer/oso/issues/2884
> feat: define new job for unstable data sources and for the core pipeline

- warehouse/oso_dagster/factories/alerts.py
After merging this, we can enable the sensor again to close #2761
> chore: change dagster alert to only target core jobs

- ops/k8s-operators/common/tailscale/kustomization.yaml
- ops/k8s-operators/common/tailscale/tailscale-operator.yaml
- ops/k8s-operators/gke/secrets-store-csi-driver/kustomization.yaml
- ops/k8s-operators/gke/secrets-store-csi-driver/secrets-store-csi-driver.yaml
- ops/k8s-operators/gke/tailscale/custom-helm-values.yaml
- ops/k8s-operators/gke/tailscale/kustomization.yaml
- ops/k8s-operators/gke/tailscale/secrets-provider.yaml
Trying to make accessing the cluster a little easy for myself.
> Adds tailscale and alternative secrets retrieval

- ops/k8s-apps/base/trino/trino.yaml
- ops/k8s-apps/production/trino/custom-helm-values.yaml
- ops/tf-modules/warehouse-cluster/main.tf
We are spending too much on trino and things around it. Let's attempt to use spot. Also I'm disabling the localssd which is expensive and didn't help as much as I wanted due to how we query things.
> Make trino instances spot instances

- ops/tf-modules/warehouse-cluster/main.tf
Trying to avoid issues with alerting pods not being able to schedule
> Improvements to GKE cluster

- .github/scripts/publish-docker-containers.sh
- docker/images/oso/Dockerfile
- ops/k8s-apps/production/metrics-calculation-service/custom-helm-values.yaml
- warehouse/metrics_mesh/models/metrics_factories.py
- warehouse/metrics_tools/compute/app.py
- warehouse/metrics_tools/compute/cache.py
- warehouse/metrics_tools/compute/cluster.py
- warehouse/metrics_tools/compute/service.py
- warehouse/metrics_tools/compute/test_cache.py
- warehouse/metrics_tools/compute/test_service.py
- warehouse/metrics_tools/compute/types.py
- warehouse/metrics_tools/factory/generated.py
- warehouse/metrics_tools/runner.py
- warehouse/metrics_tools/utils/tables.py
- warehouse/metrics_tools/utils/testing.py
- warehouse/oso_lets_go/cli.py
Closes #3010 
Fixes issues with MCS execution also ensures that the MCS kills the dask cluster when it's no longer in use.
> Fix MCS execution errors

- warehouse/metrics_mesh/models/marts/directory/artifacts_by_collection_v1.sql
- warehouse/metrics_mesh/models/marts/directory/artifacts_by_project_v1.sql
- warehouse/metrics_mesh/models/marts/directory/artifacts_by_user_v1.sql
- warehouse/metrics_mesh/models/marts/directory/artifacts_v1.sql
- warehouse/metrics_mesh/models/marts/directory/collections_v1.sql
- warehouse/metrics_mesh/models/marts/directory/projects_v1.sql
Add more metrics to the export list
> feat: export more metrics

- warehouse/oso_dagster/factories/alerts.py
- warehouse/oso_dagster/utils/alerts.py
Closes https://github.com/opensource-observer/oso/issues/3064
> feat(alerts): always alert when running freshness check

- apps/docs/docs/integrate/datasets/index.mdx
- warehouse/metrics_mesh/models/staging/superchain/stg_superchain__4337_traces.sql
- warehouse/metrics_mesh/models/staging/superchain/stg_superchain__4337_userop_logs.sql
- warehouse/metrics_tools/local/utils.py
- **feat: add 4337 source and staging models**
- **feat(docs): add 4337 source to docs**
> feat: add 4337 source and staging models

- ops/tf-modules/warehouse-cluster/main.tf
- warehouse/oso_dagster/schedules.py
Closes https://github.com/opensource-observer/oso/issues/3088
> Scale down resource usage

- ops/k8s-apps/production/trino/custom-helm-values.yaml
- warehouse/oso_sqlmesh/macros/hex_to_int.py
- warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__4337_traces.sql
- warehouse/oso_sqlmesh/tests/test_stg_op_atlas_project_contract.yml
- warehouse/oso_sqlmesh/tests/test_stg_op_atlas_project_farcaster.yml
- warehouse/oso_sqlmesh/tests/test_stg_op_atlas_project_repository.yml
Manually updated the permissions for the gcs user
> fix: sqlmesh + trino fixes

- ops/helm-charts/oso-dagster/Chart.lock
- ops/helm-charts/oso-dagster/Chart.yaml
This PR closes #3221 by upgrading Dagster helm charts.
> chore: upgrade `dagster` helm chart

- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_contract.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_defillama.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_deployer.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_farcaster.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_links.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_repository.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_twitter.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_website.sql
- warehouse/oso_sqlmesh/tests/test_stg_op_atlas_project_contract.yml
- warehouse/oso_sqlmesh/tests/test_stg_op_atlas_project_farcaster.yml
- warehouse/oso_sqlmesh/tests/test_stg_op_atlas_project_repository.yml
- **fix(sqlmesh): update artifact_source_ids for staging models**
- **fix(sqlmesh): use repo node id as artifact source, if it exists**
- **chore: update tests**
- **chore: add todo**
> fix(sqlmesh): modify artifact_source_id patterns for op_atlas artifacts

- pyproject.toml
- uv.lock
- warehouse/metrics_tools/factory/factory.py
- warehouse/oso_dagster/assets/sqlmesh.py
- warehouse/oso_dagster/resources/sqlmesh.py
- warehouse/oso_sqlmesh/config.py
- warehouse/oso_sqlmesh/models/intermediate/events/int_events__blockchain.sql
- warehouse/oso_sqlmesh/models/intermediate/events/int_events__dependencies.sql
- warehouse/oso_sqlmesh/models/intermediate/events/int_events__funding.sql
- warehouse/oso_sqlmesh/models/intermediate/events/int_events__github.sql
- warehouse/oso_sqlmesh/models/intermediate/metrics/int_key_metric_names_from_artifact.sql
- warehouse/oso_sqlmesh/models/intermediate/metrics/int_key_metric_names_from_collection.sql
- warehouse/oso_sqlmesh/models/intermediate/metrics/int_key_metric_names_from_project.sql
- warehouse/oso_sqlmesh/models/intermediate/metrics/int_metric_names_from_artifact.sql
- warehouse/oso_sqlmesh/models/intermediate/metrics/int_metric_names_from_collection.sql
- warehouse/oso_sqlmesh/models/intermediate/metrics/int_metric_names_from_project.sql
- warehouse/oso_sqlmesh/models/marts/metrics/key_metrics_by_artifact_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/key_metrics_by_collection_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/key_metrics_by_project_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/metrics_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/timeseries_metrics_by_artifact_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/timeseries_metrics_by_collection_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/timeseries_metrics_by_project_v0.sql
This is a fairly large PR because i needed to do the following:
* Upgrade dagster-sqlmesh
* Add tags to any metrics models
* Add jobs for sqlmesh so we can use this new metadata properly
> feat: allow subsetting sqlmesh

- warehouse/oso_dagster/assets/defillama.py
https://canary.discord.com/channels/1151273191419953224/1151273192267194380/1349754711800021002
> fix: add back `defillama` protocols

- warehouse/oso_dagster/assets/defillama.py
Hopefully this gives the pod enough resources.
> fix: increase defillama `k8s` limits even more

- warehouse/oso_dagster/assets/defillama.py
This reverts commit 8fd86d320b187ff23a89848f4b81336df2628dd3.
> Revert "add: extra `k8s` resources for defillama `tvl` asset (#3259)"

- pyproject.toml
- uv.lock
- warehouse/oso_dagster/cbt/transforms/time_constrain.py
- warehouse/oso_dagster/cbt/utils/compare.py
- warehouse/oso_dagster/utils/bq.py
Also moves ruff into dev dependencies
> chore: update ossd deps

- warehouse/oso_sqlmesh/models/intermediate/events/int_events_daily__blockchain.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/int_superchain_events_by_project.sql
- **fix(sqlmesh): use count distinct hash instead of count(*)**
- **feat(sqlmesh): unify superchain events from 4337 and blockchain models**
> feat(sqlmesh): unify 4337 and blockchain events by project

- warehouse/oso_sqlmesh/models/intermediate/events/int_events__blockchain.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/int_superchain_s7_onchain_builder_eligibility.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/int_superchain_s7_onchain_metrics_by_project.sql
- warehouse/oso_sqlmesh/models/intermediate/users/int_artifacts_by_farcaster_user.sql
- **fix(sqlmesh): group internal transactions that are related to each other**
- **fix(sqlmesh): hide null custody addresses**
- **fix(sqlemsh): include amortized transactions**
- **fix(sqlmesh): include all projects in eligibility checks**
> fix(sqlmesh): cleanup of onchain builder metrics

- warehouse/oso_sqlmesh/models/intermediate/defillama/int_defillama_protocol_mapping.sql
- warehouse/oso_sqlmesh/models/intermediate/directory/int_artifacts_by_project_in_op_atlas.sql
- warehouse/oso_sqlmesh/models/staging/defillama/stg_defillama.py
- **feat(sqlmesh): include parent protocol as a field in staging model**
- **fix(sqlmesh): lookup parent protocol for op_atlas defillama slugs**
> feat(sqlmesh): link children to defillama parent protocols in op_atlas

- warehouse/oso_sqlmesh/models/intermediate/superchain/int_superchain_traces_txs_joined.sql
- warehouse/oso_sqlmesh/models/staging/defillama/stg_defillama.py
just fyi @Jabolol, I removed the `batch_size` for the defillama python model since it's chunked now :). That should be much better
> fix: some model fixes for better wall times

- warehouse/oso_sqlmesh/models/intermediate/defillama/int_events_daily__defillama_tvl.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_onchain_builder_eligibility.sql
- **fix(sqlmesh): keep gas fees as a double not int**
- **fix(sqlmesh): user inner join for defillama artifacts**
- **chore: specify dialect**
> fix(sqlmesh): small changes to s7 metrics calcs

- apps/frontend/app/artifacts/[source]/[...name]/page.tsx
- apps/frontend/app/collections/[...name]/page.tsx
- apps/frontend/components/widgets/algolia.tsx
- apps/frontend/lib/clickhouse/metrics-config.ts
- apps/frontend/lib/clickhouse/queries.ts
* This gets us back to basic feature parity from our pre-sqlmesh days.
> fix: wired up project/collection pages to new data

- apps/frontend/app/api/v1/sql/route.ts
Closes https://github.com/opensource-observer/oso/issues/3398
> fix(sql/route): remove decodeURIComponent call as we are using POST instead of GET now

- warehouse/oso_dagster/factories/graphql.py
This PR closes #3403 by implementing robust cycle detection, proper depth handling, and enhanced error reporting. Added the `FieldExpander` class to intelligently handle complex nested fields while preventing infinite recursion. Improved type resolution logic with better scalar type mapping and edge case handling. Fixed HTTP timeout issues and added detailed logging to help diagnose query generation problems. Enhanced result processing to support both direct objects and lists.
> feat: overhaul `graphql` factory dynamic type building

- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_metrics_by_project.sql
- warehouse/oso_sqlmesh/models/staging/defillama/stg_defillama.py
- **fix(sqlmesh): turn defillama staging model into a full model instead of incremental**
- **fix(sqlmesh): add more fields to devtooling metrics summary**
> fix(sqlmesh): `stg_defillama` should be full instead of incremental

- apps/docs/docs/get-started/bigquery.mdx
- apps/docs/docs/guides/ops/gcloud.md
- apps/docs/docs/guides/ops/hasura.md
- apps/docs/docs/guides/ops/index.md
- apps/docs/docs/guides/ops/service.md
- apps/docs/docs/guides/ops/supabase.md
- apps/docs/docs/integrate/index.md
- apps/docs/docs/projects/index.md
- apps/docs/docs/references/architecture.md
- apps/docs/docs/references/ecosystems/arbitrum.md
- apps/docs/docs/references/ecosystems/pln.md
- apps/docs/docs/references/ecosystems/superchain.md
- apps/docs/docs/references/faq.md
- apps/docs/docs/references/join-team.mdx
- apps/docs/docs/references/mission.md
- apps/docs/docs/references/style-guide.md
- apps/docs/docs/references/talks.md
* Update references
* Update guides
> docs: Update references, guides

- warehouse/metrics_tools/local/utils.py
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_repositories.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_organization.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_repository.sql
- warehouse/oso_sqlmesh/tests/test_stg_op_atlas_project_repository.yml
- **fix(sqlmesh): only consider star/fork events from 2024 onwards**
- **fix(sqlmesh): link solc-js to solidity app**
> fix(sqlmesh): implement first feedback on m1 models

- warehouse/metrics_tools/definition.py
- warehouse/metrics_tools/factory/factory.py
- warehouse/metrics_tools/factory/test_factory.py
- warehouse/metrics_tools/intermediate.py
- warehouse/metrics_tools/macros/macros.py
- warehouse/metrics_tools/runner.py
- warehouse/oso_lets_go/cli.py
This is the first step to replacing our rolling windows with a simpler calculation (for the time being)
> feat: support larger time aggregation buckets

- apps/hasura-clickhouse/README.md
- apps/hasura-clickhouse/oso_subgraph/connector/oso_clickhouse/configuration.json
- apps/hasura-clickhouse/oso_subgraph/metadata/ModelsV0.hml
- apps/hasura-clickhouse/oso_subgraph/metadata/oso_clickhouse-types.hml
- apps/hasura-clickhouse/oso_subgraph/metadata/oso_clickhouse.hml
- apps/hasura-clickhouse/package.json
* Just running manually right now
* Updated package.json scripts and README to simplify deployments
> feat: refresh Hasura Clickhouse

- ops/k8s-apps/base/trino/trino.yaml
> chore: enable trino json logs

- warehouse/metrics_tools/local/utils.py
* This was manually removed from BigQuery
> fix: remove reference to stg_deps_dev__dependencies

- apps/frontend/app/api/v1/graphql/route.ts
- apps/frontend/package.json
- apps/frontend/supergraph-config.yaml
- apps/frontend/supergraph.graphql
- pnpm-lock.yaml
* Previous we'd introspect on load/runtime, which was leading to all sorts of bugs at runtime
* Now we introspect at build time, check in the schema, and load that schema.
* Following guide here https://www.apollographql.com/docs/federation/v1/gateway
> fix: GraphQL Gateway uses static schema

- .github/workflows/ci-default.yml
- warehouse/metrics_tools/seed/loader.py
- warehouse/metrics_tools/seed/seed.py
- warehouse/metrics_tools/seed/sql.py
- warehouse/oso_lets_go/cli.py
- warehouse/oso_sqlmesh/README.md
Closes https://github.com/opensource-observer/oso/issues/3387
> DuckDB local seed data

- warehouse/docker/trino/catalog/bigquery_public_data.properties
- warehouse/metrics_tools/local/utils.py
- warehouse/metrics_tools/models/constants.py
- warehouse/metrics_tools/seed/schemas/deps_dev/PackageVersionToProject.py
- warehouse/oso_sqlmesh/config.py
- warehouse/oso_sqlmesh/models/intermediate/code_artifacts/int_packages.sql
- warehouse/oso_sqlmesh/models/staging/deps-dev/stg_deps_dev__packages.sql
* This removes the last dependency on a dbt model from sqlmesh
> data: move stg_deps_dev__packages to sqlmesh

- uv.lock
- warehouse/oso_agent/README.md
- warehouse/oso_agent/main.py
- warehouse/oso_agent/pyproject.toml
Just a local setup for now. figured I'd commit this before going all in on the ops deployment
> feat: sets up arize phoenix in agent (locally)

- warehouse/oso_sqlmesh/models/intermediate/events/int_events__4337.sql
- warehouse/oso_sqlmesh/models/intermediate/events/int_events_daily__4337.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/int_superchain_events_by_project.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_onchain_metrics_by_project.sql
- warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__4337_traces.sql
- **fix(sqlmesh): keep gas_cost variable**
- **fix(sqlmesh): update gas_fee calc for AA events**
- **fix(sqlmesh): include AA userop counts as metrics**
- **chore(sqlmesh): add audit to s7 metrics model**
> fix(sqlmesh): gas and metric calcs for 4337 events

- .github/workflows/ci-default.yml
- warehouse/oso_sqlmesh/config.py
- warehouse/oso_sqlmesh/linter/incremental.py
- warehouse/oso_sqlmesh/linter/time_partitions.py
- warehouse/oso_sqlmesh/macros/semantic.py
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_deps_to_projects_graph.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_devs_to_projects_graph.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_graph.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_metrics_by_project.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_onchain_builder_nodes.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_repositories.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_trusted_developers.sql
- warehouse/oso_sqlmesh/models/marts/metrics/key_metrics_by_artifact_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/key_metrics_by_collection_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/key_metrics_by_project_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/timeseries_metrics_by_artifact_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/timeseries_metrics_by_collection_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/timeseries_metrics_by_project_v0.sql
- warehouse/oso_sqlmesh/models/metrics_factories.py
Sets up sqlmesh linter and adds rules for partitions
> chore: set up sqlmesh linter

- warehouse/oso_dagster/assets/sqlmesh.py
- warehouse/oso_sqlmesh/config.py
- warehouse/oso_sqlmesh/linter/entity_category_tags.py
- warehouse/oso_sqlmesh/models/intermediate/defillama/int_events_daily_to_project__defillama_tvl.sql
- warehouse/oso_sqlmesh/models/intermediate/directory/int_artifacts_by_collection.sql
- warehouse/oso_sqlmesh/models/intermediate/directory/int_artifacts_by_project.sql
- warehouse/oso_sqlmesh/models/intermediate/directory/int_projects.sql
- warehouse/oso_sqlmesh/models/intermediate/directory/int_projects_by_collection.sql
- warehouse/oso_sqlmesh/models/intermediate/directory/int_projects_to_projects.sql
- warehouse/oso_sqlmesh/models/intermediate/events/code/int_first_contribution_to_collection.sql
- warehouse/oso_sqlmesh/models/intermediate/events/code/int_first_contribution_to_project.sql
- warehouse/oso_sqlmesh/models/intermediate/events/int_events_daily_to_project__github.sql
- warehouse/oso_sqlmesh/models/intermediate/events/int_events_monthly_to_project__github.sql
- warehouse/oso_sqlmesh/models/intermediate/events/int_events_to_collection.sql
- warehouse/oso_sqlmesh/models/intermediate/events/int_events_to_project__github.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/int_superchain_events_by_project.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_graph.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_metrics_by_project.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_onchain_builder_nodes.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_devtooling_repositories.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_onchain_builder_eligibility.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_onchain_metrics_by_project.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/rewards/int_superchain_s7_m1_rewards.sql
- warehouse/oso_sqlmesh/models/marts/directory/artifacts_by_project_v1.sql
- warehouse/oso_sqlmesh/models/marts/directory/projects_by_collection_v1.sql
- warehouse/oso_sqlmesh/models/marts/directory/projects_v1.sql
- warehouse/oso_sqlmesh/models/marts/metrics/key_metrics_by_collection_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/key_metrics_by_project_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/timeseries_metrics_by_collection_v0.sql
- warehouse/oso_sqlmesh/models/marts/metrics/timeseries_metrics_by_project_v0.sql
- **chore(sqlmesh): add tags to projects and collection models**
- **feat(sqlmesh): add entity tags to linter**
> chore(sqlmesh): add entity category tags to models to facilitate incremental restatements

- warehouse/oso_sqlmesh/models/intermediate/superchain/int_worldchain_events_by_project.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_onchain_builder_events.sql
- warehouse/oso_sqlmesh/models/intermediate/superchain/s7/int_superchain_s7_onchain_metrics_by_project.sql
- **feat(sqlmesh): add worldchain event types by project**
- **refactor(sqlmesh): create separate incremental table for onchain builder events only**
- **refactor(sqlmesh): calculate onchain builder metrics more efficiently**
> refactor(sqlmesh): include worldchain events and refactor onchain builder event aggregations

- warehouse/oso_sqlmesh/models/intermediate/directory/int_projects_by_collection_in_op_atlas.sql
- warehouse/oso_sqlmesh/models/staging/op_atlas/stg_op_atlas_project_repository.sql
- warehouse/oso_sqlmesh/tests/test_stg_op_atlas_project_repository.yml
- **fix(sqlmesh): filter out dupe project**
- **fix(sqlmesh): add missing repo mapping**
> fix(sqlmesh): overrides for m2 data

- apps/frontend/next.config.js
* Redirect to our new Gather v2 workspace
* Redirect to our new Uptime robot page
> fix: Gather and status page redirects

- apps/frontend/app/api/v1/graphql/route.ts
- apps/frontend/app/api/v1/sql/route.ts
- apps/frontend/lib/auth/auth.ts
- apps/frontend/lib/clients/posthog.ts
* Parse the `host` from the HTTP headers and include that in `api_call` events
> feat: api_call events track origin

- apps/frontend/app/sql-studio/page.tsx
- apps/frontend/components/widgets/monaco-editor.tsx
- apps/frontend/components/widgets/oso-chat.tsx
- apps/frontend/plasmic-init-client.tsx
> feat: Register MonacoEditor, OSOChat, and sql-formatter as Plasmic

- apps/frontend/components/widgets/monaco-editor.tsx
- apps/frontend/plasmic-init-client.tsx
* Give the user the ability to pick a language in the Monaco editor
* Rename format to formatSql to be more explicit
> fix: minor changes to Plasmic components

- apps/frontend/app/api/v1/chat/route.ts
> fix: fixes system prompt typo

- uv.lock
- warehouse/oso_agent/oso_agent/agent/agent.py
- warehouse/oso_agent/oso_agent/cli/commands.py
- warehouse/oso_agent/oso_agent/server/app.py
- warehouse/oso_agent/oso_agent/server/definition.py
- warehouse/oso_agent/oso_agent/server/server.py
- warehouse/oso_agent/pyproject.toml
This follows the wire format that vercel's ai-sdk's `useChat` expects.
See: https://github.com/vercel/ai/blob/main/packages/ui-utils/src/data-stream-parts.ts
> feat: setup a chat web interface for oso_agent

- ops/clusters/warehouse/flux-system/gotk-sync.yaml
- ops/helm-charts/generic/Chart.yaml
- ops/helm-charts/generic/templates/ingress.yaml
- ops/helm-charts/generic/values.yaml
- ops/k8s-apps/base/agent/agent.yaml
- ops/k8s-apps/base/agent/kustomization.yaml
- ops/k8s-apps/production/agent/custom-helm-values.yaml
- ops/k8s-apps/production/agent/kustomization.yaml
- ops/k8s-apps/production/kustomization.yaml
- warehouse/oso_agent/oso_agent/agent/agent.py
- warehouse/oso_agent/oso_agent/agent/config.py
> feat: deploy `oso_agent`

- .github/workflows/sync-to-production.yml
- pyproject.toml
- uv.lock
- warehouse/oso_dagster/utils/kube/scaler.py
- warehouse/oso_lets_go/cli.py
Related to #2699 
One final todo after this would be to get the production branch to be tracked by flux for "production" and to create a loom to go over testing production changes
> feat: setup sync to the production branch

- warehouse/oso_lets_go/cli.py
Oddly, `requests` just doesn't work well within this context.
> fix: fixes trigger-image-update hanging

- warehouse/oso_dagster/resources/sqlmesh.py
This PR closes #3642 by implementing a batching mechanism for both the `Trino2BigQuerySQLMeshExporter` and `DuckDB2BigQuerySQLMeshExporter`.
> fix: implement batch processing for `BigQuery` transfers to handle large datasets

- warehouse/metrics_tools/transfer/bq.py
This is also needed to fix large exports.
> fix: batch `BigQuery` load jobs at `transfer` level

- apps/frontend/supabase/migrations/20250516000600_user_profiles.sql
- apps/frontend/supabase/migrations/20250516010748_unique_api_key.sql
* API keys must be unique
* rename `profiles` to user_profiles
> feat: migrations for users and API keys

- apps/frontend/components/dataprovider/oso-app-provider.tsx
- apps/frontend/lib/clients/oso-app.ts
- apps/frontend/lib/types/plasmic.ts
- apps/frontend/plasmic-init-client.tsx
* Register a component that exposes the OsoAppClient to Plasmic
* Implement both DataProvider and element actions
> feat: OsoAppProvider

- apps/frontend/components/dataprovider/oso-app-provider.tsx
- apps/frontend/lib/clients/oso-app.ts
* Promise.all doesn't do what I expect with Maps
* Fix referencing non-existent column
> fix: bugs in OsoAppProvider

- apps/frontend/components/dataprovider/oso-global-context.tsx
- apps/frontend/lib/clients/oso-app.ts
* Also added actionErrors to global state
> feat: add the ability to get/delete API keys

- apps/frontend/.env.local.example
- apps/frontend/components/dataprovider/apollo-wrapper.tsx
- apps/frontend/components/dataprovider/auth-router.tsx
- apps/frontend/components/widgets/auth-actions.tsx
- apps/frontend/components/widgets/oso-chat.tsx
- apps/frontend/lib/auth/auth.ts
- apps/frontend/lib/clients/supabase.ts
- apps/frontend/lib/config.ts
* We were getting rate limited on auth requests, so this will cache supabase.getSession() for later use
> fix: Supabase session caching

- warehouse/metrics_tools/semantic/definition.py
- warehouse/metrics_tools/semantic/example.py
- warehouse/metrics_tools/semantic/query.py
- warehouse/metrics_tools/semantic/test_definition.py
- warehouse/metrics_tools/semantic/test_query.py
- warehouse/metrics_tools/semantic/testing.py
Still a WIP, but need to get the following:
> feat: semantic querying tools

- apps/frontend/supabase/migrations/20250516185358_create_dynamic_connectors.sql
This PR addresses the changes we discussed for the supabase migration. Working locally, it is not deployed yet on prod.
> fix: include public schema and improve foreign key references

- apps/frontend/lib/clients/oso-app/oso-app.ts
This PR adds `getMyCredits` and `getMyCreditTransactions` helper plasmic glue functions.
> add: credit related `plasmic` helpers

- warehouse/metrics_tools/semantic/definition.py
- warehouse/metrics_tools/semantic/query.py
- warehouse/metrics_tools/semantic/test_definition.py
- warehouse/metrics_tools/semantic/test_query.py
- warehouse/metrics_tools/semantic/testing.py
This is actually working quite nicely. Instead of integrating this directly I created a notebook locally (currently using marimo) that uses this with pyoso.
> fix: fix issues with semantic querying

- warehouse/oso_agent/.env.example
- warehouse/oso_agent/README.md
- warehouse/oso_mcp/.env.example
- warehouse/oso_mcp/README.md
- warehouse/oso_mcp/oso_mcp/server/config.py
* Had some outdated commands.
* Fixing the .env.examples as well
> docs: Fix README for getting oso_agent running

- uv.lock
- warehouse/oso_agent/oso_agent/eval/config.py
- warehouse/oso_agent/oso_agent/eval/dataset.py
- warehouse/oso_agent/oso_agent/server/definition.py
- warehouse/oso_agent/pyproject.toml
* This is not ready for use yet, but WIP
* Adds a simple dynamic experiment, using production Phoenix Cloud datasets
> feat: add basic evals

- apps/docs/docs/contribute-data/graphql-api.md
- warehouse/oso_dagster/factories/graphql.py
This PR closes #3481 by implementing dynamic GraphQL pagination. It currently supports `OFFSET`, `CURSOR` and `RELAY` pagination. This allows for users to use the `graphql_factory` with pagination out of the box.
And example would be the following asset:
```py
from oso_dagster.factories.graphql import (
GraphQLResourceConfig,
PaginationConfig,
PaginationType,
graphql_factory,
)
def create_open_collective_transactions_asset():
"""
Create an asset that fetches all transactions from Open Collective
using offset-based pagination.
"""
config = GraphQLResourceConfig(
name="open_collective_transactions",
endpoint="https://api.opencollective.com/graphql/v2",
max_depth=2,
pagination=PaginationConfig(
type=PaginationType.OFFSET,
page_size=100,
max_pages=5,
rate_limit_seconds=0.5, …
```
> feat: implement `graphql` pagination

- warehouse/oso_agent/oso_agent/eval/text2sql.py
- warehouse/oso_agent/oso_agent/server/app.py
Cherry picked from #3924 (also fixed a merge conflict)
> fix: `uv` loop crash

- warehouse/oso_agent/.env.example
- warehouse/oso_agent/oso_agent/datasets/text2sql.py
- warehouse/oso_agent/oso_agent/datasets/uploader.py
- warehouse/oso_agent/oso_agent/eval/text2sql.py
- warehouse/oso_agent/oso_agent/types/datasets.py
* Looks for new questions in the code examples, and uploads only those
> feat: dataset diff

- apps/frontend/lib/parsing.test.ts
- apps/frontend/lib/parsing.ts
Closes https://github.com/opensource-observer/oso/issues/3937
> fix(parsing): do not throw error when failing to parse query to get table names

- warehouse/oso_agent/oso_agent/cli/commands.py
- warehouse/oso_agent/oso_agent/server/app.py
- warehouse/oso_agent/oso_agent/server/bot.py
* Can target a specific agent or just ask the default one
* Can also run experiments against specific agents now
> feat: update Discord bot to support queries

- warehouse/oso_agent/oso_agent/server/bot.py
- warehouse/oso_agent/oso_agent/util/config.py
* Use function_text2sql by default
* Return better strings for errors and responses
> feat: a bit better ergonomics for Discord bot

- apps/frontend/supabase/migrations/20250530202554_add_name_constraints.sql
Closes https://github.com/opensource-observer/oso/issues/3961
> fix: add migration to check constraints to org_name and connector_name

- ops/k8s-apps/base/agent/agent.yaml
- warehouse/oso_agent/oso_agent/cli/commands.py
- warehouse/oso_agent/oso_agent/eval/text2sql.py
- warehouse/oso_agent/oso_agent/server/app.py
- warehouse/oso_agent/oso_agent/server/bot.py
- warehouse/oso_agent/oso_agent/tool/oso_sql_db.py
- warehouse/oso_agent/oso_agent/util/asyncbase.py
Turns out we can't use the `uvicorn` cli command because nest_asyncio can't bind soon enough. 
Closes: #4012
> fix: address issues with the discord bot's event loop issues

- warehouse/metrics_tools/semantic/definition.py
- warehouse/metrics_tools/semantic/query.py
- warehouse/metrics_tools/semantic/testing.py
- warehouse/metrics_tools/utils/glot.py
Had this dangling from the weekend. Closes #3983
> feat(metric_tools/semantic): add composite key support

- warehouse/oso_sqlmesh/audits/no_gaps.sql
- warehouse/oso_sqlmesh/config.py
- warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/blockchain/deployers/int_deployers.sql
- warehouse/oso_sqlmesh/models/intermediate/events/blockchain/int_events__blockchain.sql
- warehouse/oso_sqlmesh/models/intermediate/events/blockchain/int_events__blockchain_token_transfers.sql
- warehouse/oso_sqlmesh/models/intermediate/events/blockchain/int_events_daily__blockchain.sql
- warehouse/oso_sqlmesh/models/intermediate/events/blockchain/int_events_daily__blockchain_token_transfers.sql
- warehouse/oso_sqlmesh/models/intermediate/events/blockchain/superchain/int_superchain_traces_txs_joined.sql
- warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__deployers.sql
- warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__factories.sql
- warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__traces.sql
- warehouse/oso_sqlmesh/models/staging/superchain/stg_superchain__transactions.sql
Changes: 
- **feat: allow no_gaps to have ignore_after**
- **feat: allow setting superchain_audit_end**
- **fix: temporarily set superchain_audit_end**
Notes:
Once the superchain data is fixed we should set the `superchain_audit_end` value to `"now"`
> feat(sqlmesh): allow setting superchain_audit_end

- apps/docs/docs/guides/oss-funding/index.md
- apps/docs/docs/tutorials/dependencies.mdx
- apps/docs/docs/tutorials/funding-data.mdx
- apps/docs/docs/tutorials/index.md
- apps/docs/docs/tutorials/network-graph.md
- **feat(docs): new funding tutorial**
- **fix(docs): oss-funding guide**
- **chore(docs): updates to index and sidebars**
> feat(docs): add oss-funding and funding metrics tutorial

- .github/workflows/ci-default.yml
* Remove use of Google auth
* Remove hacky public-vars population
* Remove dbt references
> fix: update ci-default to use `public` environment

- apps/frontend/components/dataprovider/oso-chat-provider.tsx
- apps/frontend/components/hooks/supabase.tsx
- apps/frontend/plasmic-init-client.tsx
* Also removes the ability to create new SupabaseClients via hook
> feat: add useChat as a Plasmic component

- uv.lock
- warehouse/oso_agent/oso_agent/agent/__init__.py
- warehouse/oso_agent/oso_agent/agent/base.py
- warehouse/oso_agent/oso_agent/agent/default.py
- warehouse/oso_agent/oso_agent/agent/function_text2sql.py
- warehouse/oso_agent/oso_agent/cli/commands.py
- warehouse/oso_agent/oso_agent/eval/experiment_registry.py
- warehouse/oso_agent/oso_agent/eval/text2sql.py
- warehouse/oso_agent/oso_agent/server/bot.py
- warehouse/oso_agent/oso_agent/tool/oso_mcp_client.py
- warehouse/oso_agent/oso_agent/tool/oso_sql_db.py
- warehouse/oso_agent/oso_agent/tool/oso_text2sql.py
- warehouse/oso_agent/oso_agent/tool/query_engine_tool.py
- warehouse/oso_agent/oso_agent/util/query.py
- warehouse/oso_agent/oso_agent/util/tracing.py
- warehouse/oso_agent/pyproject.toml
changes:
- **fix(oso_agent): fix async issues with sql similarity**
- **fix: issues with semicolons in queries**
- **fix(oso_agent): improve testing**
- **feat: change how experiments are defined**
There's still quite a bit to improve on the eval front but I think this should be merged as it cleans up quite a few things to get all this working so it's actually comparing SQL string to SQL string in the evals. We likely need to do some processing of the expected answers and the actual answer through sqlglot to normalize the string comparison
> feat: change experiment definition and improve evals

- warehouse/oso_agent/oso_agent/datasets/backlog.py
- warehouse/oso_agent/oso_agent/datasets/readme.md
- warehouse/oso_agent/oso_agent/datasets/text2sql.py
- warehouse/oso_agent/oso_agent/types/datasets.py
Deprecating spreadsheet and moving towards the `datasets.py` serving as the sole source of truth
> Evals dataset improvements

- warehouse/oso_sqlmesh/macros/onchain/factory_deployments.py
- warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/blockchain/contracts/int_contracts_root_deployers.sql
- warehouse/oso_sqlmesh/models/marts/entities/contracts_v0.sql
In helping out @Nkovaturient today I realized we needed much better docs here. @ccerv1 can you double check my column descriptions for `contracts_v0`
> chore: improve sqlmesh docs for contracts_v0

- warehouse/oso_agent/oso_agent/datasets/uploader.py
- warehouse/oso_agent/oso_agent/eval/text2sql.py
Also makes the uploading of datasets idempotent (ish) for use with testing against a local phoenix
> fix: use metadata correctly in evals

- apps/frontend/components/dataprovider/oso-chat-provider.tsx
- apps/frontend/components/dataprovider/oso-global-context.tsx
- apps/frontend/lib/clients/oso-app/oso-app.ts
- apps/frontend/lib/types/schema.ts
- apps/frontend/lib/types/supabase.ts
* Load the chat session from Supabase on first load
* Change the type to strings for the chat data
* Return the data in global actions provider
> feat: load chats properly

- ops/k8s-apps/base/agent/agent.yaml
- ops/k8s-apps/production/agent/custom-helm-values.yaml
- warehouse/oso_agent/oso_agent/agent/function_text2sql.py
- warehouse/oso_agent/oso_agent/agent/react_text2sql.py
- warehouse/oso_agent/oso_agent/cli/commands.py
- warehouse/oso_agent/oso_agent/tool/oso_text2sql.py
- warehouse/oso_agent/oso_agent/tool/query_engine_tool.py
- warehouse/oso_agent/oso_agent/util/config.py
This seems to perform pretty well. 
TODO:
> feat: add rag to the query engine

- warehouse/oso_agent/oso_agent/cli/commands.py
- warehouse/oso_agent/oso_agent/datasets/testing.py
- warehouse/oso_agent/oso_agent/datasets/text2sql.py
- warehouse/oso_agent/oso_agent/datasets/uploader.py
- warehouse/oso_agent/oso_agent/eval/experiment_registry.py
- warehouse/oso_agent/oso_agent/eval/text2sql.py
- warehouse/oso_agent/oso_agent/types/datasets.py
- warehouse/oso_agent/oso_agent/util/datasets.py
- warehouse/oso_mcp/pyproject.toml
Walked through it with @ravenac95 already, everything ran as expected locally
> feat: added functionality to run smaller subsets of evals locally

- warehouse/metrics_tools/seed/schemas/defillama/protocol_metadata.py
- warehouse/oso_dagster/assets/defillama.py
- warehouse/oso_sqlmesh/models/intermediate/entities/artifacts/defillama/int_defillama_protocol_mapping.sql
- warehouse/oso_sqlmesh/models/staging/defillama/stg_defillama__protocol_metadata.sql
- **chore(sqlmesh): add seed and staging models**
- **fix(dagster): grab all slugs not just valid ones**
- **refactor(sqlmesh): use protocol metadata model**
> chore(sqlmesh): add seed and staging models for defillama protocol metadata (plus some smol fixes)

- pyproject.toml
- uv.lock
- warehouse/oso_agent/oso_agent/agent/base.py
- warehouse/oso_agent/oso_agent/agent/decorator.py
- warehouse/oso_agent/oso_agent/agent/semantic_agent.py
- warehouse/oso_agent/oso_agent/server/bot.py
- warehouse/oso_agent/oso_agent/types/response.py
- warehouse/oso_agent/oso_agent/workflows/base.py
- warehouse/oso_agent/oso_agent/workflows/mixins.py
- warehouse/oso_agent/oso_agent/workflows/registry.py
- warehouse/oso_agent/oso_agent/workflows/test_base.py
- warehouse/oso_agent/oso_agent/workflows/text2sql/basic.py
- warehouse/oso_agent/oso_agent/workflows/types.py
Originally tried to do this with vanilla llama_index workflows but that didn't end up working. Essentially this is a way to get a bit more control of the process for each of the agents while also being able to more easily introspect each step that our agents are taking. This was a somewhat light hack on top of vanilla llama_index to allow for an ergonomic way to define everything as a set of workflow mixins. There's one more piece to this but I'd like to get #4133 merged before that integration. 
Closes #4132
> feat: adds tools for composable and introspectable workflows

- apps/frontend/app/api/v1/chat/route.ts
- apps/frontend/app/api/v1/graphql/route.ts
- apps/frontend/app/api/v1/sql/route.ts
This reverts commit 29b49cacd37915300170879051601a95fa3f2de9.
> Revert "fix: relax `credit` enforcement checks (#4208)"

- apps/frontend/app/api/v1/chat/route.ts
- apps/frontend/app/api/v1/graphql/route.ts
- apps/frontend/app/api/v1/sql/route.ts
- apps/frontend/lib/services/credits.ts
> fix: log usage `non-invasively`

- apps/frontend/__tests__/connector/route.test.ts
- apps/frontend/app/api/v1/connector/route.ts
- apps/frontend/supabase/migrations/20250617193337_change_org_name_constraint.sql
- opa/trino/trino.rego
- opa/trino/trino_test.rego
Fixes https://github.com/opensource-observer/oso/issues/4206
> fix(trino): fix trino auth to have unique separator

- apps/frontend/components/widgets/markdown.tsx
- apps/frontend/package.json
- apps/frontend/tailwind.config.js
- pnpm-lock.yaml
* https://stackoverflow.com/questions/75706164/problem-with-tailwind-css-when-using-the-react-markdown-component
> fix: use tailwindcss/typography as a hack to fix markdown rendering issues

- ops/helm-charts/generic/Chart.yaml
- ops/helm-charts/generic/templates/app.yaml
- ops/helm-charts/generic/values.yaml
- ops/k8s-apps/base/agent/agent.yaml
- warehouse/oso_agent/oso_agent/datasets/uploader.py
Also adds a livenessprobe to the deployment so we can get a "cheap" rollover deployment (hopefully it works).
> fix: fix dataset upload issues with agent experiment on prod

- warehouse/oso_agent/oso_agent/eval/experiment_runner.py
- warehouse/oso_agent/oso_agent/eval/text2sql/experiment.py
- warehouse/oso_agent/oso_agent/workflows/base.py
- warehouse/oso_agent/oso_agent/workflows/types.py
Incredibly long time to figure this out but I found some set of configuration that actually made this break locally in _i think_ a similar way to the way it breaks on prod. Hoping this is finally the issue.
> fix: workflow run issues with concurrency and error handling

- warehouse/oso_semantic/oso_semantic/definition.py
- warehouse/oso_semantic/oso_semantic/query.py
- warehouse/oso_semantic/oso_semantic/register.py
- warehouse/oso_semantic/oso_semantic/test_definition.py
- warehouse/oso_semantic/oso_semantic/testing.py
- warehouse/pyoso/pyoso/semantic.py
The last solution assumed the dag was always a tree. Now we try to build a join tree using different roots
> fix(oso_semantic): fix how we do joins

- ops/k8s-apps/production/agent/custom-helm-values.yaml
- warehouse/oso_agent/oso_agent/server/app.py
- warehouse/oso_agent/oso_agent/server/definition.py
Makes the discord bot optional
> fix: makes the discord bot optional in oso_agent

- ops/k8s-apps/production/trino/custom-helm-values.yaml
This is a test and might actually make performance much worse.
> chore: bump commit retries in trino

- apps/frontend/components/widgets/index.ts
- apps/frontend/components/widgets/tally.tsx
- apps/frontend/next.config.js
* Currently used for the sales form
> feat: adding embeddable Tally popups

- apps/frontend/components/ui/index.ts
- apps/frontend/components/ui/navigation-menu.tsx
- apps/frontend/components/ui/sidebar.tsx
- apps/frontend/components/ui/tooltip.tsx
- apps/frontend/components/widgets/index.ts
- apps/frontend/components/widgets/navbar.tsx
- apps/frontend/package.json
- pnpm-lock.yaml
* As discussed, this navbar will be coded and imported wholesale.
* Also added a tooltip component to use
> feat: Add a new NavBar

- uv.lock
- warehouse/oso_semantic/oso_semantic/definition.py
- warehouse/oso_semantic/oso_semantic/query.py
- warehouse/oso_semantic/oso_semantic/test_definition.py
- warehouse/oso_semantic/oso_semantic/test_query.py
- warehouse/oso_semantic/pyproject.toml
If there is a relationship from A -> B, when going through B we will also list A as a possible join without the need of creating a Relationship in the registry.
> [OSO-648] Fix semantic joins for undirected graph

- warehouse/oso_mcp/oso_mcp/server/config.py
> Give the secret a name beginning COPILOT_MCP_, add the secret value, then click Add secret.
This is required to run this on the repository MCP
> fix: accept `COPILOT_MCP_OSO_API_KEY` env var

- apps/frontend/app/layout.tsx
- apps/frontend/components/widgets/index.ts
- apps/frontend/components/widgets/jupyter-console.tsx
- apps/frontend/components/widgets/jupyter-meta.tsx
- apps/frontend/components/widgets/jupyter-notebook.tsx
- apps/frontend/components/widgets/jupyter-root.tsx
- apps/frontend/components/widgets/navbar.tsx
- apps/frontend/next.config.js
- apps/frontend/package.json
- pnpm-lock.yaml
* Add require.js to root layout
* Add Jupyter React components to Plasmic registration
* Add necessary webpack config to next.config.js
> feat: Jupyter React components

- uv.lock
We need to hotfix the uv-lock. That's preventing deployment.
> chore: update uv.lock

- uv.lock
- warehouse/pyoso/pyoso/analytics.py
- warehouse/pyoso/pyproject.toml
- warehouse/pyoso/tests/test_analytics.py
Moved the string logic to DataStatus and created helper function to get all the source nodes from the query
> feat(pyoso): add more helper function for analytics

- warehouse/oso_dagster/factories/graphql.py
This PR closes #4829 by fixing `offset` based pagination stopping even when `continue_on_failure` is set
> fix: advance `offset` for `continue_on_failure`

- uv.lock
- warehouse/oso_semantic/pyproject.toml
- warehouse/pyoso/pyoso/client.py
- warehouse/pyoso/pyoso/engine.py
- warehouse/pyoso/pyproject.toml
We should likely completely support this for marimo but this is a hack to get things to work. This also contains some additional pyodide fixes. 
Not implementing a fully working interface, would like to get this wired into the notebook and then address issues with it in a follow on issue. Particularly, #4867
> feat: create dbapi that is compatible with marimo

- .github/workflows/deploy-marimo-wasm.yml
> fix: marimo deploy

- apps/frontend/components/dataprovider/oso-data-provider.tsx
- apps/frontend/components/ui/sidebar.tsx
- missing children prop in SidebarMenuSubButton
- logging the OsoDataProvider
> fix: minor fixes

- apps/frontend/app/start/route.ts
- apps/frontend/lib/auth/auth.ts
- apps/frontend/lib/hooks/useAnalytics.ts
- apps/frontend/lib/hooks/useAuth.ts
- apps/frontend/lib/types/user.ts
- Removed partial schema for organization
- We always return an organization
> feat: orgId should never be undefined anymore

- warehouse/oso_sqlmesh/models/intermediate/domain-specific/superchain/s8/int_superchain_s8_devtooling_onchain_builder_nodes.sql
Previous version missed transaction counts, which we need for pretrust scores in the devtooling algo
> fix(sqlmesh): include other pretrust fields for onchain builder nodes

- apps/docs/docs/guides/ops/service.md
* Very basic start
TODOs:
Follow on work:
* Actually label data assets with `core` to determine what we believe to be in scope for 99.0% availability
> chore: add SLO docs

- .github/workflows/deploy-marimo-wasm.yml
- apps/docs/docs/guides/wasm.md
Would actually appreciate if everyone tried to set this up and run this. I also updated the workflow cause I changed some things to make the docs make a little more sense.
> chore: wasm dev docs

- uv.lock
- warehouse/pyoso/README.md
- warehouse/pyoso/pyoso/client.py
- warehouse/pyoso/pyoso/notebook.py
- warehouse/pyoso/pyoso/pyodide_only.py
- warehouse/pyoso/pyproject.toml
I found some things about pyoso and pyodide that needed some fixing.
* I noticed some strange things with requests when running with vanilla pyoso + requests. We now have an alternative path for making requests with pyoso that uses pyodide's `pyfetch`
* Adds a notebook helper `marimo_db` for use in our marimo notebooks for a succinct setup step.
> fix(pyoso): pyoso pyodide fixes

- apps/frontend/app/api/v1/marimo/ai/completion/route.ts
This PR enables stream support back to `marimo` so we remove the OpenAI format boilerplate.
AI completions (almost) work on production! This is the last missing piece of the puzzle to get everything running end to end as expected :)
> feat: stream `openai` compat response back to `marimo`

- warehouse/oso_dagster/assets/default/ethereum_blockchain.py
Had some issues with memory when running the transactions asset.
> feat(ethereum): increase dagster limits for ethereum assets

- apps/frontend/__tests__/connector/route.test.ts
- apps/frontend/app/api/v1/chat/completions/route.ts
- apps/frontend/app/api/v1/connector/route.ts
- apps/frontend/app/api/v1/jwt/route.ts
- apps/frontend/app/api/v1/responses/route.ts
- apps/frontend/app/api/v1/sql/route.ts
- apps/frontend/app/api/v1/text2sql/route.ts
- apps/frontend/app/start/route.ts
- apps/frontend/lib/analytics/track.ts
- apps/frontend/lib/auth/auth.ts
- apps/frontend/lib/services/credits.ts
- apps/frontend/lib/types/user.ts
getOrgUser requires the organization to be provided somewhere in the auth method, else it returns anonymous 
getUser might contain the organization data, but is not required
> [OSO-1004] separate getUser into getOrgUser and getUser

- apps/frontend/app/start/route.ts
> feat: /start should redirect to the onboarding wizard if you have no notebooks

- apps/frontend/app/api/v1/og/route.tsx
This PR fixes images no showing
> feat: use correct `fonts` and `images` in `og` images

- apps/frontend/lib/utils/og-metadata.ts
This will use the `database` description and use color `white` in the embed.
> chore: add `og` image color

- warehouse/oso_dagster/factories/graphql.py
> chore: catch `extra` connection errors

- uv.lock
- warehouse/pyoso/pyoso/constants.py
- warehouse/pyoso/pyproject.toml
- warehouse/pyoso/tests/test_client.py
> feat(pyoso): update pyoso base url
